### ISSUE TITLE
[BUG] `gtk::TextView::buffer` should return `Option<gtk::TextBuffer>`.

### ISSUE THREAD

**Issue by ranfdev** [gtk-rs/gtk4-rs#1005]
`gtk::TextView::set_buffer` takes an `Option<gtk::TextBuffer>`, but `gtk::TextView::buffer` returns `gtk::TextBuffer`.

This is unexpected.
Similar methods (like `HeaderBar::set_title_widget`) consistently take and return `Option<_>`

**Comment by sdroege** [comment]
`gtk_text_view_get_buffer()` is missing the `(nullable)` annotation in the C code.

**Comment by sdroege** [comment]
Judging from the code this can't actually return `NULL`:

 - https://gitlab.gnome.org/GNOME/gtk/-/blob/940248598e5bcef264aff7c18ac5e4bf5ffd2b75/gtk/gtktextview.c#L2289
 - https://gitlab.gnome.org/GNOME/gtk/-/blob/940248598e5bcef264aff7c18ac5e4bf5ffd2b75/gtk/gtktextview.c#L685

Please re-open with a testcase that fails here if there is one.
