### ISSUE TITLE
`SnapshotExt` shouldn't be listed into `gtk::Snapshot` page

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk4-rs#1015]
The trait simply doesn't exist. You can see the bug on this page: https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.Snapshot.html

**Comment by bilelmoussaoui** [comment]
It should probably exist, see #803

**Comment by bilelmoussaoui** [comment]
I am going to go ahead and close this one as we have https://github.com/gtk-rs/gtk4-rs/issues/799 for tracking a similar problem that would solve the broken doc link.
