### ISSUE TITLE
Create xtask to install application data in one go

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk4-rs#1033]
At the moment this means mostly installing and compiling gschemas.
See here for more details: https://github.com/matklad/cargo-xtask

**Comment by Hofer-Julian** [comment]
> Why introduce yet another build system? :)

What alternative do you propose?
It's not like I can use cargo to install stuff.

Also xtask is basically a shell script but in Rust.

**Comment by sdroege** [comment]
I don't really have any alternatives to propose but I'm wondering if it makes sense to introduce this in addition to meson, or maybe it makes sense to instead introduce meson earlier? Do we want people to actually use `cargo xtask` in practice?

**Comment by Hofer-Julian** [comment]
> I don't really have any alternatives to propose but I'm wondering if it makes sense to introduce this in addition to meson, or maybe it makes sense to instead introduce meson earlier? Do we want people to actually use `cargo xtask` in practice?

No, it will not be mentioned in the book.
It’s just for my convenience so I don’t habe to install everything manually.

**Comment by sdroege** [comment]
Oh I see. I thought this was something you wanted to cover in the book. Then ignore my concerns :)

**Comment by bilelmoussaoui** [comment]
you don't necessarily need to install the compiled schema, there is an env variable you can make use of btw

**Comment by Hofer-Julian** [comment]
Are you suggesting to set the env var in the code of the listings instead of installing the schemas first?

**Comment by bilelmoussaoui** [comment]
> Are you suggesting to set the env var in the code of the listings instead of installing the schemas first?

Yes, that is an option. Installing the schemas is only needed if you are distributing the application

**Comment by Hofer-Julian** [comment]
I would still need compile them somehow right?

**Comment by bilelmoussaoui** [comment]
Definitely.
