### ISSUE TITLE
[HELP] I want to use cli args with gtk4-rs, but I get error: This application can not open files.

### ISSUE THREAD

**Issue by omac777** [gtk-rs/gtk4-rs#1039]
Using this standard bit of code then invoking the gtk4-rs compiled binary without arguments works well.
```
fn main() {
    let application = gtk4::Application::new(
        Some("blah"),
        Default::default(),
    );    
    application.connect_activate(build_ui);    
    application.run();
}
```

BUT if I pass other arguments to the binary, it craps out
```
i.e. ./target/release/blah /home/davidm/someframes/
```

It will crap out. with this error:
```
(blah:14179): GLib-GIO-CRITICAL **: 12:09:24.048: This application can not open files.
```

I've tried something else, but it never displays the gui:
```
fn main() {
     let app = gtk4::Application::builder()
         .application_id("blah")
         .flags(ApplicationFlags::HANDLES_COMMAND_LINE)
         .build();
     app.connect_command_line(|app, arg| {
         println!("Handling command-line...");
 	app.connect_activate(build_ui);
 	//app.run();
 	app.run_with_args( &std::env::args().collect::<Vec<_>>() );	
         0
     });
 }
```

Any pointers suggestions?  I didn't find any clear example to achieve using cli args with gtk4-rs gui's.  Please could somebody provide one?  Thank you in advance.

**Comment by Hofer-Julian** [comment]
You need to use [`run_with_args`](https://gtk-rs.org/gtk-rs-core/stable/0.15/docs/gio/application/trait.ApplicationExtManual.html#tymethod.run_with_args).

**Comment by bilelmoussaoui** [comment]
> (blah:14179): GLib-GIO-CRITICAL **: 12:09:24.048: This application can not open files.

You need to set the appropriate ApplicationFlags for opening files as well.

**Comment by omac777** [comment]
I appreciate you taking the time to answer the question.  Thank you for that.I have attempted with run_with_args, but then the gui doesn't appear when I do that.So have any of you actually used it in a practical way?

There are easy to follow examples provided with gtk-rs to demonstrate how to use arguments with gnome and rust.Even using arguments with gnome and c++ seems convoluted.  Gnome should have just stuck the classic main(argc, argv) to retrieve the arguments.All this other api is a nuisance and annoying and a waste of time to adapt to.
I would have preferred to stick with clap crate rather than having to deal with all this gnome argument WAY-OF-DOING-THINGS...It's like gnome args api are coming from another planet or something.Ask anybody coming from regular cli tools parsing will agree with me without a doubt.  GNOME team should get rid that arg-handling api and return to the classic argc/argv stuff or adopt something like clap crate style api's.
    On Thursday, May 19, 2022, 03:01:45 p.m. EDT, Hofer-Julian ***@***.***> wrote:  
 
 


You need to use run_with_args.

**Comment by ZanderBrown** [comment]
```rust
use gtk4::{gio::ApplicationFlags, prelude::*, Application};

fn main() {
    let app = Application::new(Some("com.example.App"), ApplicationFlags::HANDLES_OPEN);

    app.connect_open(|_, files, _| {
        for file in files {
            println!("Open: {:?}", file.path());
        }
    });

    app.run();
}
```

I'd note command line isn't the only way to open files

**Comment by omac777** [comment]
I figured it out.  The trick:  pass in the same args as connect open to the build_ui

```
fn build_ui(app: &gtk4::Application, files: &[gtk4::gio::File], blah: &str ) {
    if (files.len() == 0) {
	println!("Please specify path of frames.");
	use std::process;
	process::exit(0x0100);	
    }
    
    let sgi_dir_path = files[0].path().unwrap();
    println!("The sgi dir path is {:?}", sgi_dir_path);

   //build gui as usual.
}
```

Here's the tweaked main:
```
fn main() {
    let app = Application::new(Some("com.mfw.sgi_viewer"), ApplicationFlags::HANDLES_OPEN);
    app.connect_open(build_ui);
    app.run();
}
```
