### ISSUE TITLE
[BUG] Seeking on URI videos is not possible.

### ISSUE THREAD

**Issue by samhamnam** [gtk-rs/gtk4-rs#1051]
**Bug description**

If a gio::File is created using a URI, seeking it using either the media control in Video, straight up using MediaControls, silently fails and makes the video unplayable until restart. I have not found any GTK-rs video players that successfully fix this while trying to find solutions.  If this is intended or known, it should be made clear in documentation.

[The author of Glide thought it could be due to libsoup](https://github.com/philn/glide/issues/63#issuecomment-1142030449).

**Code**
This is enough to reproduce it.
```rs
let video_file = gtk::gio::File::for_uri(
    "https://v.redd.it/3mp2tkvshs291/DASH_1080.mp4?source=fallback",
);
let video_stream = MediaFile::for_file(&video_file);
let video = Video::for_media_stream(Some(&video_stream));
parent.append(&video);
```

**Comment by sdroege** [comment]
Also better use [gstreamer](https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/) directly if you want to implement a media player. The media support in GTK is only meant for minimal things like video "icons" and such.

Note that glide is not using `gio::File` / `gtk::MediaFile`.

**Comment by bilelmoussaoui** [comment]
Glide doesn't use gtk4 neither.

**Comment by samhamnam** [comment]
My mistake!
