### ISSUE TITLE
Book tells me to install a package that doesnt exist

### ISSUE THREAD

**Issue by Dan-Gamin** [gtk-rs/gtk4-rs#1058]
In the [installation Linux section](https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_linux.html) of the book. The book tells me to run different commands depending my distro, I run the Debian ones because I'm on KDE Neon (Ubuntu-based which is Debian-based).  The command I ran is:

```sh
sudo apt install libgtk-4-dev build-essential
```

But I got the error `Unable to locate package libgtk-4-dev`. That means the package doesnt exist. What is the correct package?

**Comment by bilelmoussaoui** [comment]
I suppose your distribution is too old and doesn't have the gtk4 package in the default repository.

**Comment by sdroege** [comment]
Yes, latest KDE Neon is based on Ubuntu 20.04, which is ancient and doesn't have GTK4 yet.

**Comment by Dan-Gamin** [comment]
> Yes, latest KDE Neon is based on Ubuntu 20.04, which is ancient and doesn't have GTK4 yet.

oh... damn..
