### ISSUE TITLE
[HELP]/[BUG] Wrong type for `self` in template callback

### ISSUE THREAD

**Issue by ItsJamie9494** [gtk-rs/gtk4-rs#1063]
While using #[template_callback] on a `search-changed` signal, like so,

```rust
#[template_callback]
fn on_search_changed(&self) {
            ...
}
```

my code compiles fine, however attempting to run it results in 
```
thread 'main' panicked at 'Wrong type for `self` in template callback `on_search_changed`: WrongValueType(ValueTypeMismatchError { actual: GtkSearchEntry, requested: CUSTOM_WIDGET })', SOURCE_FILE:72:1
```

It doesn't exactly matter what the contents of the callback are, the error is the same. I'm not sure if this is a bug, or my code being written wrong. Other callbacks, not using `&self`, work fine.

I hope I've been descriptive enough, if I haven't, the full code is available at https://github.com/ItsJamie9494/nixie/blob/main/src/ui/dialogs/clock_locations.rs

**Comment by ItsJamie9494** [comment]
I was missing `swapped="true"`, my code is working now.

**Comment by AbuShawarib** [comment]
For clarification, the swapped value is set in the signal of an object in the UI file:
<signal name="clicked" handler="on_button_clicked" swapped="yes"/>
