### ISSUE TITLE
[FEATURE REQUEST] Simplified installation for Windows

### ISSUE THREAD

**Issue by blueglyph** [gtk-rs/gtk4-rs#1064]
Here's a simpler procedure if you don't want to build GTK4:

1. download the GTK4 binaries from https://github.com/ruifengx/gnome-build/releases/tag/v0.1-20220403
2. uncompress the archive in your preferred location, let's call it `%GTK4_INSTALL_DIR%`
3. download the pkg-config-lite from https://sourceforge.net/projects/pkgconfiglite/
4. uncompress the archive in your preferred location `%PKGCONFIG_INSTALL_DIR%`
5. add the following to the PATH (either user or system depending on preferences)
    - `%GTK4_INSTALL_DIR%\bin`
    - `%PKGCONFIG_INSTALL_DIR%\bin`
6. set the following environment variable (either user or system)
    - `PKG_CONFIG_PATH=%GTK4_INSTALL_DIR%\lib\pkgconfig`

I'm suggesting that here instead of doing a pull request, in case I missed something or if it doesn't work in some particular cases.

NOTE: in Windows, I'd advise those two extra steps:

- for NVIDIA card owners: disable FXAA or the text will be blurry (not sure it's been reported to GTK developers, it should since it's a known problem in frameworks like Electron, egui and so on).
- add `#![cfg_attr(windows_subsystem = "windows")]` at the start of `main.rs` if you don't want to see the command console when launching the program. Or even `#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]` if you don't want to see the debug asserts when running in debug.

**Comment by bilelmoussaoui** [comment]
I agree that providing pre-built binaries would be nice, but that is something gtk itself should provide and not gtk4-rs. We can then update the book to mention the usage of the binaries as an alternative to building gtk yourself. 

Regarding the other recommendations, please mention them in https://github.com/gtk-rs/gtk4-rs/issues/848
