### ISSUE TITLE
[BUG] TextView is not visible if default dimensions are set

### ISSUE THREAD

**Issue by bubelov** [gtk-rs/gtk4-rs#1068]
**Bug description**

Please provide a code sample as small as possible which reproduces the bug.

```rust
use gtk::prelude::*;
use gtk::{Application, ApplicationWindow, Orientation, TextBuffer, TextView};
const APP_ID: &str = "org.gtk_rs.test";

fn main() {
    let app = Application::builder().application_id(APP_ID).build();
    app.connect_activate(build_ui);
    app.run();
}

fn build_ui(app: &Application) {
    let buffer = TextBuffer::builder()
        .text("Buffer")
        .build();
    let text_view = TextView::builder()
        .buffer(&buffer)
        .build();

    let gtk_box = gtk::Box::builder()
        .orientation(Orientation::Vertical)
        .build();

    gtk_box.append(&text_view);

    let window = ApplicationWindow::builder()
        .application(app)
        .default_width(400)
        .default_height(500)
        .title("Test")
        .child(&gtk_box)
        .build();

    window.present();
}
```

- Expected result: `text_view` is visible
- Actual result: the window is completely blank

Not setting default dimensions or resizing the window manually fixes the issue. Not using a container also helps. I'm new to GTK so take this code with a grain of salt, maybe I'm not using some of those widgets properly

Environment:

```toml
gtk = { version = "0.4.8", package = "gtk4" }
```

```
pkg-config --modversion gtk4
4.6.6
```

**Comment by bilelmoussaoui** [comment]
that looks correct to me, but the result seems to be problematic. You might want to report that upstream instead as it is not a bindings problem

**Comment by bubelov** [comment]
You're right, looks like it's an old and unattended upstream issue:

https://gitlab.gnome.org/GNOME/gtk/-/issues/3635

Closing
