### ISSUE TITLE
[HELP] Configure x11 backend on Docker container

### ISSUE THREAD

**Issue by ayushmxn** [gtk-rs/gtk4-rs#1087]
If you need help to use the libraries and not the Rust API specifically, better go to <https://discourse.gnome.org> instead.

In case you need help with the Rust API, please provide as much information as possible and a sample of code as small as possible which reproduces your issue so we can help you better.

I'm trying to run a GTK4 application using Rust in a Docker container. I've got the container to build.On running it I got this error:
```
docker run ayushmxn/pahuch

(pahuch:7): Gtk-WARNING **: 05:50:26.506: cannot open display: 
```

This led me to realise that the X11/Wayland backend has to be configured. I've chosen X11 for the application but can't seem to find any documentation/tutorial on how to configure it via this package. Here's the link to the GitHub rep(r)o:

https://github.com/PahuchTech/pahuch/tree/dev-3

Instructions to build the container are here:
https://pahuchtech.github.io/pahuch/

This assumes your current working directory is the repo.

Please let me know you require any more info!

p.s.: I didn't know where to open this issue so starting here. Let me know if this isn't the correct place!

**Comment by bilelmoussaoui** [comment]
> This led me to realise that the X11/Wayland backend has to be configured. I've chosen X11 for the application but can't seem to find any documentation/tutorial on how to configure it via this package. Here's the link to the GitHub rep(r)o:

No that is not correct, you have to export the `DISPLAY` env variable. This is rather a docker question about how to run graphical user applications than the container we provide. Note that the container is meant for CI only and it is not recommended to use it as there might be API breaks that happens on upstream gtk that might break your correctly building project or that we bundle a too new version for whatever dependencies.

**Comment by ayushmxn** [comment]
Thanks for the info, closing this here.

**Comment by bilelmoussaoui** [comment]
I would recommend looking at something like Flatpak for shipping your app in a container like format, which does handle forwarding the right env variables for GUI applications whether you are using x11 or wayland.
