### ISSUE TITLE
The repository is too large

### ISSUE THREAD

**Issue by YaLTeR** [gtk-rs/gtk4-rs#1090]
It seems that the repository is currently 836 MB large:
```
┌ ~/s/rs
└─ g clone https://github.com/gtk-rs/gtk4-rs.git
Cloning into 'gtk4-rs'...
remote: Enumerating objects: 1962448, done.
remote: Counting objects: 100% (33222/33222), done.
remote: Compressing objects: 100% (550/550), done.
remote: Total 1962448 (delta 32692), reused 33126 (delta 32656), pack-reused 1929226
Receiving objects: 100% (1962448/1962448), 835.61 MiB | 487.00 KiB/s, done.
Resolving deltas: 100% (1933494/1933494), done.
```
I used a "find largest objects" script to check if any large files were left over in the history, but it doesn't seem the case:
```
┌ (master) ~/s/r/gtk4-rs
└─ git rev-list --objects --all \
       | git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' \
       | sed -n 's/^blob //p' \
       | sort --numeric-sort --key=2 \
       | tail -n 10 \
       | cut -c 1-12,41- \
       | numfmt --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
2fe0eefc08e0  5,0MiB git/docs/search-index.js
5a9fcf0d6c2f  5,0MiB git/docs/search-index.js
0be52477c4c7  5,1MiB git/docs/search-index.js
e7973bff740a  5,3MiB stable/0.4/docs/search-index.js
a3b5a3f08b18  5,5MiB git/docs/search-index.js
33878568c9d3  5,5MiB git/docs/search-index.js
6940a888d74b  5,5MiB git/docs/search-index.js
e43ce610108c  5,5MiB git/docs/search-index.js
345d7c590d98  5,5MiB git/docs/search-index.js
c60255753a3c  8,6MiB git/book/img/actions_menu.gif
```
It seems that it might be the `gh-pages` branch, which is updated very frequently, and has a ton of large `search-index.js` files. Is there a way to split it out into a different repo, or maybe graft the history at least?

**Comment by bilelmoussaoui** [comment]
I already complained to github about this and they said they were working on improving github pages, no more details or news since then. I usually clone with `--depth=1`.

**Comment by sdroege** [comment]
You can also use --branch master to get the history of the branch too

**Comment by bilelmoussaoui** [comment]
The repository should be much smaller now

**Comment by sdroege** [comment]
By accident though, or did you implement something?

**Comment by bilelmoussaoui** [comment]
I squashed the commits locally and force pushed. I am going to look at adding a weekly job that does that automatically for us

**Comment by sdroege** [comment]
Makes sense. Could this not also be done directly as part of the docs update job though?

**Comment by bilelmoussaoui** [comment]
That should be doable as well I think
