### ISSUE TITLE
[HELP]how to set theme as native on window.

### ISSUE THREAD

**Issue by nishuzumi** [gtk-rs/gtk4-rs#1108]
How to set theme as native on window.
I tried to create settings.ini file in . /etc/gtk-4.0, and the content is 
```
[Settings]
gtk-theme-name=win32
```
But it is not work.

**Comment by sdroege** [comment]
Please ask this on the GNOME discord, as it has nothing to do with the bindings themselves. It seems you also already did that here: https://discourse.gnome.org/t/gtk-rs-4-how-to-set-theme-as-native-on-window/10865
