### ISSUE TITLE
ColorChooserExtManual add_palette does not accept None even though it should

### ISSUE THREAD

**Issue by FineFindus** [gtk-rs/gtk4-rs#1114]
[According to the documentation](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.ColorChooserExtManual.html#tymethod.add_palette) it should be possible to clear the previously set palettes by passing `None` as the `colors` argument, but the type `&[RGBA]` does not allow it.

**Current behavior**
```rust
.add_palette(gtk::Orientation::Horizontal, 0, None);
```
Throws the following error:
```
mismatched types
expected reference `&[RGBA]`
        found enum `std::option::Option<_>`rustc[E0308](https://doc.rust-lang.org/error-index.html#E0308)
```
**Expected behavior**
```rust
//for clearing the palette
.add_palette(gtk::Orientation::Horizontal, 0, None);
//for adding new palettes
.add_palette(gtk::Orientation::Horizontal, 0, Some(&[gdk::RGBA::BLACK]));
```

**Comment by bilelmoussaoui** [comment]
Passing an empty slice should work fine.

**Comment by FineFindus** [comment]
It does remove the default palette. But from what I understand, passing `None` should remove all palettes. Reading this, I think it should include palettes added with `add_palette`. 
>If @colors is [None](https://doc.rust-lang.org/nightly/core/option/enum.Option.html#variant.None), removes all previously added palettes.

Passing in an empty will not remove added palettes, who where added by using `add_palette`.

**Comment by bilelmoussaoui** [comment]
Passing None shouldn't change much from the bindings perspective.

**Comment by FineFindus** [comment]
Sorry if I am a bit naive today, but if passing either None or an empty slice have the same result, does that that it is not possible to remove palettes after adding them?

**Comment by bilelmoussaoui** [comment]
Note that the documentation is the C docs automatically modified to use Rust "notions"  but as C doesn't have the concept of an empty array/slice, you pass a NULL `@colors` which is what gets converted to the `None` in the docs. 

I would think this is an issue in the widget itself and not the bindings gtk4-rs provides. You could copy the ffi function call and use it in your own project and see if actually passing None changes anything, it won't.

**Comment by FineFindus** [comment]
Interesting, I did not know that. I will close it then.

**Comment by bilelmoussaoui** [comment]
I would recommend opening an issue at https://gitlab.gnome.org/GNOME/gtk with a small reproducer.

**Comment by FineFindus** [comment]
I tried to create a reproducible sample in C, but it works according to the docs.
Unless I made a mistake or overlooked something, it seems to be a bug in the bindings and not the widget.

<details>
  <summary>Example code</summary>
  
```c
#include <gtk/gtk.h>

#define COLOR(r, g, b)                    \
    {                                     \
        r / 255., g / 255., b / 255., 1.0 \
    }

static void
app_activate(GApplication *app, gpointer user_data)
{
    GtkWidget *win;
    GtkWidget *picker;

    GdkRGBA solarized[] = {
        COLOR(0xff, 0xff, 0xff),
        COLOR(0x07, 0x36, 0x42),
        COLOR(0xdc, 0x32, 0x2f),
        COLOR(0x85, 0x99, 0x00),
        COLOR(0xb5, 0x89, 0x00),
        COLOR(0x26, 0x8b, 0xd2),
        COLOR(0xd3, 0x36, 0x82),
        COLOR(0x2a, 0xa1, 0x98),
        COLOR(0xee, 0xe8, 0xd5),

        COLOR(0x00, 0x00, 0x00),
        COLOR(0x00, 0x2b, 0x36),
        COLOR(0xcb, 0x4b, 0x16),
        COLOR(0x58, 0x6e, 0x75),
        COLOR(0x65, 0x7b, 0x83),
        COLOR(0x83, 0x94, 0x96),
        COLOR(0x6c, 0x71, 0xc4),
        COLOR(0x93, 0xa1, 0xa1),
        COLOR(0xfd, 0xf6, 0xe3),
    };

    win = gtk_application_window_new(GTK_APPLICATION(app));
    gtk_window_set_title(GTK_WINDOW(win), "example");
    gtk_window_set_default_size(GTK_WINDOW(win), 400, 300);

    picker = gtk_color_button_new();
    gtk_color_button_set_title(GTK_COLOR_BUTTON(picker), "Solarized colors");
    gtk_color_chooser_add_palette(GTK_COLOR_CHOOSER(picker),
                                  GTK_ORIENTATION_HORIZONTAL,
                                  9,
                                  18,
                                  solarized);

    //if this code is commented out, two palettes are shown
    gtk_color_chooser_add_palette(GTK_COLOR_CHOOSER(picker),
                                  GTK_ORIENTATION_HORIZONTAL,
                                  9,
                                  18,
                                  NULL);

    gtk_color_chooser_add_palette(GTK_COLOR_CHOOSER(picker),
                                  GTK_ORIENTATION_HORIZONTAL,
                                  9,
                                  18,
                                  solarized);

    gtk_window_set_child(GTK_WINDOW(win), picker);

    gtk_widget_show(win);
}

int main(int argc, char **argv)
{
    GtkApplication *app;
    int stat;

    app = gtk_application_new("com.bug.example", G_APPLICATION_FLAGS_NONE);
    g_signal_connect(app, "activate", G_CALLBACK(app_activate), NULL);
    stat = g_application_run(G_APPLICATION(app), argc, argv);
    g_object_unref(app);
    return stat;
}
```

</details>

**Comment by sdroege** [comment]
I assume the function makes a distinction between `NULL` and an empty array.
