### ISSUE TITLE
[HELP] How to get started with Cairo

### ISSUE THREAD

**Issue by mygnu** [gtk-rs/gtk4-rs#1126]
I would like to convert my TUI app to gtk, one of the main requirements is drawing a line graph(smooth) and updating it on short intervals, very similar to gnome system monitor cpu graph. I cannot find any examples here. Can someone please point me to right place. 
Thank you

**Comment by bilelmoussaoui** [comment]
Process viewer has that https://github.com/GuillaumeGomez/process-viewer, adding a small example in the gtk4-rs repo would be great.

**Comment by mygnu** [comment]
> Process viewer has that https://github.com/GuillaumeGomez/process-viewer, adding a small example in the gtk4-rs repo would be great.

Great thanks, that's exactly what I'm looking for. I'll try making a minimal example as well.

**Comment by sdroege** [comment]
Generally for cairo the documentation on https://www.cairographics.org/documentation/ is very good too. The tutorial, cookbook, samples/examples specifically.

**Comment by bilelmoussaoui** [comment]
I am going to go ahead and close this one.
