### ISSUE TITLE
[BUG] 'STATUS_ACCESS_VIOLATION' on Windows 10

### ISSUE THREAD

**Issue by Joezeo** [gtk-rs/gtk4-rs#1143]
**Bug description**
I was installed gtk4 by vcpkg command `vcpkg install gtk --triplet x64-windows`.  
error message after `cargo run`:  
> error: process didn't exit successfully: `target\debug\my-gtk-app.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

It runs normal when I execute the code below:  
```rust
use gtk::prelude::*;
use gtk::{Application, ApplicationWindow};

const APP_ID: &str = "orh.toocol.HelloWorld";

fn main() {
    let app = Application::builder().application_id(APP_ID).build();

    app.connect_activate(build_ui);

    app.run();
}

fn build_ui(app: &Application) {
    let window = ApplicationWindow::builder()
        .application(app)
        .title("My Gtk App")
        .default_width(400)
        .default_height(300)
        .build();

    window.present();
}
```
But when I add the Button, it runs failed with `STATUS_ACCESS_VIOLATION`:  
```rust
use gtk::prelude::*;
use gtk::{Application, ApplicationWindow, Button};

const APP_ID: &str = "orh.toocol.HelloWorld";

fn main() {
    let button = Button::builder()
        .label("Press me")
        .margin_top(12)
        .margin_bottom(12)
        .margin_start(12)
        .margin_end(12)
        .build();

    button.connect_clicked(move |button| {
        button.set_label("Hello World!");
    });

    let app = Application::builder().application_id(APP_ID).build();

    app.connect_activate(build_ui);

    app.run();
}

fn build_ui(app: &Application) {
    let window = ApplicationWindow::builder()
        .application(app)
        .title("My Gtk App")
        .default_width(400)
        .default_height(300)
        .build();

    window.present();
}

```

And according to this [gist](https://gist.github.com/Ep0chalypse/0e0f9ef43eb7f0218eaa8fe0822f3d36), I checked the dlls this app used and I didn't find anything wrong:  
<details>
<summary>dll list</summary>
my-gtk-app.exe pid: 327360
Command line: my-gtk-app.exe

Base                Size      Path
0x000000003c5f0000  0x64000   D:\workspace\projects\my-gtk-app\target\debug\my-gtk-app.exe
0x00000000d8eb0000  0x1f8000  C:\WINDOWS\SYSTEM32\ntdll.dll
0x00000000d6fc0000  0xbd000   C:\WINDOWS\System32\KERNEL32.DLL
0x00000000d6b70000  0x2ce000  C:\WINDOWS\System32\KERNELBASE.dll
0x00000000d6730000  0x100000  C:\WINDOWS\System32\ucrtbase.dll
0x0000000028ce0000  0x75a000  C:\vcpkg\installed\x64-windows\bin\gtk-4-1.dll
0x00000000bd9d0000  0x51000   C:\vcpkg\installed\x64-windows\bin\gobject-2.0-0.dll
0x0000000064560000  0x196000  C:\vcpkg\installed\x64-windows\bin\gio-2.0-0.dll
0x0000000064420000  0x138000  C:\vcpkg\installed\x64-windows\bin\glib-2.0-0.dll
0x00000000c5d50000  0x1b000   C:\WINDOWS\SYSTEM32\VCRUNTIME140.dll
0x00000000d8700000  0x55000   C:\WINDOWS\System32\SHLWAPI.dll
0x00000000d8550000  0x6b000   C:\WINDOWS\System32\WS2_32.dll
0x00000000d80f0000  0x9e000   C:\WINDOWS\System32\msvcrt.dll
0x00000000d8c90000  0x125000  C:\WINDOWS\System32\RPCRT4.dll
0x00000000d7ef0000  0x1a0000  C:\WINDOWS\System32\USER32.dll
0x00000000d8b10000  0xae000   C:\WINDOWS\System32\ADVAPI32.dll
0x00000000d6b40000  0x22000   C:\WINDOWS\System32\win32u.dll
0x00000000d71b0000  0x743000  C:\WINDOWS\System32\SHELL32.dll
0x00000000d8660000  0x9c000   C:\WINDOWS\System32\sechost.dll
0x00000000d7eb0000  0x2a000   C:\WINDOWS\System32\GDI32.dll
0x00000000d6e70000  0x9d000   C:\WINDOWS\System32\msvcp_win.dll
0x00000000d6620000  0x10b000  C:\WINDOWS\System32\gdi32full.dll
0x00000000d7080000  0x12a000  C:\WINDOWS\System32\ole32.dll
0x00000000d21d0000  0xc000    C:\vcpkg\installed\x64-windows\bin\libffi.dll
0x00000000d69e0000  0x156000  C:\WINDOWS\System32\CRYPT32.dll
0x00000000d81f0000  0x354000  C:\WINDOWS\System32\combase.dll
0x00000000d7e00000  0x30000   C:\WINDOWS\System32\IMM32.dll
0x00000000d7990000  0x46f000  C:\WINDOWS\System32\SETUPAPI.dll
0x00000000d65d0000  0x4e000   C:\WINDOWS\System32\cfgmgr32.dll
0x00000000d21c0000  0x9000    C:\vcpkg\installed\x64-windows\bin\gmodule-2.0-0.dll
0x00000000d6e40000  0x27000   C:\WINDOWS\System32\bcrypt.dll
0x00000000becf0000  0x1a000   C:\vcpkg\installed\x64-windows\bin\zlib1.dll
0x00000000674c0000  0x67000   C:\vcpkg\installed\x64-windows\bin\pcre.dll
0x00000000d8a30000  0xda000   C:\WINDOWS\System32\COMDLG32.dll
0x00000000d8dc0000  0xad000   C:\WINDOWS\System32\shcore.dll
0x00000000bdaa0000  0x1a000   C:\vcpkg\installed\x64-windows\bin\intl-8.dll
0x0000000062960000  0x10b000  C:\vcpkg\installed\x64-windows\bin\iconv-2.dll
0x00000000bd620000  0x12000   C:\vcpkg\installed\x64-windows\bin\pangocairo-1.0-0.dll
0x00000000d5a70000  0xca000   C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x00000000d5a30000  0x3b000   C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x000000006bea0000  0x5d000   C:\vcpkg\installed\x64-windows\bin\pango-1.0-0.dll
0x0000000062860000  0xf8000   C:\vcpkg\installed\x64-windows\bin\harfbuzz.dll
0x0000000064340000  0xdf000   C:\vcpkg\installed\x64-windows\bin\cairo-2.dll
0x00000000bbb90000  0x21000   C:\vcpkg\installed\x64-windows\bin\fribidi-0.dll
0x00000000bf020000  0xb000    C:\vcpkg\installed\x64-windows\bin\cairo-gobject-2.dll
0x000000008f790000  0x45000   C:\vcpkg\installed\x64-windows\bin\gdk_pixbuf-2.0-0.dll
0x000000002cd10000  0x167000  C:\vcpkg\installed\x64-windows\bin\epoxy-0.dll
0x00000000b9350000  0x19000   C:\vcpkg\installed\x64-windows\bin\graphene-1.0-0.dll
0x00000000b9130000  0x12000   C:\vcpkg\installed\x64-windows\bin\pangowin32-1.0-0.dll
0x00000000c6ca0000  0x29a000  C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll
0x00000000d4300000  0x2f000   C:\WINDOWS\SYSTEM32\dwmapi.dll
0x00000000cd890000  0x27000   C:\WINDOWS\SYSTEM32\WINMM.dll
0x0000000066520000  0x72000   C:\vcpkg\installed\x64-windows\bin\tiff.dll
0x00000000d4e80000  0xd000    C:\WINDOWS\SYSTEM32\HID.DLL
0x00000000ac120000  0x35000   C:\vcpkg\installed\x64-windows\bin\libpng16.dll
0x00000000627c0000  0x9c000   C:\vcpkg\installed\x64-windows\bin\jpeg62.dll
0x00000000b82e0000  0x24000   C:\vcpkg\installed\x64-windows\bin\cairo-script-interpreter-2.dll
0x00000000cd240000  0x98000   C:\WINDOWS\SYSTEM32\WINSPOOL.DRV
0x00000000b9110000  0x18000   C:\vcpkg\installed\x64-windows\bin\pangoft2-1.0-0.dll
0x000000008b560000  0x4a000   C:\vcpkg\installed\x64-windows\bin\fontconfig-1.dll
0x00000000c4aa0000  0xc000    C:\WINDOWS\SYSTEM32\VCRUNTIME140_1.dll
0x0000000062710000  0xac000   C:\vcpkg\installed\x64-windows\bin\freetype.dll
0x00000000cfe50000  0x7000    C:\WINDOWS\SYSTEM32\MSIMG32.dll
0x000000005fd60000  0x93000   C:\vcpkg\installed\x64-windows\bin\pixman-1-0.dll
0x00000000b6780000  0x2b000   C:\vcpkg\installed\x64-windows\bin\liblzma.dll
0x00000000b36a0000  0x1f000   C:\vcpkg\installed\x64-windows\bin\lzo2.dll
0x00000000aca90000  0x2a000   C:\vcpkg\installed\x64-windows\bin\libexpat.dll
0x00000000d63d0000  0xa000    C:\WINDOWS\SYSTEM32\DPAPI.DLL
0x00000000b2860000  0x18000   C:\vcpkg\installed\x64-windows\bin\bz2.dll
0x00000000bef20000  0x10000   C:\vcpkg\installed\x64-windows\bin\brotlidec.dll
0x00000000abfb0000  0x27000   C:\vcpkg\installed\x64-windows\bin\brotlicommon.dll
0x00000000d7980000  0x8000    C:\WINDOWS\System32\NSI.dll
0x00000000d44e0000  0x12000   C:\WINDOWS\SYSTEM32\kernel.appcore.dll
Error opening my-gtk-app.exe(327404):
</details>

**Comment by sdroege** [comment]
Can you get a backtrace of the crash?

**Comment by Joezeo** [comment]
@sdroege It seems no backtrace info
![QQ截图20221009190231](https://user-images.githubusercontent.com/30520229/194753218-f333c47e-cb3b-4857-ad20-57bd1e6dc3a8.png)

**Comment by sdroege** [comment]
Run in a debugger to get one :) If you use the mingw toolchain please use gdb, if you use the Visual Studio toolchain use the debugger from Visual Studio

**Comment by sdroege** [comment]
@Joezeo What was the problem in the end?

**Comment by Joezeo** [comment]
@sdroege It's not the dll problem. I created the Button before the Application was activated. I've been thinking in the wrong direction before, sorry about that:)

**Comment by bilelmoussaoui** [comment]
Ah yeah, creating the application would run `gtk::init` for you and creating the button before that would panic.
