### ISSUE TITLE
[FEATURE REQUEST] Implement ToValueOptional for more primitive types

### ISSUE THREAD

**Issue by matbme** [gtk-rs/gtk4-rs#1145]
[ToValueOptional](https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/value/trait.ToValueOptional.html#) is currently only implemented for `str`, `String` and `NonNulll<Pointee>`. Is there a specific reason for that? 

If not, it would be interesting to create these implementations for allowing properties containing Optional primitive types like `f32`, `i32`, etc, via `ParamSpecEnum`.

**Comment by sdroege** [comment]
`glib::Value` can't contain optional primitive types unfortunately, so that's not possible.
