### ISSUE TITLE
[BUG] Incorrect text kerning on Windows

### ISSUE THREAD

**Issue by BillyDM** [gtk-rs/gtk4-rs#1148]
The kerning of text is weird on Windows. It looks fine under Linux and MacOS.

I'm using an up-to-date version of Windows 11. I've tried both the MSVC toolchain and the GNU toolchain, but they both had the same problem.

I'm not sure if this is an issue related to gtk4-rs or if it's an issue with gtk4 itself, but I figured I would try here first.

![Screenshot 2022-10-12 184109](https://user-images.githubusercontent.com/60663878/195467929-f1818600-8964-4169-b32a-0156f0ad8eec.png)

**Comment by bilelmoussaoui** [comment]
Definitely a  gtk4 issue or some missing font/wrong configuration, let us know what was wrong once you figure it out but I would recommend opening an issue upstream instead.
