### ISSUE TITLE
[BUG] Showing Dialog after closing it freezes the application

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk4-rs#1149]
### Steps to reproduce

1. Create a modal `MessageDialog`
2. Call `run_future`
3. Call `run_future` again

### Expected result

The second call to `run_future` works the same as the first call.

### Actual result

On the second call to `run_future`, the dialog doesn't show up, but freezes the application.
The dialog can still be closed with the `Esc` key while invisible and the future returns the correct value, but the application remains frozen.

There's some weird stuff you can do with inspector. Once the dialog closes for the first time, the dialog disappears from the widget overview. However, if you selected the dialog before in the inspector, you can still edit it's properties and by setting the visible property from `true` to `false` and back to `true`, you can make the dialog visible again. Eventually, I ended up with a seg fault but I can't reproduce it...

> Note: `adw::MessageDialog` is also affected by this.

## Example

```rust
use gtk::glib::clone;
use gtk::glib::signal::Inhibit;
use gtk::prelude::*;

use std::rc::Rc;

fn main() {
    let application = gtk::Application::builder()
        .application_id("com.github.gtk-rs.examples.dialog")
        .build();

    application.connect_activate(build_ui);
    application.run();
}

fn build_ui(application: &gtk::Application) {
    let button = gtk::Button::builder()
        .label("Open Dialog")
        .halign(gtk::Align::Center)
        .valign(gtk::Align::Center)
        .build();

    let window = Rc::new(
        gtk::ApplicationWindow::builder()
            .application(application)
            .title("Dialog Example")
            .default_width(350)
            .default_height(70)
            .child(&button)
            .visible(true)
            .build(),
    );

    let question_dialog = gtk::MessageDialog::default();
    question_dialog.set_transient_for(Some(&*window));
    question_dialog.set_modal(true);
    question_dialog.add_button("test", gtk::ResponseType::Ok);

    button.connect_clicked(clone!(@strong window =>
        move |_| {
            let question_dialog = question_dialog.clone();
            gtk::glib::MainContext::default().spawn_local(async move {
                let answer = question_dialog.run_future().await;
                dbg!(answer);
                question_dialog.close();
            });
        }
    ));

    window.connect_close_request(move |window| {
        if let Some(application) = window.application() {
            application.remove_window(window);
        }
        Inhibit(false)
    });
}

```

**Comment by AaronErhardt** [comment]
### Update

I was able to reproduce this without `run_future`. It seems like simply showing the dialog for the second time is enough to break the application.

```rust
use gtk::glib::signal::Inhibit;
use gtk::prelude::*;

use std::rc::Rc;

fn main() {
    let application = gtk::Application::builder()
        .application_id("com.github.gtk-rs.examples.dialog")
        .build();

    application.connect_activate(build_ui);
    application.run();
}

fn build_ui(application: &gtk::Application) {
    let button = gtk::Button::builder()
        .label("Open Dialog")
        .halign(gtk::Align::Center)
        .valign(gtk::Align::Center)
        .build();

    let window = Rc::new(
        gtk::ApplicationWindow::builder()
            .application(application)
            .title("Dialog Example")
            .default_width(350)
            .default_height(70)
            .child(&button)
            .visible(true)
            .build(),
    );

    let dialog = gtk::Dialog::default();
    dialog.set_transient_for(Some(&*window));
    dialog.set_modal(true);
    dialog.add_button("test", gtk::ResponseType::Ok);
    dialog.connect_response(|dialog, res| {
        dbg!(res);
        dialog.close();
    });

    button.connect_clicked(move |_| dialog.show());

    window.connect_close_request(move |window| {
        if let Some(application) = window.application() {
            application.remove_window(window);
        }
        Inhibit(false)
    });
}
```

**Comment by AaronErhardt** [comment]
### Update 2

I think I've found the cause: Calling close on a dialog. This seems to leave the dialog in a inconsistent state for some reason. Using `hide` instead seems to work as exepected.

**Comment by sdroege** [comment]
That's expected, yes. Calling close on a window basically destroys it. If you want to re-use it then you need to use `hide()`

**Comment by bilelmoussaoui** [comment]
Maybe we should make the close call take self by value instead of by reference , not gonna solve the problem but at least would somehow make things clearer to the end user

**Comment by AaronErhardt** [comment]
> Maybe we should make the close call take self by value instead of by reference , not gonna solve the problem but at least would somehow make things clearer to the end user.

Yes, I think that would be good. It makes it more obvious that that window isn't supposed to be used afterwards. Also, the docs should be more clear I think. At least for me, the word "closing" isn't associated with "destroying" the entire widget.

> [From the docs](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/prelude/trait.GtkWindowExt.html#tymethod.close): Requests that the window is closed. This is similar to what happens when a window manager close button is clicked. This function can be used with close buttons in custom titlebars.

**Comment by AaronErhardt** [comment]
Also, I've just found another annoying detail. If the user closes the dialog with the close button, this is the same as calling close (which kinda makes sense but also breaks the dialog when shown again). However, `adw::MessageDialog` always closes the dialog window, even when you clicked a regular response. So solve this, you need to register a "close_request" handler to prevent the closing. It's just very unexpected that this happens when you click regular responses...

**Comment by sdroege** [comment]
This should probably be reported directly to adwaita and GTK

**Comment by AaronErhardt** [comment]
I agree. But what should be reported? Technically, this is something I stumbled over, but not really unexpected behavior if you have a closer look. What would have helped me a lot with the search for errors would be that presenting a closed window should throw a runtime warning or error.

So I guess if we implement a check for present in GTK that would also apply to adwaita. What do you think?

**Comment by sdroege** [comment]
Calling show on a closed/destroyed widget could probably give a `g_warning()`, would that work?

**Comment by AaronErhardt** [comment]
Sounds good, I'm closing this then and try to report or fix this upstream.

**Comment by bilelmoussaoui** [comment]
I would still keep this open until we make it take Self instead of &Self
