### ISSUE TITLE
[FEATURE REQUEST] Add gnome_{version} feature flags

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk4-rs#1156]
### The problem

The gtk4 crate re-exports quite a few dependencies. Yet at the same time, these dependencies have quite a few items behind a certain feature flag. This makes the re-export less useful because to activate these feature flags, you need to specify the re-exports like regular dependencies in the README.md.

One particularly common situation are version requirements. You might need to enable features from GTK 4.8, glib 2.70 and also gdk-pixbuf 2.36. This means that you need to re-define two crates as dependencies that were already re-exports.

For example, [Amberol](https://gitlab.gnome.org/World/amberol/-/blob/main/Cargo.toml) is affected by this.

### The solution

Developers usually target a certain version of the entire GNOME stack, which means a certain baseline of dependencies. For example, for GNOME 43 that should be GTK 4.8, libadwaita 1.2, glib 2.74 and so on. Anyone targeting Ubuntu 22.10, Fedora 37 or the Flatpak GNOME runtime in version 43 should have this baseline of dependencies. 

So naturally, it would make sense to also offer this as a feature flag for gtk4-rs. For example, enabling the "gnome_43" feature flag could take care enabling the correct feature flags.

**Comment by sdroege** [comment]
Sounds like a good idea. Do you want to create a PR?

**Comment by AaronErhardt** [comment]
Sure, but I wonder whether there's a good source of information for those version numbers. Of course I could go through each library and check which version is installed on my Fedora 37 machine or look up git tags, but that seems a bit tedious. For example, the [GNOME 43 changelog for developers](https://release.gnome.org/43/developers/index.html) only mentions versions for GTK, GLib and libadwaita but not cairo, gdk-pixbuf, pango etc.

Maybe someone has a good idea? :)

**Comment by sdroege** [comment]
@alatiera maybe knows?

**Comment by alatiera** [comment]
You can find a summary of versions [here](https://gitlab.gnome.org/GNOME/releng/-/blob/master/tools/versions-stable) however the files are not versions the versions keep roatating depending on their status `stable`, `oldstable` etc.

The canonical way to look for everything, since the version file above might be missing some projects, would be to look for the element/bst file in gnome-build-meta repo, desired stable branch, and the ref it uses.

here's the glib one for example:

https://gitlab.gnome.org/GNOME/gnome-build-meta/-/blob/gnome-43/elements/sdk/glib.bst#L5

**Comment by alatiera** [comment]
Another way to find the versions and all in an easier way is to inspect the manifest in the runtime, but again it might be missing projects that are no shipped in the Sdk, although unlikely for this case, so best to use the gnome-build-meta repo as the source of truth when in doubt.

```
flatpak run --command=cat org.gnome.Sdk//43 -- /usr/manifest.json
```
