### ISSUE TITLE
Using custom widgets in ui templates

### ISSUE THREAD

**Issue by Malmz** [gtk-rs/gtk4-rs#116]
Trying to use a subclassed widget in another widget's ui template gives a runtime error:

Gtk-CRITICAL **: 18:40:50.481: Error building template class 'ParentCustomWidget' for an instance of type 'ParentCustomWidget': .:0:0 Invalid object type 'ChildCustomWidget'

[This](https://stackoverflow.com/questions/24235937/custom-gtk-widget-with-template-ui) stackoverflow thread seems to have some info.

**Comment by Malmz** [comment]
Thanks! Calling `ChildCustomWidget::static_type()` in `ParentCustomWidget::class_init()` before binding the template works!

**Comment by bilelmoussaoui** [comment]
Nice! Feel free to submit an example with such use case :)

**Comment by piegamesde** [comment]
I think the issue still exists when the child class is not directly referenced as `template_child`. At least I ran into this error again today, and I think this is the cause.
