### ISSUE TITLE
[HELP] Question about Picture and Window size adjustment

### ISSUE THREAD

**Issue by Joezeo** [gtk-rs/gtk4-rs#1167]
Hi there. I created a Picture through Pixbuf. I want the size of the Picture to be fixed, so I set the Picture `set_can_shrink (false)`: It works fine when I increase the window size. 

But I want the window to display only part of the Picture when the window size is smaller than the Picture size,  but the problem is that I can't reduce the window size at all.

Is there any way to achieve this?

ps: I read the document `Viewport`, which seems can solve my problem, but I don't know how to use it, it seems not working properly.

there was my code:
```rust
fn main() {
    let app = Application::builder()
        .application_id("com.test.picture")
        .build();

    app.connect_activate(build_ui);

    app.run();
}

fn build_ui(app: &Application) {
    let pixbuf = Pixbuf::from_file("D:/test.png").unwrap();

    let picture = Picture::for_pixbuf(&pixbuf);
    picture.set_valign(Align::Start);
    picture.set_halign(Align::Start);
    picture.set_can_shrink(false);

    let viewport = Viewport::builder().child(&picture).build();

    let window = ApplicationWindow::builder()
        .application(app)
        .title("Picture")
        .child(&viewport)
        .build();

    window.present();
}
```

**Comment by bilelmoussaoui** [comment]
You should use ScrolledWindow not Viewport.
