### ISSUE TITLE
Add composite template callbacks examples

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#1168]
Things that comes to my mind that should be covered

- A dialog's response signal (as the response type is expected to be an int32 and not a ResponseType)
- Some `signal::notify`

**Comment by jobale** [comment]
I wrote this example jobale/gtk4-rs@f12dfd3fa15c33b9c2cad442e223e49aa1fc1b52 . It shows:

- Composite template
- custom property "counter" and its binding with another property
- signal "notify::counter"
- dialog's response signal handling
- callbacks

Is it a correct answer to this issue and should I make a PR of it or not?

**Comment by bilelmoussaoui** [comment]
Yes please, thanks a lot!
