### ISSUE TITLE
[FEATURE REQUEST] Add information regarding the interaction of modal ApplicationWindow's and the Headerbar widget

### ISSUE THREAD

**Issue by StefanMathis** [gtk-rs/gtk4-rs#1169]
Today I encountered the following problem: When building an `ApplicationWindow` the following way, the `minimize` and `maximize` buttons didn't show up:

```rust
let header_bar = gtk::HeaderBar::builder()
    .decoration_layout(":minimize,maximize,close")
    .build();

let window = gtk::ApplicationWindow::builder()
    .title("Slot pole-pair combinations")
    .titlebar(&header_bar)
    .decorated(true)
    .modal(true) // <=== This automatically prevents minimize and maximize buttons to show up!
    .application(&app)
    .build();
```

I spent the better half of the day on this problem until I found that setting the window as modal prevents the buttons. This is not documented anywhere, I just found a comment somewhere in the GTK documentation (don't remember where) which stated that headerbar widgets may or may not be shown depending on window properties (but without any details).

I therefore suggest to add a sentence to both `set_decoration_layout` (https://gtk-rs.org/gtk4-rs/stable/latest/docs/src/gtk4/auto/header_bar.rs.html#210) and the `set_modal` method (https://gtk-rs.org/gtk4-rs/stable/latest/docs/src/gtk4/auto/window.rs.html#1446) where this interaction is explicitly stated. I am happy to submit a corresponding PR if you agree with me.

**Comment by bilelmoussaoui** [comment]
Hi, 
thank you for the detailed issue, the rust documentation is generated from the C documentation. So the changes has to be done in the upstream source code.  See https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkheaderbar.c#L770 & https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkwindow.c#L2422, please submit a PR/issue there.

**Comment by StefanMathis** [comment]
I submitted an upstream issue, see https://gitlab.gnome.org/GNOME/gtk/-/issues/5324. Thanks for looking up the corresponding lines in the source code.
