### ISSUE TITLE
Improve bindings for gtk::Widget::dispose_template

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk4-rs#1189]
Currently one has to call
```rust
       fn dispose(&self) {
            self.obj().dispose_template(Self::Type::static_type());
        }
```
but this could be turn into
```rust
        fn dispose(&self) {
            self.dispose_template();
        }
```

**Comment by bilelmoussaoui** [comment]
The function should be moved to `InitializingWidgetExt` and `init_template` / `template_child` dropped from `WidgetExt` as they don't make sense for random widgets.

**Comment by bilelmoussaoui** [comment]
Similarly, `WidgetClassSubclassExt::bind_template_child` should be dropped
