### ISSUE TITLE
[HELP] GNU toolchain in Windows OS also need to install pkg-config?

### ISSUE THREAD

**Issue by seyoatda** [gtk-rs/gtk4-rs#1197]
Help needed for the installation

Followed the construction from here: https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html
I'm using GNU toolchain so I perform following actions: 
1. install MSYS2
2. install GTK4 in MSYS2 windows
3. update environment path
4. set up gnu toolchain for rust

I try to run a hello world program, and this error occurs:
```
The following warnings were emitted during compilation:
warning: Could not run `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.66"`
error: failed to run custom build command for `glib-sys v0.16.3`
Caused by:
  process didn't exit successfully: `D:\projects\rust\my-gtk-app\target\debug\build\glib-sys-1598cafa53f87858\build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-pc-windows-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_pc_windows_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=Could not run `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.66"`
  The pkg-config command could not be found.
  Most likely, you need to install a pkg-config package for your OS.
  If you've already installed it, ensure the pkg-config command is one of the
  directories in the PATH environment variable.
  If you did not expect this build to link to a pre-installed system library,
  then check documentation of the glib-sys crate for an option to
  build the library from source, or disable features or dependencies
  that require pkg-config.
```
it says I need to install a pkg-config package, which is not mentioned in the tutorial.

**Comment by Hofer-Julian** [comment]
> it says I need to install a pkg-config package, which is not mentioned in the tutorial.

It is among the packages to install: https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html#install-gtk-4

`mingw-w64-x86_64-pkgconf` should also act as `pkg-config`

**Comment by seyoatda** [comment]
> > it says I need to install a pkg-config package, which is not mentioned in the tutorial.
> 
> It is among the packages to install: https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html#install-gtk-4
> 
> `mingw-w64-x86_64-pkgconf` should also act as `pkg-config`

Sorry, I wasn't aware that the package is installed from the command, so the problem is the glib version?

**Comment by Hofer-Julian** [comment]
I guess that the msys binaries are not in your PATH. What happens if you try to run pkg-config?

**Comment by seyoatda** [comment]
the path variable was set. I'm trying to use the MSVC toolchain to see if the program can run successfully😂

![image](https://user-images.githubusercontent.com/24985838/205203477-fe65b18e-9993-484c-96d0-f09e16a0db10.png)

**Comment by nazar-pc** [comment]
> It is among the packages to install

It is not under "Build GTK 4 with gvsbuild and MSVC (recommended)"

**Comment by Hofer-Julian** [comment]
I think we can close this issue by now.
