### ISSUE TITLE
[FEATURE REQUEST] Update MSVC installation docs to recommend gvsbuild

### ISSUE THREAD

**Issue by mitchhentges** [gtk-rs/gtk4-rs#1199]
I think that `gvsbuild` is an easier way for developers to build GTK4 on Windows than the current recommended steps.

* The upstream GTK docs [recommend gvsbuild for building with MSVC](https://www.gtk.org/docs/installations/windows/).
* It would allow significantly simplifying the `installation_windows` and `libadwaita#windows` (only `gvsbuild build libadwaita`, nice!) sections.
* (👎) [There are risks with icons not working](https://gitlab.gnome.org/GNOME/gtk/-/issues/5303)
* ~(👎) [there is currently a compatibility issue with the most-recent `gvsbuild` release and `gtk4-rs`](https://github.com/gtk-rs/gtk4-rs/issues/1198)~

I will happily make the PR to migrate the docs for this, if you think that the tradeoffs are worth making this change.

**Comment by bilelmoussaoui** [comment]
I would add a documentation for the other option, not drop the current one.

**Comment by Hofer-Julian** [comment]
> I would add a documentation for the other option, not drop the current one.

Why should we keep both?
Especially if it is the recommended method.

**Comment by Hofer-Julian** [comment]
Either way @mitchhentges:
If you open a PR, please make sure that your instructions work locally on your machine and are reproducible :)

**Comment by wroyca** [comment]
> > I would add a documentation for the other option, not drop the current one.
> 
> Why should we keep both? Especially if it is the recommended method.

@Hofer-Julian It's crucial to have clear, reliable build instructions that don't rely on automated toolkits that may not always be reliable. This is especially important for complex systems like the GTK stack, where each component is modularized. Without reliable build instructions, it can be frustrating and time-consuming to collect and compile information from various sources in order to determine the correct steps to follow. Clear, step-by-step instructions can help streamline the build process and provide a consistent reference point for everyone to follow, which can help ensure that everyone is on the same page. \:)

**Comment by bilelmoussaoui** [comment]
> > I would add a documentation for the other option, not drop the current one.
> 
> Why should we keep both? Especially if it is the recommended method.

It is the recommended method when it works compared to building everything manually yourself. So I would rather keep the current steps as a "fallback instructions" instead of dropping them and hoping windows users would find out how to fix gvsbuild in case there is a regression.

**Comment by Hofer-Julian** [comment]
> So I would rather keep the current steps as a "fallback instructions" instead of dropping them and hoping windows users would find out how to fix gvsbuild in case there is a regression.

Fair point.

**Comment by pieterdd** [comment]
To be fair, the manual build instructions don't seem to be completely reliable either (or I'm not great at reading). I had to manually find `libsass.dll` somewhere and drop it into `gtk\builddir\subprojects\sassc` to make things work. I'm still figuring out some other impediments such as "error: could not find system library 'gio-2.0' required by the 'gio-sys' crate" through Google as I'm inexperienced with Rust.

`gvsbuild` had its own set of issues here but I'm happy to use whichever of the two I can figure out faster.

**Comment by wroyca** [comment]
> To be fair, the manual build instructions don't seem to be completely reliable either (or I'm not great at reading). I had to manually find `libsass.dll` somewhere and drop it into `gtk\builddir\subprojects\sassc` to make things work. I'm still figuring out some other impediments such as "LINK : fatal error LNK1181: cannot open input file 'cairo-gobject.lib'" through Google.
> 
> `gvsbuild` had its own set of issues here but I'm happy to use whichever of the two I can figure out faster.

Hi @pieterdd, the manual instructions build GTK from master, which is a very fast and constantly changing environment. This can occasionally lead to unexpected problems that were not detected by CI - however, I tried to build a fresh install to see if anything was inadvertently broken and everything is OK on my end - so we will need more information from you to help

**Comment by mitchhentges** [comment]
> gvsbuild had its own set of issues here but I'm happy to use whichever of the two I can figure out faster.

FWIW, I've been burnt twice on stable `gvsbuild` releases not being able to build `gtk4` - there's an issue [affecting the current release](https://github.com/wingtk/gvsbuild/issues/811) ([heh, you found it already](https://github.com/wingtk/gvsbuild/issues/813)). Fortunately, with `gvsbuild`, _generally_ once you find a good version (and they should keep getting better as the project matures!), then it seems pretty solid :)

**Comment by pieterdd** [comment]
@wroyca Thanks for the checklist. I tried to start fresh again. Alas, I'm still getting a "cannot open input file 'cairo-gobject.lib" error. I'd provide more info but I also want to keep this thread on topic. Is https://discourse.gnome.org/ the best place to go with questions about this, or do I open a separate GitHub issue?

**Comment by wroyca** [comment]
> @wroyca Thanks for the checklist. I tried to start fresh again. Alas, I'm still getting a "cannot open input file 'cairo-gobject.lib" error. I'd provide more info but I also want to keep this thread on topic. Is https://discourse.gnome.org/ the best place to go with questions about this, or do I open a separate GitHub issue?

I believe it's best to open a separate issue so we can track it down - and it's directly related to the book, so not explicitly out of context for gtk-rs

**Comment by pieterdd** [comment]
Okay, I've opened https://github.com/gtk-rs/gtk4-rs/issues/1257 for this.
