### ISSUE TITLE
[HELP] Custom signals that don't send any values

### ISSUE THREAD

**Issue by myu-jiku** [gtk-rs/gtk4-rs#1208]
Hi, I want to create a custom signal that can be use like the button clicked signal [here](https://github.com/gtk-rs/gtk4-rs/blob/3e2b633394fcddb50857016b8def1ac47419e212/book/listings/g_object_signals/1/main.rs#L33), so a signal that does not send any additional values.

I defined the signal like this:
```rs
fn signals() -> &'static [Signal] {
    static SIGNALS: Lazy<Vec<Signal>> = Lazy::new(|| {
        vec![Signal::builder("signal-name").build()]
    });
    return SIGNALS.as_ref();
}
```

And tried to connect it like this:
```rs
custom_widget.connect_closure(
    "signal-name",
    false,
    glib::closure_local!(move |_widget| {
        println!("did something");
    }),
);
```

When trying to compile I got the following error:
```
the trait `FromValue<'_>` is not implemented for `()`
```

What am I doing wrong?

**Comment by sdroege** [comment]
> ```rust
>     glib::closure_local!(move |_widget| {
> ```

You have to give the arguments types if they're not inferred from the closure body. I.e. in your case something like

```rust
    glib::closure_local!(move |_widget: &gtk::Widget| {
```
