### ISSUE TITLE
[FEATURE REQUEST] Improve usability of `.css_classes` in builders

### ISSUE THREAD

**Issue by hwittenborn** [gtk-rs/gtk4-rs#1224]
Currently in builders (such as [`LabelBuilder`](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/builders/struct.LabelBuilder.html#method.css_classes)), `css_classes` requires a `Vec<String>`, which is quite annoying to use, with snippets such as these littered throughout my codebase (this isn't an actual example, but it shows the point):

```rust
...
.css_classes(vec!["background".to_string(), "error".to_string()])
```

The fact that I have to run `.to_string()` really makes it messier. It would be nicer if I could just pass in `&str` references so I could do this:

```rust
...
.css_classes(vec!["background", "error")])
```

It probably wouldn't be best to just break things though - maybe a `Vec<impl ToString>` or `Vec<impl AsRef<str>>` could be passed instead? I just don't really want to have to be typing `.to_string()` everywhere, and I don't really see any reason why it'd have to stay as such.

**Comment by hwittenborn** [comment]
On that note, it might be nice to even just accept `&[impl AsRef<str>]` or something like that so it's not forced to be a vector either.

**Comment by bilelmoussaoui** [comment]
See https://github.com/gtk-rs/gir/issues/1122

**Comment by bilelmoussaoui** [comment]
Also please check #1110

**Comment by hwittenborn** [comment]
Is this just waiting for someone to submit a PR then @bilelmoussaoui? I'd be more than glad to look into it if so

**Comment by bilelmoussaoui** [comment]
I would wait until https://github.com/gtk-rs/gir/pull/1417 lands first
