### ISSUE TITLE
[HELP]How to use svg filter through filter:url('#xx') in css

### ISSUE THREAD

**Issue by Grieey** [gtk-rs/gtk4-rs#1228]
```html
    <svg id="svg" xmlns="http://www.w3.org/2000/svg" version="1.1">
      <defs>
        <filter id="gooey">
          <feGaussianBlur in="SourceGraphic" stdDeviation="6" result="blur" />
          <feColorMatrix in="blur" type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0 0 0 0 19 -9" result="highContrastGraphic"/>
          <feComposite in="SourceGraphic" in2="highContrastGraphic" operator="atop"/>
        </filter>
      </defs>
    </svg>
```
I can define the above svg filter in Html, and then use filter: url('#id') in CSS. How can I achieve the same effect in gtk?

**Comment by bilelmoussaoui** [comment]
You can't I believe. GTK doesn't implement all the CSS standard implemented by web browsers, only a subset of it.

**Comment by bilelmoussaoui** [comment]
Please use discourse.gnome.org/ for generic GTK questions & https://github.com/gtk-rs/gtk4-rs/discussions for questions related to the bindings in the future
