### ISSUE TITLE
Split off big generic functions from traits into non-generic functions

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk4-rs#1241]
See also https://github.com/gtk-rs/gtk-rs-core/issues/887

**Comment by bilelmoussaoui** [comment]
I have already done such cleanup a long time ago, only generic functions are in traits nowadays. I did a quick checkup this morning and found nothing to be cleaned here. Unless I misunderstood the purpose of this issue

**Comment by sdroege** [comment]
Something like `ObjectExt::set_property()` is huge and a generic function (it's on a trait after all), so there would be a copy of that for every single type this is called on.

If this is made a very small generic function in the trait that just calls a big non-generic function (taking `Object` instead of `impl IsA<Object>`, etc) then this problem goes away.

**Comment by bilelmoussaoui** [comment]
Aha I see, then we have nothing like this here in gtk4-rs itself.
