### ISSUE TITLE
Store `PhantomData` in stashes of manual `ToGlibPtr` impls if only a lifetime is needed

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk4-rs#1248]
https://github.com/gtk-rs/gtk-rs-core/commit/d373a78b01957b0d3430f3eb8b19b8459b5029ef

**Comment by bilelmoussaoui** [comment]
Just did a check and we only use PhantomData when a lifetime is needed.

**Comment by sdroege** [comment]
Ah did I update that already? Apparently: https://github.com/gtk-rs/gtk4-rs/commit/6863c9c3ec4eb8bb4eaee1e76abdfa33fb38f4a0
