### ISSUE TITLE
[FEATURE REQUEST] Replace all C code with Rust code

### ISSUE THREAD

**Issue by amab8901** [gtk-rs/gtk4-rs#1260]
Would be nice if this crate was 100% Rust without any C-dependencies whatsoever. I think this would allow the crate to more easily take advantage of Rust's language features to its full advantage with higher memory safety and lower risk of bugs. Perhaps may be easier for future Rust contributors to work on the crate if they don't have to worry about FFI:s.

**Comment by sdroege** [comment]
The whole purpose of this crate is to provide a safe Rust API on top of the GTK C library. If you're looking for a Rust-native UI toolkit, there are many (more or less incomplete) options at this point.

While it would be nice to have at least parts of GTK in Rust, the GTK maintainers are not very open to that idea.

**Comment by bilelmoussaoui** [comment]
That is definitely out of scope of the current project.
