### ISSUE TITLE
Weird sentence in the Memory Managment section

### ISSUE THREAD

**Issue by delight-aug** [gtk-rs/gtk4-rs#1276]
**Bug description**

In GObject Concepts -> Memory Managment -> explanation of weak references:
> Every time the button is clicked, `glib::clone` tries to upgrade the weak reference. If we now for example click on one button and the other button is not there anymore, `upgrade` will return `None`.

At the end on the sentence, "upgrade" is referred to as a function (by putting it in a code block), yet it isn't defined or shown anywhere. What it actually means, is that the process of upgrading will return `None`.

**Comment by Hofer-Julian** [comment]
The best I can do is to show the expanded code of the `clone!` macro.
I have to think a bit more about this.

**Comment by delight-aug** [comment]
Maybe it can be just reworded to something like:
> Every time the button is clicked, `glib::clone` tries to upgrade the weak reference. If we now for example click on one button and the other button is not there anymore, the callback will be skipped.

**Comment by Hofer-Julian** [comment]
@delight-aug sounds good!
Do you want to open a PR for that?
