### ISSUE TITLE
[HELP] Trait bound FromGlibPtrNone<*mut _> is not satisfied

### ISSUE THREAD

**Issue by uglyluigi** [gtk-rs/gtk4-rs#1286]
Hi there,

I am trying to write a custom layout manager that will allow me to set a maximum width for its children. Here's all the code I have so far:

```#[gtk::glib::object_subclass]
impl ObjectSubclass for MaxWidthBox {
	const NAME: &'static str = "MaxWidthBox";
	type Type = MaxWidthBox;
	type ParentType = gtk::Box;
}

impl ObjectImpl for MaxWidthBox {}

impl WidgetImpl for MaxWidthBox {}

impl LayoutManagerImpl for MaxWidthBox {}

impl BoxImpl for MaxWidthBox {}
```

I've found a little bit of documentation [here](https://gtk-rs.org/gtk4-rs/stable/latest/book/g_object_subclassing.html) but even this example yields similar compiler diagnostics:

`the trait bound MaxWidthBox: FromGlibPtrNone<*mut _> is not satisfied`

and

`the trait bound ObjectRef: From<MaxWidthBox> is not satisfied`

Obviously there is most likely a trait impl I am missing, but it's not exactly clear which. Does anyone know what other trait impls I need to provide for this to work properly? Thanks in advance.

**Comment by bilelmoussaoui** [comment]
```diff
-	type Type = MaxWidthBox;
+	type Type = super::MaxWidthBox;
```

**Comment by uglyluigi** [comment]
> ```diff
> -	type Type = MaxWidthBox;
> +	type Type = super::MaxWidthBox;
> ```

```
#[derive(Default)]
pub struct MaxWidthBox;

use gtk::glib;

#[gtk::glib::object_subclass]
impl ObjectSubclass for MaxWidthBox {
	const NAME: &'static str = "MaxWidthBox";
	type Type = super::MaxWidthBox;
	type ParentType = gtk::Box;
}

impl ObjectImpl for MaxWidthBox {}

impl WidgetImpl for MaxWidthBox {}

impl LayoutManagerImpl for MaxWidthBox {}

impl BoxImpl for MaxWidthBox {}
```

I did try that to keep it more in line with the documentation, but for some reason rustc can't find super::MaxWidthBox but can find MaxWidthBox:

```
cannot find type `MaxWidthBox` in module `super`
not found in `super`
```

**Comment by sdroege** [comment]
Please provide your whole code, in a (theoretically) compileable form :)

**Comment by uglyluigi** [comment]
> Please provide your whole code, in a (theoretically) compileable form :)

The snipped I included could pretty much be dropped into any gtk-rs project, at least to my understanding of that particular code, since it's just defining a new component. Apologies if I didn't include enough context, but I can offer a solution.

The `super` prefix on the `Type` was just a consequence of how the project was structured in the docs. 

It turns out, these two traits are implemented on your struct when you define your wrapper type with `glib::wrapper!`. So you just need to create your wrapper type as the next step in the doc describes, although it is slightly different for my particular case. Here's the completed code for my case, extending the gtk::Box in gtk-rs 4:

fixed_box.rs
```
#[derive(Default)]
pub struct MaxWidthBox;

use gtk::glib;
use gtk::subclass::prelude::*;
use glib::Object;

#[gtk::glib::object_subclass]
impl ObjectSubclass for MaxWidthBox {
    const NAME: &'static str = "MaxWidthBox";
    type Type = MaxWidthBoxImpl;
    type ParentType = gtk::Box;
}

impl ObjectImpl for MaxWidthBox {}

impl WidgetImpl for MaxWidthBox {}

impl LayoutManagerImpl for MaxWidthBox {}

impl BoxImpl for MaxWidthBox {
    
}

glib::wrapper! {
    pub struct MaxWidthBoxImpl(ObjectSubclass<MaxWidthBox>)
        @extends gtk::Button, gtk::Widget,
        @implements gtk::Accessible, gtk::Actionable, gtk::Buildable, gtk::ConstraintTarget;
}

impl MaxWidthBoxImpl {
    pub fn new() -> Self {
        Object::builder().build()
    }
}
```

This compiles properly and works as expected.

**Comment by sdroege** [comment]
Yes that explains it. I would recommend naming things differently or using the module scheme from the docs though. The wrapper type is not really an "implementation" like you named it. In your naming, `MaxWidthBox` is the private state / private member variables of the class `MaxWidthBoxImpl`. If anything I'd call them `MaxWidthBoxPriv` and `MaxWidthBox`, but personally I prefer the module scheme.
