### ISSUE TITLE
Example `video_player` not using theme decoration & not using `GTK_USE_PORTAL`

### ISSUE THREAD

**Issue by hasezoey** [gtk-rs/gtk4-rs#1299]
I am still new to GTK (or gui in general), but i have noticed that the example `video_player` does not use the correct theme / window decoration, whereas other examples like `clock` use the correct one.

also i have noticed that the `FileChooserNative` in `video_player` does not seem to respect `GTK_USE_PORTAL=1` (firefox seems to respect it, but things like `transmission-remote-gtk` do not)

![clock_example](https://user-images.githubusercontent.com/10911626/218262903-17054d8a-3518-46c9-85d1-97b82c9049a6.png)
![video_player_example](https://user-images.githubusercontent.com/10911626/218262900-ee5a5b18-f3e2-4977-866b-4f38000241d7.png)

Running:
Manjaro 22.0.2
KDE Plasma Wayland 5.26.5

```rust
println!("{}.{}.{}", gtk::major_version(), gtk::minor_version(), gtk::micro_version());
```

prints `4.8.3`

**Comment by bragefuglseth** [comment]
The video player uses the GtkHeaderbar widget, which overrides the titlebar. It isn't possible to put the "open" button it has in the headerbar inside of the KDE titlebar. If you want your apps to always use the system-provided one, you'll have to avoid using the headerbar widget.

**Comment by hasezoey** [comment]
thanks for the explanation, what about the file chooser not using `GTK_USE_PORTAL`?

**Comment by bilelmoussaoui** [comment]
That would probably be caused by the env variable being replaced with something else I believe. Please ask upstream GTK developers

**Comment by alatiera** [comment]
`GTK_USE_PORTAL` was a debug variable, which no longer exists, but even when it wasn't really doing what you were expecting. `FileChooserNative` just calls into the portal implementation of the filechooser, gtk doesn't do much more than that. The issue is likely on your systems configuration.

This issue is kinda a duplicate of https://gitlab.gnome.org/GNOME/gtk/-/issues/5332#note_1592555
