### ISSUE TITLE
Data races reported by TSAN

### ISSUE THREAD

**Issue by parasyte** [gtk-rs/gtk4-rs#1304]
**Bug description**

Running any of the examples on the nightly compiler with thread-sanitizer enabled reports several data races.

```bash
RUSTFLAGS='-Zsanitizer=thread' cargo run -Zbuild-std --target x86_64-unknown-linux-gnu --bin clock
```

**Output**

[Printed when running the `clock` example (external link because it's so long)](https://gist.github.com/parasyte/61272e40ae9b58e0b38c60947b014b8e)

**Additional context**

I am using GTK 4.6 on Ubuntu 22.04 in WSL2 on Windows 11.

But I don't expect this to be limited to WSL or virtualization in general.

**Comment by jf2048** [comment]
I suspect you will see similar things if you do the same thing with a gtk C example using clang.

```sh
git clone https://gitlab.gnome.org/GNOME/gtk.git
cd gtk
CC=clang meson setup build -Db_sanitize=thread -Db_lundef=false
```

And then try to run something from the build/examples folder. For me on Linux it looks like a lot of the same errors. The majority look like gdbus so probably these should be reported upstream to [glib](https://gitlab.gnome.org/GNOME/glib). One of them appears to be in pango or fontconfig though.

**Comment by jf2048** [comment]
Reported one of them at least: https://gitlab.gnome.org/GNOME/glib/-/issues/2920

**Comment by parasyte** [comment]
Thanks for pointing me in the right direction. https://gitlab.gnome.org/GNOME/glib/-/issues/1672 looks like the tracking ticket for these data races.

**Comment by jf2048** [comment]
Closing for now, let's report against that ticket
