### ISSUE TITLE
[HELP] GLAreaImpl Non-mutable reference

### ISSUE THREAD

**Issue by joshuabogue** [gtk-rs/gtk4-rs#1309]
I am working on a custom control that implements the GLAreaImpl trait.  The problem is that the trait only seems to give you a non-mutable reference to self.  So in this case I wanted to be able to set state for both render and resize methods that are part of GLAreaImpl.

Has anyone else run into this?  Is there something I am overlooking or an easy way to get past this? 

```
impl GLAreaImpl for RendererGtk4 {
    fn render(&self, context: &gtk4::gdk::GLContext) -> bool {
        self.renderer.render();
        true
    }

    fn resize(&self, width: i32, height: i32) {
        unsafe { self.renderer.resize(width as u32, height as u32) };
    }
}
```

**Comment by sdroege** [comment]
You have to make use of interior mutability via e.g. a `RefCell` or `Mutex` to get mutable references to your state.
