### ISSUE TITLE
gtk::StyleContext  *_provider functions are marked as deprecated

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#1317]
because gtk::StyleContext is marked as deprecated as well 

![image](https://user-images.githubusercontent.com/7660997/220565162-c3003149-c9fe-48ee-b617-a05a1928da23.png)

**Comment by jf2048** [comment]
Should these just become functions like `gtk::style_context_add_provider_for_display`?
