### ISSUE TITLE
Some Settings Reset on Application Close

### ISSUE THREAD

**Issue by rburmorrison** [gtk-rs/gtk4-rs#1319]
**Bug description**

While following through the [actions section](https://gtk-rs.org/gtk4-rs/stable/latest/book/actions.html) from the gtk4-rs book, I found that the button sensitivity setting wasn't working. To be sure that it wasn't an issue with me following along, I cloned the source down and ran the [official listing's example](https://github.com/gtk-rs/gtk4-rs/tree/0.6.2/book/listings/actions/7) and saw the same issue.

Here's a demonstration of the issue with dconf Editor to visualize the setting changes:

![gtk4rs-settings](https://user-images.githubusercontent.com/12453590/221221620-e186c719-4925-44a9-a03c-4e64fc37860a.gif)

As you can see, the layout settings are retained even though the sensitivity setting is disabled. If I send a kill signal to the application instead of closing through the window itself, the settings are retained, so I imagine it must be linked to something with the window closing.

Out of curiosity if it was a Gtk issue in general or specific to gtk4-rs, I re-implemented the example in GTKMM and got it as close as I was able to, and the settings are retained in GTKMM, so that makes me think it's specific to this crate. 

I am using gtk4-rs v0.6.2, and GTK4 4.8.3. I tested this on Fedora 37, but had the same issue running it on Ubuntu 22.10.

**Backtrace**

N/A

**Comment by rburmorrison** [comment]
I've been looking at this a bit more trying to diagnose the issue, and I think I isolated where the problem is. Commenting the statement out on [book/listings/actions/7/window/mod.rs](https://github.com/gtk-rs/gtk4-rs/blob/0.6/book/listings/actions/7/window/mod.rs#L101) seems to preserve the setting when the window is closed, as the check mark is next to the option in the global menu.

This also seems to only happen with Buttons as far as I can tell. I added a GtkSwitch to the GtkBox and bound a different boolean setting to the "active" property and it was preserved after the window was closed. So something is off specifically about the GtkButton binding, it seems.

I'm not incredibly familiar with the code base, but I've been trying to look through to see if I can find where the issue is occurring. I'll update this issue if I find anything.

**Comment by zekefast** [comment]
I've seen same behaviour in the following environment:
- Rust: `1.68.0`
- gtk4-rs: `0.6.4`
- GTK: `4.10.1`
- Platform: `linux`

**Comment by oleksii-yermolaiev** [comment]
I'm having the same issue. I made it print something when the "sensitive" property changes and it seems to change when the window is closed. Switches do that too. It doesn't happen if the app is terminated with a signal though.

**Comment by linewelder** [comment]
I was having the same issue, so I made a little investigation and found out what most likely was the reason for that:

1.  Buttons/switches/menu items change their sensitivity depending on whether the action they refer to in "action-name" property exists. An interesting detail is that if you bind an action to them before setting as the window's child, they become insensitive no matter what until you do that;
2.  If the button is bound to a settings action, it changes its sensitivity to false when the window gets closed;
3.  At that moment the "sensitive-button" setting gets updated.

I'm not sure if that's intended behaviour or not, but it is definitely a bug on the book's side.

**Comment by Hofer-Julian** [comment]
Thanks everyone for the input. Unfortunately, I couldn't figure out the underlying issue. Which is why I toggle the button frame now instead of its sensitivity.
