### ISSUE TITLE
About the book chapter `Composite Templates` , may I suggest adding a note about  removing `connect_clicked` after using template callback ?

### ISSUE THREAD

**Issue by mashomee** [gtk-rs/gtk4-rs#1329]
In section [Template Callbacks](https://gtk-rs.org/gtk4-rs/stable/latest/book/composite_templates.html#template-callbacks),  after `handle_button_clicked` callback implemented, the `button` is still labeled with"Hello World!" when clicked.  
By checking [4/window/imp.rs](https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/composite_templates/4/window/imp.rs),  I realised we have to
remove the `connect_clicked` call in `impl ObjectImpl for Window {}` for the template callback to take effect. it's confusing then.

So may I suggest adding a note about this removing or about the signal callback
call priority about this

**Comment by Hofer-Julian** [comment]
@mashomee nice find.
Do you want to open a PR to fix this?
The source code of the book is [here](https://github.com/gtk-rs/gtk4-rs/tree/master/book)
