### ISSUE TITLE
Is it worth to mention necessity to add load_css() in main.rs in the book at "Set CSS Name and Use Exported Colors" section of 14th (CSS) chapter?

### ISSUE THREAD

**Issue by zekefast** [gtk-rs/gtk4-rs#1335]
Text body of ["Set CSS Name and Use Exported Colors"](https://gtk-rs.org/gtk4-rs/stable/latest/book/css.html#set-css-name-and-use-exported-colors) section of [14th (CSS) chapter](https://gtk-rs.org/gtk4-rs/stable/latest/book/css.html) does not mention about necessity to add `load_css()` in `main.rs`.

Actual code listing contains necessary [call](https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/todo/3/main.rs#L23) but it seems to me it worth to mention that addition in order to remind the reader about necessity to load CSS styles.

WDYT @Hofer-Julian ?

P.S. It probably worth to mention inclusion of `style.css` into [`resources.gresource.xml`](https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/todo/3/resources/resources.gresource.xml#L7) file.

**Comment by Hofer-Julian** [comment]
> Text body of ["Set CSS Name and Use Exported Colors"](https://gtk-rs.org/gtk4-rs/stable/latest/book/css.html#set-css-name-and-use-exported-colors) section of [14th (CSS) chapter](https://gtk-rs.org/gtk4-rs/stable/latest/book/css.html) does not mention about necessity to add `load_css()` in `main.rs`.
> 
> Actual code listing contains necessary [call](https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/todo/3/main.rs#L23) but it seems to me it worth to mention that addition in order to remind the reader about necessity to load CSS styles.
> 
> WDYT @Hofer-Julian ?

I am not sure I understand the suggestion. That you need to load css in the startup callback is mentioned. Are you suggesting once isn't enough?

**Comment by zekefast** [comment]
> Are you suggesting once isn't enough?

Yeah. Reader probably will use code from chapter 13 or copy it over and at the end of 14th chapter it could forget about CSS loading piece. At least that's what I did :) So, it seems reasonable to put one sentence as a reminder about `load_css()` and `resources.gresource.xml`.

**Comment by Hofer-Julian** [comment]
Fair enough!
Do you want to open a PR? :)

**Comment by zekefast** [comment]
Okay. I'll done with some family staff in the morning and then I'll prepare one closer to my evening (CET).
