### ISSUE TITLE
[HELP] How to use `BookmarkList`? 

### ISSUE THREAD

**Issue by vanillajonathan** [gtk-rs/gtk4-rs#1346]
When I try to compile I get an error saying that [`glib::BookmarkFile`](https://docs.gtk.org/glib/struct.BookmarkFile.html) cannot be found.

I found [`gtk::BookmarkList`](https://docs.gtk.org/gtk4/class.BookmarkList.html) which is suppose to wrap that, but how do I use it?

I want to do something like:
```rust
let bookmarks = gtk::BookmarkList::new(Some("recently-used.xbel"), None);

for bookmark in bookmarks.iter::<I_Dont_Know>() {
    if let Ok(bookmark) = bookmark {
        println!("File: {}, Path: {}", bookmark.filename, bookmark.path);
    }
}
```

But I don't know how to.

**Comment by bilelmoussaoui** [comment]
The list model contains `G_TYPE_FILE_INFO`, which are `gio::FileInfo`

**Comment by vanillajonathan** [comment]
Thanks.

Now I got it to run with:
```rust
let bookmarks = gtk::BookmarkList::new(Some("recently-used.xbel"), None);

for bookmark in bookmarks.iter::<gio::FileInfo>() {
    if let Ok(bookmark) = bookmark {
        println!("File: {}, Path: {}", bookmark.filename, bookmark.path);
    }
}
```

But it was anything but intuitive. I couldn't know what type to use for the generics, I couldn't know that it was `gio::FileInfo`. The API forced me to specify the type, I don't know why, and the documentation didn't help me either.

I think this should somehow be more clear. Either the API or the documentation could be improved, and there could be an example in this repository.

**Comment by bilelmoussaoui** [comment]
The documentation comes from gitlab.gnome.org/gnome/gtk/, so feel free to submit a patch to make the docs clearer.  To me it is clear 
```
The GFileInfos in the list have some attributes in the recent namespace added: recent::private (boolean) and recent:applications (stringv).
```

**Comment by vanillajonathan** [comment]
For me, I think it would be easier if I could just iterate over the `BookmarkList` directly without even have to do  `.iter`.

Example:
```rust
let bookmarks = gtk::BookmarkList::new(Some("recently-used.xbel"), None);

for bookmark in bookmarks {
    //
}
```

If that isn't possible, I would want to call `.iter` without generics.
Example:
```rust
let bookmarks = gtk::BookmarkList::new(Some("recently-used.xbel"), None);

for bookmark in bookmarks.iter() { // now it is gio::FileInfo
    //
}
```

I don't know why `iter()` needs to accept a type.

The documentation could say something like "To iterate over the `BookmarkList` instance create an iterator by calling `.iter::<gio::FileInfo>` then iterate over that."

**Comment by bilelmoussaoui** [comment]
the iter method is added to the `gio::ListModel` interface and so to the `gio::ListModelExtManual` trait which is automatically implemented for  `gtk::BookmarkList`  as it is a `gio::ListModel`. There is no way for it to know what type is expected as the C library doesn't support generics at the type system level.

**Comment by bilelmoussaoui** [comment]
The upstream docs could yes, but that would be in C and won't be useful at all. The whole iter you are using in Rust is specific Rust accommodation and doesn't exists in upstream API.  If you want to add an example to this repo, feel free to send a PR.
