### ISSUE TITLE
libadwaita chapters are missing in the book since awhile.

### ISSUE THREAD

**Issue by zekefast** [gtk-rs/gtk4-rs#1350]
@Hofer-Julian after returning to [the book](https://gtk-rs.org/gtk4-rs/stable/latest/book/) for reference I noticed that `libadwaita` related chapters has disappeared and new inactive chapters in Contents were added.

I wonder is a bug or missing content hasn't been ported to news structure yet?

![Screenshot 2023-03-29 at 13-54-12 Introduction - GUI development with Rust and GTK 4](https://user-images.githubusercontent.com/237734/228527944-2403f2fc-b396-4da1-b42d-abe22744acf6.png)

Also, "Resource" chapter has no content, just a Title.

**Comment by zekefast** [comment]
Previous version of the book is back ATM. It seems like it was already fixed.

**Comment by zekefast** [comment]
@Hofer-Julian Shouldn't we close this issue since the problem has been resolved?

**Comment by Hofer-Julian** [comment]
Sure

**Comment by bilelmoussaoui** [comment]
I think we should stop publishing the book on releases as it usually might require fixes or updates after the release is done.

**Comment by Hofer-Julian** [comment]
> I think we should stop publishing the book on releases as it usually might require fixes or updates after the release is done.

We already stopped doing that on main IIRC. The older point releases sill mess us up though.
