### ISSUE TITLE
Unable to remove EventControllers from Widgets

### ISSUE THREAD

**Issue by blake-wilson** [gtk-rs/gtk4-rs#1353]
I'm newish to both GTK and Rust, so this may be something which is doable already, but I'm unclear as to how.

My issue is that I have an app which assigns `EventController`s to Widgets when they are first created. The Widgets have a lifecycle such that they are deleted and recreated throughout the life of an app.

`EventController`s are assigned to a Widget via the [add_controller](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.add_controller) method which gives up ownership of the `EventController` passed into it.

The problem is, then, that I am unable to maintain a reference to the `EventController` object for the purposes of later removing the controller from the widget via [remove_controller](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/prelude/trait.WidgetExt.html#tymethod.remove_controller).

I'm wondering:
1. Is there already a way to get a reference to the `EventController`?
2. If not, could one be added to facilitate cases like this?

**Comment by blake-wilson** [comment]
It looks like I can get around this using the clone macro
```rust
let click_gesture = GestureClick::new();

clone!(@weak click_gesture => move || {
    self.add_controller(click_gesture);
})();

self.controller_ref = click_gesture;
```

I hadn't previously seen this macro used outside the signal connection context, so it does make me wonder if it's the right way to do this.

**Comment by bilelmoussaoui** [comment]
you could clone the `EventController`  when adding to the widget `some_widget.add_controller(event_controller.clone())` that would bump the ref count so the clone part is cheap. Also, please use github discussions for questions
