### ISSUE TITLE
[HELP] I can't open gtk::FileDialog with given "initial-folder".

### ISSUE THREAD

**Issue by zekefast** [gtk-rs/gtk4-rs#1354]
[`gtk::FileDialog`](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.FileDialog.html) provides a way to set [`initial-folder`](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.FileDialog.html#initial-folder), but it does not work for me no matter what I would do.

Could you please, let me know what I do wrong or it is a bug in `gtk::FileDialog`?

Are there any settings that `gtk::FileDialog` may depend on which turn on that kind of behaviour? I use GNOME `3.38.5`, so I assume I could be missing some settings which normally present for latest GNOME versions.

I'm not very comfortable with C, so I haven't tried to rebuild same example in C and check whether it is a bug in GTK or in gtk4-rs bindings for Rust.

Thank you in advance for any help!

P.S.: [`initial-file`](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.FileDialog.html#initial-file) and [`initial-name`](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.FileDialog.html#initial-name) does not work for me as well.

# Steps To Reproduce
```sh
cargo new file-dialog
cargo add gtk4 --rename gtk --features v4_10
cd file-dialog
cat <<'EOF' > src/main.rs
use gtk::{
    self,
    prelude::*,
    Application,
    ApplicationWindow,
    FileDialog,
    gio::{
        self,
        prelude::*,
        Cancellable,
    },
    glib::{
        self,
        prelude::*,
        clone,
    }
};

const APP_ID: &str = "info.zekefast.FileDialogTest";

fn main() -> glib::ExitCode {
    let app = Application::builder()
        .application_id(APP_ID)
        .build();

    app.connect_activate(build_ui);

    app.run()
}

fn build_ui(app: &Application) {
    let opened_dir = gio::File::for_path("./");

    let file_dialog = FileDialog::builder()
        .title("Open File")
        .modal(true)
        .initial_folder(&opened_dir) // THIS IS THE PART THAT DOES NOT WORK
        .build();

    let window = ApplicationWindow::builder()
        .application(app)
        .title(APP_ID)
        .build();

    file_dialog.open(Some(&window), Cancellable::NONE, clone!(@weak window => move |result| {
        if let Ok(Some(pathbuf)) = result.as_ref().map(|file| file.path()) {
            println!("{}", pathbuf.display());
        } else {
            eprintln!("{:?}", result);
        }
    }));

    window.present();
}
EOF
```

Once again source of `src/main.rs` with Rust syntax highlighted:

```rust
use gtk::{
    self,
    prelude::*,
    Application,
    ApplicationWindow,
    FileDialog,
    gio::{
        self,
        prelude::*,
        Cancellable,
    },
    glib::{
        self,
        prelude::*,
        clone,
    }
};

const APP_ID: &str = "info.zekefast.FileDialogTest";

fn main() -> glib::ExitCode {
    let app = Application::builder()
        .application_id(APP_ID)
        .build();

    app.connect_activate(build_ui);

    app.run()
}

fn build_ui(app: &Application) {
    let opened_dir = gio::File::for_path("./");

    let file_dialog = FileDialog::builder()
        .title("Open File")
        .modal(true)
        .initial_folder(&opened_dir) // THIS IS THE PART THAT DOES NOT WORK
        .build();

    let window = ApplicationWindow::builder()
        .application(app)
        .title(APP_ID)
        .build();

    file_dialog.open(Some(&window), Cancellable::NONE, clone!(@weak window => move |result| {
        if let Ok(Some(pathbuf)) = result.as_ref().map(|file| file.path()) {
            println!("{}", pathbuf.display());
        } else {
            eprintln!("{:?}", result);
        }
    }));

    window.present();
}
```

# Expected Behaviour

File dialog  opens given directory `./` as a current directory.

# Actual Behaviour

File dialog always opens "Recent Files".

# Environment
- Rust: `rustc 1.68.2 (9eb3afe9e 2023-03-27)`
- `gtk4` crate: `0.6.4`
- GTK: `4.10.0`
- GNOME: `3.38.5`
- OS: `Debian GNU/Linux 11 (bullseye)`

# Notes on setup
- GTK4 was compiled from sources and was installed in parallel with system-provided version of GTK3. I let `cargo` know about it with the following flags:

  ```sh
  #!/usr/bin/env bash

  export LD_LIBRARY_PATH="/opt/gtk/lib/x86_64-linux-gnu:/opt/adwaita/lib/x86_64-linux-gnu"
  export CPPFLAGS="-I/opt/gtk/include -I/opt/adwaita/include"
  export LDFLAGS="-L/opt/gtk/lib/x86_64-linux-gnu -L/opt/adwaita/lib/x86_64-linux-gnu"
  export PKG_CONFIG_PATH="/opt/gtk/lib/x86_64-linux-gnu/pkgconfig/:/opt/adwaita/lib/x86_64-linux-gnu/pkgconfig/"
  ```

**Comment by bilelmoussaoui** [comment]
Sounds very much like an upstream issue, the bindings don't do anything special here.

**Comment by zekefast** [comment]
@bilelmoussaoui Should I report it somewhere else or it will be automatically recreated based on assigned label?

**Comment by bilelmoussaoui** [comment]
Please open the issue here gitlab.gnome.org/gnome/gtk/
