### ISSUE TITLE
Possible to create gdk::TextureDownloader in different thread

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk4-rs#1357]
I tried the following code

```rust
        gio::spawn_blocking(move || {
            let mut downloader = gdk::TextureDownloader::new(&texture);
            downloader.set_format(gdk::MemoryFormat::R8g8b8a8);
            let (bytes, stride) = downloader.download_bytes();
```

And got

> Gdk-WARNING **: 17:34:12.619: gdk_gl_context_make_current() failed

So I guess `gdk::TextureDownloader::new` should panic if it's not happening in the main thread?

**Comment by sophie-h** [comment]
Oh, okay, then feel free to close when it is out of scope.

**Comment by sdroege** [comment]
It's still a bug that should be fixed somehow :)
