### ISSUE TITLE
ApplicationWindowBuilder doesn't satisfy ApplicationExt and IsA<Application>

### ISSUE THREAD

**Issue by erikbgithub** [gtk-rs/gtk4-rs#1364]
**Bug description**

I'm trying to run [this "Hello World" example](https://crates.io/crates/gtk4) and run into bounds not satisfied examples from inside the library.

**Backtrace**

```
$ cargo run
   Compiling gtk-app v0.1.0 (/home/erik/coding/rustapp/gtk-app)
error[E0599]: the method `application_id` exists for struct `ApplicationWindowBuilder`, but its trait bounds were not satisfied
  --> src/main.rs:12:14
   |
12 |             .application_id(app)
   |              ^^^^^^^^^^^^^^
   |
  ::: /home/erik/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.6.4/src/auto/application_window.rs:59:1
   |
59 | pub struct ApplicationWindowBuilder {
   | -----------------------------------
   | |
   | doesn't satisfy `_: ApplicationExt`
   | doesn't satisfy `_: IsA<Application>`
   |
   = note: the following trait bounds were not satisfied:
           `ApplicationWindowBuilder: IsA<gtk4::gio::Application>`
           which is required by `ApplicationWindowBuilder: gtk4::prelude::ApplicationExt`
```

**Environment**

```
$ rustc --version
rustc 1.68.2 (9eb3afe9e 2023-03-27) (Fedora 1.68.2-1.fc38)

$ cat Cargo.toml 
[package]
name = "gtk-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.17.5"
gtk = { version = "0.6.4", package = "gtk4", features = ["v4_8"] }
```

**Comment by bilelmoussaoui** [comment]
The application_id must be a string, not an application object.

**Comment by erikbgithub** [comment]
@bilelmoussaoui I think you might have closed this without updating your documentation. Happy to help. I'm not sharing my homework here but following your tutorial. :D

**Comment by erikbgithub** [comment]
And the application_id IS a string. It's `"org.example.HelloWorld"`.

**Comment by bilelmoussaoui** [comment]
Please paste your code.

**Comment by erikbgithub** [comment]
```rust
use gtk4 as gtk;
use gtk::prelude::*;
use gtk::{Application, ApplicationWindow};

fn main() -> glib::ExitCode {
    let app = Application::builder()
        .application_id("org.example.HelloWorld")
        .build();

    app.connect_activate(|app| {
        // We create the main window.
        let window = ApplicationWindow::builder()
            .application(app)
            .default_width(320)
            .default_height(200)
            .title("Hello, World!")
            .build();

        // Show the window.
        window.show();
    });

    app.run()
}
```

**Comment by bilelmoussaoui** [comment]
> ```rust
> use gtk4 as gtk;
> use gtk::prelude::*;
> use gtk::{Application, ApplicationWindow};
> 
> fn main() -> glib::ExitCode {
>     let app = Application::builder()
>         .application_id("org.example.HelloWorld")
>         .build();
> 
>     app.connect_activate(|app| {
>         // We create the main window.
>         let window = ApplicationWindow::builder()
>             .application(app)
>             .default_width(320)
>             .default_height(200)
>             .title("Hello, World!")
>             .build();
> 
>         // Show the window.
>         window.show();
>     });
> 
>     app.run()
> }
> ```

With the changes on this commit https://github.com/gtk-rs/gtk4-rs/commit/ec6e7b06e58b518c462f942a0d1a205860938291, the example works fine locally. Would you mind pasting your Cargo.toml as well?
