### ISSUE TITLE
Todo example does not have round corners when run inside sway

### ISSUE THREAD

**Issue by ferdinandschober** [gtk-rs/gtk4-rs#1365]
Running the todo list example from the book results in a window with square corners, when using sway:

![image](https://user-images.githubusercontent.com/40996949/230774676-dc24572b-d016-45c4-a9eb-510147e68ad2.png)

Command to reproduce:
```sh
cd book/listings
cargo xtask install
cargo run --bin todo_8
```

**Comment by ferdinandschober** [comment]
Update: Forcing csd through sway config fixes the corners (they appear round then). I find this weird, becaue I always thought that gtk does not support server side decorations.

**Comment by bilelmoussaoui** [comment]
Definitely not a bindings issue.
