### ISSUE TITLE
[HELP] Unable to get TextView wrapping to have the wanted behaviour.

### ISSUE THREAD

**Issue by Feohr** [gtk-rs/gtk4-rs#1373]
I have a TextView widget inside a ScrolledWindow. I wanted to wrap word inside the text view so I set the wrap mode to "word-char" which works as expected except one thing. The text view does not recognise tabs and extends until I enter a word. The word then wraps around but the tab remains the same. As such when I move the cursor back, the end of next line is far along the right side where I had tabs. How do I get the TextView to wrap around tabs as well?

**Comment by bilelmoussaoui** [comment]
Please use the discussions for "questions", https://github.com/gtk-rs/gtk4-rs/discussions

**Comment by bilelmoussaoui** [comment]
Otherwise this sounds like an issue/intended behaviour that comes from the library itself, so I would suggest opening an issue at https://gitlab.gnome.org/GNOME/gtk/
