### ISSUE TITLE
[HELP] GUI is only showing when running from a graphical enviorment

### ISSUE THREAD

**Issue by MAlba124** [gtk-rs/gtk4-rs#1374]
When I try to run any examples from a terminal I get this:
![gtk4-rs-problem](https://user-images.githubusercontent.com/83474682/232230976-d1f8252d-a582-40f5-9167-78f6682c994b.png)
(the leaves are the wallpaper)

When I run the same binary using `dmenu_run`, it works as expected.

**Comment by bilelmoussaoui** [comment]
Something broken your system.

**Comment by MAlba124** [comment]
I have had this issue on two separate systems.

**Comment by bilelmoussaoui** [comment]
Two separately broken setups
