### ISSUE TITLE
Book: How can I help?

### ISSUE THREAD

**Issue by zekefast** [gtk-rs/gtk4-rs#1377]
@Hofer-Julian I was reading through the book and it was awesome, but I also saw some teasers on other interesting chapters. Is there a way how I can help you to finish them sooner? :)

**Comment by bilelmoussaoui** [comment]
Not Julian, but I guess helping out with issues that are tagged https://github.com/gtk-rs/gtk4-rs/issues?q=is%3Aissue+is%3Aopen+label%3Abook would be of a good help as well

**Comment by Hofer-Julian** [comment]
Indeed. Although, make sure to comment on the issue before you are starting to work on it. Most of them need further discussion.

**Comment by zekefast** [comment]
Thank you @bilelmoussaoui.

@Hofer-Julian will do!

**Comment by bilelmoussaoui** [comment]
I suppose this can be closed now. Please join our Matrix: [#rust:gnome.org](https://matrix.to/#/#rust:gnome.org) channel and make use of https://github.com/gtk-rs/gtk4-rs/discussions for questions like this one in the future

**Comment by zekefast** [comment]
@bilelmoussaoui Thank you for the suggestion! I'll join it.
