### ISSUE TITLE
ApplicationWindow.show() deprecated function replacement

### ISSUE THREAD

**Issue by HarryTheFairy** [gtk-rs/gtk4-rs#1381]
I hope the following is posted in the correct/expected manner. Never used github before, I hope this helps in some way...

All examples I could find until now for creating an new Application + Window use gkt4::ApplicationWindow::**show** which cause a warning:
warning: use of deprecated associated function `gtk4::prelude::WidgetExt::show`: Since 4.10

- maybe a hint can be added what to use instead?
- in the release notes I foud this by accident: https://github.com/gtk-rs/gtk4-rs/pull/1072 which seems not to be directly related. ApplicationWindow::present() seems to be working fine though

cargo version: cargo 1.68.2 (6feb7c9cf 2023-03-26)

**Comment by jf2048** [comment]
Either that or `set_visible(true)`. The [upstream docs](https://docs.gtk.org/gtk4/method.Widget.show.html) say this but the gtk4-rs docs for this seem to be broken right now.

**Comment by HarryTheFairy** [comment]
Thanks, gtk::ApplicationWindow::set_visible(true) tested and works aswell.

**Comment by jf2048** [comment]
Currently affects a lot of things, it is a rustdoc-stripper bug: https://github.com/GuillaumeGomez/rustdoc-stripper/pull/82

cc @GuillaumeGomez

**Comment by bilelmoussaoui** [comment]
> Thanks, gtk::ApplicationWindow::set_visible(true) tested and works aswell.

you should not use set_visible(true) in windows, as if it is already visible, calling that wouldn't do "present" the window to the user by focusing it

Please make use of https://github.com/gtk-rs/gtk4-rs/discussions for future questions. 

Anyway, let us close this for now
