### ISSUE TITLE
[HELP] How do you reuse an existing C widget

### ISSUE THREAD

**Issue by zn3x** [gtk-rs/gtk4-rs#1393]
Hello, what is the most idiomatic way to use a C widget (like the one [here](https://gitlab.gnome.org/GNOME/gnome-contacts/-/blob/main/src/cc-crop-area.h)).

**Comment by bilelmoussaoui** [comment]
You re-implement it in Rust?

**Comment by zn3x** [comment]
Can't it be wrapped with a rust api type?

**Comment by bilelmoussaoui** [comment]
it can be, but that would require much more work then just writing the widget.

**Comment by sdroege** [comment]
Well, it's how all the existing C widgets from GTK itself etc are made available in Rust. You can do exactly the same :)

**Comment by zn3x** [comment]
Thanks for the help. After looking much closer.
I think having ffi bindings to the widget and converting between rust api types and ffi types using glib's `[ToGlibPtr](https://gtk-rs.org/gtk-rs-core/git/docs/glib/translate/trait.ToGlibPtr.html)` and `[FromGlibPtrFull](https://gtk-rs.org/gtk-rs-core/git/docs/glib/translate/trait.FromGlibPtrFull.html)` is a much more appropriate solution for my problem.
