### ISSUE TITLE
[HELP] Crosscompilation for Windows from Linux

### ISSUE THREAD

**Issue by MStarha** [gtk-rs/gtk4-rs#1403]
How can I crosscompile this crate for Windows from Linux? The regular cargo build fails because of custom build scripts that include pkg-config, which is not configured for crosscompilation. How can I configure it? The only solutions I found were using Docker, which I do not have the time to learn for a 'simple' crosscompilation.

**Comment by MGlolenstine** [comment]
I know you said you don't want to go with Docker, but I've created an image that helps you build/package Windows GTK binaries from Linux.
The execution should be straightforward and work as described in the README.
The repository can be found [here](https://github.com/MGlolenstine/gtk4-cross).

P.s: If there are any further questions, feel free to ask.

**Comment by MStarha** [comment]
Thank you, that is what I found and tried. The problem is I am completely unfamiliar with Docker, how to set it up, how to control it,... The description just is not thorough enough for a complete noob like me (things like launching Docker after installation, container creation, contrainer start,... , I had to figure out those myself and it still did not work).

I was doing just a quick test of Relm4, whether it is suitable for my upcoming projects, crosscompilation being one of the potential issues. As it turns out, it is not as simple installing a few dependencies and running `cargo build --target ...`, as is the case with other options.

That being said, I still want to try to get it to work. I just don't have the time to figure out what was wrong with the Docker setup I had.

But thank you anyway.

**Comment by MGlolenstine** [comment]
If you happen to be using Fedora, you could copy the installation instructions from the [base](https://github.com/MGlolenstine/gtk4-cross/blob/main/gtk4-cross-base-hub/Dockerfile) and [rust](https://github.com/MGlolenstine/gtk4-cross/tree/main/gtk4-cross-rust) images, install all required packages/dependencies and then you can build it by running `cargo build` with the correct target specified.

This is what Docker does behind the scenes.
Docker is just a Linux distro, predefined and preconfigured to run build instructions.

**Comment by MStarha** [comment]
I am using Fedora, but that seems like even more work with addition of bloating my system with build tools (I have installed some of them, though).

**Comment by MStarha** [comment]
I finally got some spare time and managed to look a bit at Docker and at the crosscompilation instructions you provided. The problem I had previously was an incorrect image tag/name when running the provided command:
```bash
docker run -ti -v `pwd`:/mnt:z gtk4-cross-rust
```
I had to replace `gtk4-cross-rust` with the image ID which in my case would look like:
```bash
docker run -ti -v `pwd`:/mnt:z 917efb663b45
```
I have no idea where the problem is. Why the original command does not work.

So I have managed to compile the code but when I run it, an error occurs with missing dynamic libraries:
 - libcairo-2.dll
 - libcairo-gobject-2.dll
 - libgio-2.0-0.dll
 - libgdk_pixbuf-2.0-0.dll

Where do I get the libraries? How do I statically compile them into the executable? Thank you.

**Comment by MGlolenstine** [comment]
Those libraries should be put next to the binary when the `package` command is run.

I've looked around, but couldn't find a way to statically link dependencies into the executable, so I've added the package command, which using pelld finds the dlls it needs and copies them into the resulting zip file.

**Comment by MStarha** [comment]
Sorry, my bad, I thought the `package` command is optional.

Not sure what I am doing wrong, but there is no `package.zip` file, just `name-version.crate` file. Further more, the package command recompiles everything in debug mode and not release (and does not accept the `--release` flag).

**Comment by MGlolenstine** [comment]
The [package](https://github.com/MGlolenstine/gtk4-cross/blob/main/gtk4-cross-base-hub/package.sh) command shouldn't be recompiling anything (except glib schemas).

**Comment by MStarha** [comment]
Now I understand, `build` and `package` are not commands (cargo commands), but custom bash scripts. Now it builds, packages,... It runs in my VM (with a message that some library is not available), but on a computer with Win10 installed it fails. I guess it is because of both Win10 and antivirus are blocking it.

Thank you.

**Comment by MGlolenstine** [comment]
Happy to be of help!

**Comment by bilelmoussaoui** [comment]
Please use the https://github.com/gtk-rs/gtk4-rs/discussions for generic and non-actionable questions.
