### ISSUE TITLE
`install_action_async` docs are unclear.

### ISSUE THREAD

**Issue by DaKnig** [gtk-rs/gtk4-rs#1411]
look [here](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/subclass/widget/trait.WidgetClassSubclassExt.html#method.install_action_async), what does `parameter_type` do? why is it `Option<&str>`? @bilelmoussaoui is telling me that the type should be changed to `VariantTy`.

**Comment by SeaDve** [comment]
This seems to also apply with `install_action`

**Comment by bilelmoussaoui** [comment]
It is unfortunate that GTK does actually create a VariantType from the passed string.... https://github.com/GNOME/gtk/blob/c274d073e01833f642cdc77e7f172dc74d028ee4/gtk/gtkwidget.c#L12780-L12783 so basically, you will create a VariantTy for it to be converted to a string to be converted back as a VariantType...
