### ISSUE TITLE
unresolved import `glib::signal::Inhibit` no `Inhibit` in `signal`

### ISSUE THREAD

**Issue by estkae** [gtk-rs/gtk4-rs#1416]
error[E0432]: unresolved import `glib::signal::Inhibit`
   --> gtk4\src\lib.rs:209:9
    |
209 | pub use glib::signal::Inhibit;
    |         ^^^^^^^^^^^^^^^^^^^^^ no `Inhibit` in `signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\about_dialog.rs:318:70
    |
318 |     pub fn connect_activate_link<F: Fn(&Self, &str) -> glib::signal::Inhibit + 'static>(
    |                                                                      ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\about_dialog.rs:323:56
    |
323 |             F: Fn(&AboutDialog, &str) -> glib::signal::Inhibit + 'static,
    |                                                        ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\entry_completion.rs:318:62
    |
318 |         F: Fn(&Self, &TreeModel, &TreeIter) -> glib::signal::Inhibit + 'static,
    |                                                              ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\entry_completion.rs:324:77
    |
324 |             F: Fn(&EntryCompletion, &TreeModel, &TreeIter) -> glib::signal::Inhibit + 'static,
    |                                                                             ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\entry_completion.rs:353:70
    |
353 |     pub fn connect_insert_prefix<F: Fn(&Self, &str) -> glib::signal::Inhibit + 'static>(
    |                                                                      ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\entry_completion.rs:358:60
    |
358 |             F: Fn(&EntryCompletion, &str) -> glib::signal::Inhibit + 'static,
    |                                                            ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\entry_completion.rs:386:62
    |
386 |         F: Fn(&Self, &TreeModel, &TreeIter) -> glib::signal::Inhibit + 'static,
    |                                                              ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\entry_completion.rs:392:77
    |
392 |             F: Fn(&EntryCompletion, &TreeModel, &TreeIter) -> glib::signal::Inhibit + 'static,
    |                                                                             ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\event_controller_key.rs:98:79
   |
98 |     pub fn connect_modifiers<F: Fn(&Self, gdk::ModifierType) -> glib::signal::Inhibit + 'static>(
   |                                                                               ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\event_controller_key.rs:103:76
    |
103 |             F: Fn(&EventControllerKey, gdk::ModifierType) -> glib::signal::Inhibit + 'static,
    |                                                                            ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\event_controller_legacy.rs:40:69
   |
40 |     pub fn connect_event<F: Fn(&Self, &gdk::Event) -> glib::signal::Inhibit + 'static>(
   |                                                                     ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\event_controller_legacy.rs:45:73
   |
45 |             F: Fn(&EventControllerLegacy, &gdk::Event) -> glib::signal::Inhibit + 'static,
   |                                                                         ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\event_controller_scroll.rs:96:67
   |
96 |     pub fn connect_scroll<F: Fn(&Self, f64, f64) -> glib::signal::Inhibit + 'static>(
   |                                                                   ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\event_controller_scroll.rs:101:70
    |
101 |             F: Fn(&EventControllerScroll, f64, f64) -> glib::signal::Inhibit + 'static,
    |                                                                      ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\gl_area.rs:495:70
    |
495 |     fn connect_render<F: Fn(&Self, &gdk::GLContext) -> glib::signal::Inhibit + 'static>(
    |                                                                      ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\gl_area.rs:501:57
    |
501 |             F: Fn(&P, &gdk::GLContext) -> glib::signal::Inhibit + 'static,
    |                                                         ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\label.rs:431:70
    |
431 |     pub fn connect_activate_link<F: Fn(&Self, &str) -> glib::signal::Inhibit + 'static>(
    |                                                                      ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\label.rs:436:50
    |
436 |             F: Fn(&Label, &str) -> glib::signal::Inhibit + 'static,
    |                                                  ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\link_button.rs:82:64
   |
82 |     pub fn connect_activate_link<F: Fn(&Self) -> glib::signal::Inhibit + 'static>(
   |                                                                ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\link_button.rs:87:49
   |
87 |             F: Fn(&LinkButton) -> glib::signal::Inhibit + 'static,
   |                                                 ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\range.rs:258:76
    |
258 |     fn connect_change_value<F: Fn(&Self, ScrollType, f64) -> glib::signal::Inhibit + 'static>(
    |                                                                            ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\range.rs:264:57
    |
264 |             F: Fn(&P, ScrollType, f64) -> glib::signal::Inhibit + 'static,
    |                                                         ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\spin_button.rs:307:57
    |
307 |     pub fn connect_output<F: Fn(&Self) -> glib::signal::Inhibit + 'static>(
    |                                                         ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\auto\spin_button.rs:312:49
    |
312 |             F: Fn(&SpinButton) -> glib::signal::Inhibit + 'static,
    |                                                 ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\switch.rs:93:66
   |
93 |     pub fn connect_state_set<F: Fn(&Self, bool) -> glib::signal::Inhibit + 'static>(
   |                                                                  ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\auto\switch.rs:98:51
   |
98 |             F: Fn(&Switch, bool) -> glib::signal::Inhibit + 'static,
   |                                                   ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\text_view.rs:1307:93
     |
1307 |         F: Fn(&Self, TextExtendSelection, &TextIter, &TextIter, &TextIter) -> glib::signal::Inhibit
     |                                                                                             ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\text_view.rs:1321:36
     |
1321 |                 ) -> glib::signal::Inhibit
     |                                    ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\tree_view.rs:2171:61
     |
2171 |         F: Fn(&Self, &TreeIter, &TreePath) -> glib::signal::Inhibit + 'static,
     |                                                             ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\tree_view.rs:2178:62
     |
2178 |             F: Fn(&P, &TreeIter, &TreePath) -> glib::signal::Inhibit + 'static,
     |                                                              ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\tree_view.rs:2208:61
     |
2208 |         F: Fn(&Self, &TreeIter, &TreePath) -> glib::signal::Inhibit + 'static,
     |                                                             ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\tree_view.rs:2215:62
     |
2215 |             F: Fn(&P, &TreeIter, &TreePath) -> glib::signal::Inhibit + 'static,
     |                                                              ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\widget.rs:1570:75
     |
1570 |     fn connect_keynav_failed<F: Fn(&Self, DirectionType) -> glib::signal::Inhibit + 'static>(
     |                                                                           ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\widget.rs:1576:55
     |
1576 |             F: Fn(&P, DirectionType) -> glib::signal::Inhibit + 'static,
     |                                                       ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\widget.rs:1625:70
     |
1625 |     fn connect_mnemonic_activate<F: Fn(&Self, bool) -> glib::signal::Inhibit + 'static>(
     |                                                                      ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\widget.rs:1631:46
     |
1631 |             F: Fn(&P, bool) -> glib::signal::Inhibit + 'static,
     |                                              ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\window.rs:1011:60
     |
1011 |     fn connect_close_request<F: Fn(&Self) -> glib::signal::Inhibit + 'static>(
     |                                                            ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
    --> gtk4\src\auto\window.rs:1017:40
     |
1017 |             F: Fn(&P) -> glib::signal::Inhibit + 'static,
     |                                        ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\subclass\text_view.rs:35:24
   |
35 |     ) -> glib::signal::Inhibit {
   |                        ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
   --> gtk4\src\subclass\text_view.rs:124:24
    |
124 |     ) -> glib::signal::Inhibit {
    |                        ^^^^^^^ not found in `glib::signal`

error[E0425]: cannot find function, tuple struct or tuple variant `Inhibit` in module `glib::signal`
   --> gtk4\src\subclass\text_view.rs:129:31
    |
129 |                 glib::signal::Inhibit(from_glib(f(
    |                               ^^^^^^^ not found in `glib::signal`

error[E0425]: cannot find function, tuple struct or tuple variant `Inhibit` in module `glib::signal`
   --> gtk4\src\subclass\text_view.rs:137:31
    |
137 |                 glib::signal::Inhibit(false)
    |                               ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\subclass\window.rs:26:46
   |
26 |     fn close_request(&self) -> glib::signal::Inhibit {
   |                                              ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\subclass\window.rs:84:53
   |
84 |     fn parent_close_request(&self) -> glib::signal::Inhibit {
   |                                                     ^^^^^^^ not found in `glib::signal`

error[E0425]: cannot find function, tuple struct or tuple variant `Inhibit` in module `glib::signal`
  --> gtk4\src\subclass\window.rs:91:27
   |
91 |             glib::signal::Inhibit(from_glib(f(self
   |                           ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\event_controller_key.rs:10:82
   |
10 |         F: Fn(&EventControllerKey, Key, u32, gdk::ModifierType) -> glib::signal::Inhibit + 'static,
   |                                                                                  ^^^^^^^ not found in `glib::signal`

error[E0412]: cannot find type `Inhibit` in module `glib::signal`
  --> gtk4\src\event_controller_key.rs:16:86
   |
16 |             F: Fn(&EventControllerKey, Key, u32, gdk::ModifierType) -> glib::signal::Inhibit + 'static,
   |                                                                                      ^^^^^^^ not found in `glib::signal`

Some errors have detailed explanations: E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `gtk4` (lib) due to 48 previous errors

PS C:\Windows\System32> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\kae\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc
1.65.0-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.70.0 (90c541806 2023-05-31)

$ pacman -S base-devel gcc vim cmake curl
warning: base-devel-2022.12-2 is up to date -- reinstalling
warning: gcc-11.3.0-3 is up to date -- reinstalling
warning: vim-9.0.1403-1 is up to date -- reinstalling
warning: cmake-3.26.4-1 is up to date -- reinstalling
warning: curl-8.1.1-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (5) base-devel-2022.12-2  cmake-3.26.4-1  curl-8.1.1-2  gcc-11.3.0-3  vim-9.0.1403-1

I work gtk4-rs repo.

**Comment by sdroege** [comment]
That's fixed by https://github.com/gtk-rs/gtk4-rs/pull/1414

**Comment by sdroege** [comment]
or rather, you also need to `cargo update` in addition to that.
