### ISSUE TITLE
Change the Display implementation for EntryBuffer

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [gtk-rs/gtk4-rs#1425]
The current implementation of `Display` for `EntryBuffer` just returns `"EntryBuffer"`. Although intuitively one would expect for it to return the internal GString converted to a String.

<https://gtk-rs.org/gtk4-rs/stable/latest/docs/src/gtk4/auto/entry_buffer.rs.html#248-252>

**Comment by bilelmoussaoui** [comment]
A PR would be appreciated here. You would have to modify the Gtk.EntryBuffer entry in `gtk4/Gir.toml` and set `generate_display_trait = false`, see https://gtk-rs.org/gir/book/config/api.html, then manually implement the trait in https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/entry_buffer.rs

**Comment by LevitatingBusinessMan** [comment]
Looks like @AbuShawarib was faster, but closed the PR just now.
