### ISSUE TITLE
passing args to cli results in this args being pased to gtk which cusses it to exit with code 0 

### ISSUE THREAD

**Issue by Horryportier** [gtk-rs/gtk4-rs#1436]
**Bug description**
i have cli tool that controls mpv thought socket. I wanted to add simple player window so i added flag for that `-g` but when running it with that flag using `cargo run -- -g` or `. /target/debug/bin_name -g` it will exit with code 1. But when changing it to run without any args it creates window as it should.

```rust
fn main() {
    let args = args().collect::<Vec<String>>();
    let args = &args[1..];
    if args[0] == "-g".to_string() {
        println!("{}", gui());
    }
}

pub fn gui() ->  ExitCode {
    let app = Application::builder().application_id(API_ID).build();

    app.run()
} 
```
**Backtrace**

[bug.txt](https://github.com/gtk-rs/gtk4-rs/files/12174740/bug.txt)

**Comment by bilelmoussaoui** [comment]
If you want to handle the cli yourself without going through glib, you should use run_with_args and pass an empty vec to it iirc

**Comment by Horryportier** [comment]
thanks now works without any issues
