### ISSUE TITLE
Subclassing `MapListModel`

### ISSUE THREAD

**Issue by arguablykomodo** [gtk-rs/gtk4-rs#1437]
I am trying to create a custom `ListModel` which consists of a composition of other models chained together. The last model in the chain is a `MapListModel`, so I thought that instead of creating a wrapper type which does all the setup and having to manually pass through the methods and signals, I could simply subclass `MapListModel`, but it seems that it is impossible to do this as `MapListModel` doesn't implement `IsSubclassable`. Is this an easy fix or is `MapListModel` not subclassable due to some technical limitation?

**Comment by RealKC** [comment]
`MapListModel` is declared as final by gtk itself (see https://docs.gtk.org/gtk4/class.MapListModel.html) so not being able to subclass it seems intentional

**Comment by arguablykomodo** [comment]
I can't believe I missed that annotation :facepalm:. I ended up going the wrapper route in the end anyways. Thanks for the reply!
