### ISSUE TITLE
[HELP] Book: Ch. 5.4 Properties - #[derived_properties] Requires glib-macros

### ISSUE THREAD

**Issue by cornmonger** [gtk-rs/gtk4-rs#1438]
In [Chapter 5.4: Adding Properties to Custom GObjects](https://gtk-rs.org/gtk4-rs/git/book/g_object_properties.html#adding-properties-to-custom-gobjects), the example makes use of the `derived_properties` macro:

```rust
// [...]
use glib::Properties;
use gtk::glib;
use gtk::prelude::*;
use gtk::subclass::prelude::*;

// [...]

#[glib::derived_properties]
impl ObjectImpl for CustomButton {
```

The macro call doesn't resolve for me if I simply follow the instructions in [Chapter 2: Project Setup](https://gtk-rs.org/gtk4-rs/git/book/project_setup.html).  I have to manually `cargo add glib-macros` and then alter the example with:
```rust
// [...]
use glib_macros;

// [...]

// Trait shared by all GObjects
#[glib_macros::derived_properties]
impl ObjectImpl for CustomButton {
```

After that everything compiles and runs properly.

I'm I doing something wrong or is this a documentation problem?
Thanks!

**Comment by bilelmoussaoui** [comment]
See #1435

**Comment by cornmonger** [comment]
Thanks. That answers another problem I ran into later as well.
