### ISSUE TITLE
Keep gtk::DialogExt::run() as async variant

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk4-rs#144]
When looking at my usage of `dialog.run()` I decided to just implement an `async run()`.

The only solution I see is to connect to the "response" event and send the result through a channel. But I can also check how gtk3 implemented this.

Any thoughts?

**Comment by sdroege** [comment]
`Dialog::run()` should also really be removed from the GTK3 bindings. A recursive mainloop is only causing problems, and I think we also moved away all examples from `run()` to using the `response` signal.

So yes, using the `response` would the right approach :) And wrapping an `async fn` around that with a oneshot channel would be even nicer usability-wise, I guess.

**Comment by sophie-h** [comment]
I think what I want is completely impossible. In the end awaiting the future will always be blocking, because it is not `Send`.

**Comment by sdroege** [comment]
The thread can continue doing other things in the meantime

**Comment by sophie-h** [comment]
This is a minimal example of my problem. Maybe `glib::MainContext::default().spawn_local()` is the wrong approach. But I don't see any other way this could be done.

```rust
    async fn recv_future() {
        // omitted gtk code which makes this none Send

        // create a fake channel
        let (_tx, rx) = std::sync::mpsc::channel::<()>();
        let _result = rx.recv();
    }

    // only function that I know of that can spawn recv_future
    glib::MainContext::default().spawn_local(recv_future());
```

(I also have a complete implementation, which also can only be spawned via `spawn_local`)

```rust
#[async_trait(?Send)]
pub trait DialogExtFuture {
    async fn run_future(&self) -> gtk::ResponseType;
}

#[async_trait(?Send)]
impl DialogExtFuture for gtk::Dialog {
    async fn run_future(&self) -> gtk::ResponseType {
        let (sender, receiver) = std::sync::mpsc::channel();
        let response_handler = self.connect_response(move |_, response_type| {
            let _result = sender.send(response_type);
        });

        self.set_modal(true);
        self.show();

        let result = receiver.recv().unwrap_or(gtk::ResponseType::None);
        self.disconnect(response_handler);

        result
    }
}
```

**Comment by sdroege** [comment]
That channel is not async but will block on `recv()`. You need [this](https://docs.rs/futures/0.3.8/futures/channel/oneshot/index.html) one and then `recv.await` for getting the value out of the channel.
