### ISSUE TITLE
How to clear/update list on click list

### ISSUE THREAD

**Issue by Klubuntu** [gtk-rs/gtk4-rs#1457]
I'm using Rust 1.71 and #gtk = { version = "0.7.1", package = "gtk4", features = ["v4_8"] }
What do I have to do to make it work in ListBox?

**Comment by bilelmoussaoui** [comment]
https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.ListBox.html#method.remove_all or iterate or use bind_model then all you have to do is update the model items or remove all the items from it. See https://github.com/gtk-rs/gtk4-rs/tree/master/examples/list_box_model

**Comment by bilelmoussaoui** [comment]
Also please use https://github.com/gtk-rs/gtk4-rs/discussions for questions
