### ISSUE TITLE
book: Ch 11 Building a Simple To-Do App: Missing explanation of window::new_tasks()

### ISSUE THREAD

**Issue by cornmonger** [gtk-rs/gtk4-rs#1460]
I see an anchor for `window::new_tasks` in the referenced [source code](https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/todo/1/window/mod.rs), but the method isn't mentioned or visible in the chapter without un-hiding lines for the file.

**Comment by Hofer-Julian** [comment]
Nice find, thanks for reporting @cornmonger!
