### ISSUE TITLE
Use GTK 4.12 API as soon as Fedora 39 is released

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk4-rs#1467]
Basically revert https://github.com/gtk-rs/gtk4-rs/commit/0e0e0590205bd2b1f44b5a4014d200abbbb60096

**Comment by bilelmoussaoui** [comment]
Path APIs? :P

**Comment by Hofer-Julian** [comment]
I thought you meant this change in your PR https://github.com/gtk-rs/gtk4-rs/pull/1463
But I guess that was only a drive-by commit.
