### ISSUE TITLE
Let `gtk::Builder::object::<T>` call  `T::ensure_type()` internally

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk4-rs#1489]
`gtk::TemplateChild<T>` already calls `T::ensure_type()` internally. 
As discussed with @bilelmoussaoui, it would be great if  `gtk::Builder::object::<T>` would do the same.

**Comment by bilelmoussaoui** [comment]
I don't know if it is worth doing so or not; maybe it is ok as we already do it for CompositeTemplate already.
