### ISSUE TITLE
gtk::FileDialog panics when opening gvfs file

### ISSUE THREAD

**Issue by felinira** [gtk-rs/gtk4-rs#1491]
Any of the single file selection methods (`save`, `open`, `select_folder_future`) will panic when opening a file from gvfs. The reason is probably related to portals not being able to open files from gvfs volumes (only URI, no concrete path).

`thread 'main' panicked at 'assertion failed: !ptr.is_null()', /home/Code/test/_build/cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.18.1/src/auto/file.rs:14:1`

This can be reproduced by opening a file from an smb share for example.

**Comment by bilelmoussaoui** [comment]
I would say fix GTK.

**Comment by sdroege** [comment]
Did someone report it to GTK already? If so, please link to the issue here.

**Comment by A6GibKm** [comment]
https://gitlab.gnome.org/GNOME/gtk/-/issues/6139

**Comment by matthiasclasen** [comment]
I don't think there's a justification for the bindings to panic. The return value is annotated as nullable

**Comment by sdroege** [comment]
Yes, the code is wrongly generated:

```xml
      <method name="save_finish" c:identifier="gtk_file_dialog_save_finish" version="4.10" throws="1">
        <doc xml:space="preserve">Finishes the [method@Gtk.FileDialog.save] call and
returns the resulting file.</doc>
        <return-value transfer-ownership="full" nullable="1">
          <doc xml:space="preserve">the file that was selected.
  Otherwise, `NULL` is returned and @error is set</doc>
          <type name="Gio.File" c:type="GFile*"/>
        </return-value>
```

**Comment by A6GibKm** [comment]
When the API was added we asked if it was ok to assume it will never NULL out (when there is no error) and added an override to reflect the intent of the API

```
[[object]]
name = "Gtk.FileDialog"
status = "generate"
    [[object.function]]
    pattern = "(open|save|open_multiple|select_folder)"
        [object.function.return]
        nullable = false
```

**Comment by sdroege** [comment]
Ok, so that was apparently wrong then and should be reverted for the next release early next year :)

**Comment by matthiasclasen** [comment]
I'm setting an error now
