### ISSUE TITLE
gtk4: warning: private item shadows public glob re-export

### ISSUE THREAD

**Issue by decathorpe** [gtk-rs/gtk4-rs#1496]
I'm the maintainer of the gtk-rs crates in Fedora, and I just noticed a warning that *might* be indicative of a problem when I built gtk4 v0.7.3 (output part of, basically, running `cargo build` for gtk4 v0.7.3):

```
warning: private item shadows public glob re-export
   --> src/lib.rs:148:1
    |
148 | mod functions;
    | ^^^^^^^^^^^^^^
    |
note: the name `functions` in the type namespace is supposed to be publicly re-exported here
   --> src/lib.rs:105:9
    |
105 | pub use auto::*;
    |         ^^^^^^^
note: but the private item here shadows it
   --> src/lib.rs:148:1
    |
148 | mod functions;
    | ^^^^^^^^^^^^^^
    = note: `#[warn(hidden_glob_reexports)]` on by default

warning: `gtk4` (lib) generated 1 warning
```

Not sure if this is a false positive or not, but I thought it was worth asking about it here.

**Comment by bilelmoussaoui** [comment]
Already solved in main but backporting it would be an API break

**Comment by sdroege** [comment]
Yeah let's close this then. It's only a warning after all and solved in the next release

**Comment by decathorpe** [comment]
Great, thanks for confirming! :) I couldn't see any obvious fix in the commit history, which is why I asked.
