### ISSUE TITLE
MacOS installation procedure

### ISSUE THREAD

**Issue by Resonanz** [gtk-rs/gtk4-rs#1500]
For MacOS install (https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_macos.html), why install Rust then Homebrew? Why not install HomeBrew then Rust:

brew install rust
brew install gtk4

Done. Seems simpler.

**Comment by bilelmoussaoui** [comment]
Sure, why not close this issue as well. Done. Seems simpler.
