### ISSUE TITLE
WidgetClassExt::add_binding's callback returns a bool instead of ControlFlow

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk4-rs#1505]
Normally one would return gdk::EVENT_PROPAGATE or gdk::EVENT_STOP in these, but you can't since the later are u32 instead of bool. I think this should retun a glib::ControlFlow.

https://gtk-rs.org/gtk4-rs/git/docs/gtk4/subclass/widget/trait.WidgetClassExt.html#method.add_binding

**Comment by sdroege** [comment]
@A6GibKm Want to provide a PR?

**Comment by bilelmoussaoui** [comment]
It would be nice to check all the subclassing code for cases where we return a boolean as well

**Comment by bilelmoussaoui** [comment]
The callback you pass ends up being used for creating a CallbackAction, https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.CallbackAction.html#method.new. The callback is a https://docs.gtk.org/gtk4/callback.ShortcutFunc.html and as you can see, `TRUE` means the action was successful but i am not sure if that maps correctly. Continue doesn't convey the action was handled

**Comment by bilelmoussaoui** [comment]
I would have closed the issue as  I don't think we should change the type here but I have noticed few cases in the manual code where it would make more sense to switch to using ControlFlow/Propagation.
