### ISSUE TITLE
FileChooserNativeBuilder drops the filters

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#151]
Creating a dialog with a filter like 
```rust
let gif_filter = gtk::FileFilter::new();
gif_filter.add_mime_type("image/gif");
gif_filter.set_name(Some("GIF (image/gif)"));


let file_chooser = gtk::FileChooserNativeBuilder::new()
    .accept_label("Open")
    .cancel_label("Cancel")
    .modal(true)
    .title("Open a GIF to display")
    .transient_for(self)
    .action(gtk::FileChooserAction::Open)
    .filter(&gif_filter)
    .build();
```

wouldn't show up which is normal as the filter isn't a prop as the builder somehow assumes? and should use the method in `FileChooserExt::add_filter` to assign all those filters which would require writing the builder manually I guess

Works fine btw
```rust
let gif_filter = gtk::FileFilter::new();
gif_filter.add_mime_type("image/gif");
gif_filter.set_name(Some("GIF (image/gif)"));


let file_chooser = gtk::FileChooserNativeBuilder::new()
    .accept_label("Open")
    .cancel_label("Cancel")
    .modal(true)
    .title("Open a GIF to display")
    .transient_for(self)
    .action(gtk::FileChooserAction::Open)
    .build();
file_chooser.add_filter(&gif_filter);
```

**Comment by sophie-h** [comment]
Sounds like the documented behavior https://developer.gnome.org/gtk3/stable/GtkFileChooser.html#gtk-file-chooser-set-filter

Maybe it's possible to make the list managed by `add_filter` a property upstream. Then we would get the feature that you want as well.

**Comment by bilelmoussaoui** [comment]
Yeah it's just confusing. I think the property should have been called default-filter or something like that. I'm going to go ahead and close this one as I don't believe it's something actionable from our side. What would be nice to have though is for gir to generate comments for each property setter based on the props documentation if there are any?

**Comment by piegamesde** [comment]
Ran into this again, was really confusing. Is there any reason why we don't panic in builders when setting the same property twice? This would have prompted me to the mistake a lot quicker
