### ISSUE TITLE
Segmentation fault when overriding `gtk::WidgetImpl::snapshot`

### ISSUE THREAD

**Issue by zecakeh** [gtk-rs/gtk4-rs#1539]
**Bug description**

I am overriding `gtk::WidgetImpl::snapshot`, but this code is causing a segmentation fault at the last line:

```rust
    fn snapshot(&self, snapshot: &gtk::Snapshot) {
            let borrow = self.child.borrow();
            let Some(child) = borrow.as_ref() else {
                return;
            };

            let obj = self.obj();

            if !self.is_cropped.get() || self.cropped_width.get() == 0 {
                obj.snapshot_child(child, snapshot);
                return;
            }

            snapshot.push_mask(gsk::MaskMode::InvertedAlpha);

            obj.snapshot_child(&self.mask, snapshot);
            snapshot.pop();

            obj.snapshot_child(child, snapshot);
            snapshot.pop();
        }
```

A minimal reproducer built upon gtk-rust-template is available here: https://gitlab.gnome.org/kcommaille/snapshot-mask/-/blob/main/src/crop_circle.rs?ref_type=heads#L105-125

I am mainly porting this C code from libadwaita: https://gitlab.gnome.org/GNOME/libadwaita/-/blob/ddd1bd567bfb93f0fbe59da7355b3457b86a90f0/src/adw-indicator-bin.c#L123-147

**Backtrace**

<details><summary>Click to expand</summary>
<pre><code>Core was generated by `snapshot-mask'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb09f4cf36e in g_atomic_ref_count_inc () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7fb09d5befc0 (LWP 2))]
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /app/bin/snapshot-mask.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt full
#0  0x00007fb09f4cf36e in g_atomic_ref_count_inc () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fb09ec32e14 in gtk_snapshot_collect_mask_source () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#2  0x00007fb09ec337cc in gtk_snapshot_pop_one () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#3  0x00007fb09ec34897 in gtk_snapshot_pop () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#4  0x000055711669d06b in gtk4::auto::snapshot::SnapshotExt::pop<gtk4::auto::snapshot::Snapshot> (self=0x7ffe682c2420) at _build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.7.3/src/auto/snapshot.rs:321
#5  0x000055711668c0b9 in snapshot_mask::crop_circle::imp::{impl#1}::snapshot (self=0x557117fb5090, snapshot=0x7ffe682c2420) at src/crop_circle.rs:124
        obj = glib::object::BorrowedObject<snapshot_mask::crop_circle::CropCircle> {ptr: core::ptr::non_null::NonNull<gobject_sys::GObject> {pointer: 0x557117fb5200}, phantom: core::marker::PhantomData<&snapshot_mask::crop_circle::CropCircle>}
        child = 0x557117fb50a0
        borrow = core::cell::Ref<core::option::Option<gtk4::auto::widget::Widget>> {value: core::ptr::non_null::NonNull<core::option::Option<gtk4::auto::widget::Widget>> {pointer: 0x557117fb50a0}, borrow: core::cell::BorrowRef {borrow: 0x557117fb5098}}
#6  0x00005571166abb18 in gtk4::subclass::widget::widget_snapshot<snapshot_mask::crop_circle::imp::CropCircle> (ptr=0x557117fb5200, snapshot_ptr=0x55711a56c2f0)
    at _build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.7.3/src/subclass/widget.rs:809
        snapshot = glib::translate::Borrowed<gtk4::auto::snapshot::Snapshot> (core::mem::manually_drop::ManuallyDrop<gtk4::auto::snapshot::Snapshot> {value: gtk4::auto::snapshot::Snapshot {inner: glib::object::TypedObjectRef<*mut core::ffi::c_void, ()> {inner: glib::object::ObjectRef {inner: core::ptr::non_null::NonNull<gobject_sys::GObject> {pointer: 0x55711a56c2f0}}, imp: core::marker::PhantomData<*mut core::ffi::c_void>, parent: core::marker::PhantomData<()>}, phantom: core::marker::PhantomData<()>}})
        imp = 0x557117fb5090
        instance = 0x557117fb5200
#7  0x00007fb09ec9c94b in gtk_widget_create_render_node () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#8  0x00007fb09ec9f7dc in gtk_widget_do_snapshot () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#9  0x00007fb09ecabee2 in gtk_widget_snapshot_child () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#10 0x00007fb09ecabfae in gtk_widget_real_snapshot () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#11 0x00007fb09ec9c94b in gtk_widget_create_render_node () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#12 0x00007fb09ec9f7dc in gtk_widget_do_snapshot () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#13 0x00007fb09ecabee2 in gtk_widget_snapshot_child () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#14 0x00007fb09ecabfae in gtk_widget_real_snapshot () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#15 0x00005571166a8339 in gtk4::subclass::widget::WidgetImplExt::parent_snapshot<snapshot_mask::window::imp::ExampleApplicationWindow> (self=0x557118061de0, snapshot=0x7ffe682c29b0)
    at _build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.7.3/src/subclass/widget.rs:480
        f = 0x7fb09ecabf70 <gtk_widget_real_snapshot>
        parent_class = 0x557117f59af0
        data = core::ptr::non_null::NonNull<glib::subclass::types::TypeData> {pointer: 0x5571167f8520 <<snapshot_mask::window::imp::ExampleApplicationWindow as glib::subclass::types::ObjectSubclassType>::type_data::DATA::h7170352f6473907d>}
#16 0x00005571166a75c3 in gtk4::subclass::widget::WidgetImpl::snapshot<snapshot_mask::window::imp::ExampleApplicationWindow> (self=0x557118061de0, snapshot=0x7ffe682c29b0)
    at _build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.7.3/src/subclass/widget.rs:185
#17 0x00005571166abba8 in gtk4::subclass::widget::widget_snapshot<snapshot_mask::window::imp::ExampleApplicationWindow> (ptr=0x557118062060, snapshot_ptr=0x55711a56c2f0)
    at _build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gtk4-0.7.3/src/subclass/widget.rs:809
        snapshot = glib::translate::Borrowed<gtk4::auto::snapshot::Snapshot> (core::mem::manually_drop::ManuallyDrop<gtk4::auto::snapshot::Snapshot> {value: gtk4::auto::snapshot::Snapshot {inner: glib::object::TypedObjectRef<*mut core::ffi::c_void, ()> {inner: glib::object::ObjectRef {inner: core::ptr::non_null::NonNull<gobject_sys::GObject> {pointer: 0x55711a56c2f0}}, imp: core::marker::PhantomData<*mut core::ffi::c_void>, parent: core::marker::PhantomData<()>}, phantom: core::marker::PhantomData<()>}})
        imp = 0x557118061de0
        instance = 0x557118062060
#18 0x00007fb09ec9cd58 in gtk_widget_create_render_node () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#19 0x00007fb09ec9f7dc in gtk_widget_do_snapshot () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#20 0x00007fb09ecab83c in gtk_widget_render () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#21 0x00007fb09ecb31a9 in surface_render () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#22 0x00007fb09ee38017 in _gdk_marshal_BOOLEAN__BOXEDv () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#23 0x00007fb09f9b5652 in _g_closure_invoke_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#24 0x00007fb09f9ca7b3 in signal_emit_valist_unlocked () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x00007fb09f9d13c1 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#26 0x00007fb09f9d1483 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#27 0x00007fb09eeb2c49 in gdk_surface_paint_on_clock () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#28 0x00007fb09f9b5652 in _g_closure_invoke_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#29 0x00007fb09f9cb4af in signal_emit_valist_unlocked () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#30 0x00007fb09f9d13c1 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#31 0x00007fb09f9d1483 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#32 0x00007fb09ee9ff7d in _gdk_frame_clock_emit_paint () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#33 0x00007fb09eea0dcf in gdk_frame_clock_paint_idle () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#34 0x00007fb09f4b9c3a in g_timeout_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#35 0x00007fb09f4b6d47 in g_main_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007fb09f4b8e57 in g_main_context_iterate_unlocked.isra () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007fb09f4b9513 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007fb09f69cb1d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#39 0x0000557116685f2e in gio::application::ApplicationExtManual::run_with_args<snapshot_mask::application::ExampleApplication, alloc::string::String>
    (self=0x7ffe682c4150, args=...) at _build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gio-0.18.3/src/application.rs:29
        argc = 1
        argv = alloc::vec::Vec<&str, alloc::alloc::Global> {buf: alloc::raw_vec::RawVec<&str, alloc::alloc::Global> {ptr: core::ptr::unique::Unique<&str> {pointer: core::ptr::non_null::NonNull<&str> {pointer: 0x557117ec4390}, _marker: core::marker::PhantomData<&str>}, cap: 1, alloc: alloc::alloc::Global}, len: 1}
#40 0x0000557116686049 in gio::application::ApplicationExtManual::run<snapshot_mask::application::ExampleApplication> (self=0x7ffe682c4150)
    at _build/cargo-home/registry/src/index.crates.io-6f17d22bba15001f/gio-0.18.3/src/application.rs:22
#41 0x000055711669819c in snapshot_mask::application::ExampleApplication::run (self=0x7ffe682c4150) at src/application.rs:138
#42 0x00005571166a1dc5 in snapshot_mask::main () at src/main.rs:32
        app = snapshot_mask::application::ExampleApplication {inner: glib::object::TypedObjectRef<snapshot_mask::application::imp::ExampleApplication, libadwaita::auto::application::Application> {inner: glib::object::ObjectRef {inner: core::ptr::non_null::NonNull<gobject_sys::GObject> {pointer: 0x557117ec4580}}, imp: core::marker::PhantomData<snapshot_mask::application::imp::ExampleApplication>, parent: core::marker::PhantomData<libadwaita::auto::application::Application>}, phantom: core::marker::PhantomData<()>}
        res = gio::auto::resource::Resource {inner: glib::shared::Shared<gio_sys::GResource, gio::auto::resource::Resource> {inner: core::ptr::non_null::NonNull<gio_sys::GResource> {pointer: 0x557117ebd490}, mm: core::marker::PhantomData<*const gio::auto::resource::Resource>}}
</code></pre>
</details>

**Comment by bilelmoussaoui** [comment]
This looks to me like a gtk issue imho

**Comment by zecakeh** [comment]
It is, it turns out that when I write code that actually works, GTK doesn't panic. It's still not ideal that GTK panics when there is something wrong, but I don't think it's worth keeping this open.
