### ISSUE TITLE
Widget's add_binding bindings are a bit off

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk4-rs#1542]
One thing is, that it uses bool instead of glib::Propagate

Second thing is, that the variants passed to the closure seems to be nothing than a weird variant of extra-data which are usually dropped from the bindings.

**Comment by bilelmoussaoui** [comment]
> Second thing is, that the variants passed to the closure seems to be nothing than a weird variant of extra-data which are usually dropped from the bindings.

Are you sure about this? =)

**Comment by bilelmoussaoui** [comment]
Fixed in main

**Comment by bilelmoussaoui** [comment]
> [6938071](https://github.com/gtk-rs/gtk4-rs/commit/69380715ea613981b7a3c9dcccd34eb961c8ec7f)
> 
> Did you …forget to stage it?

chances of mistakes increase significantly when you are half asleep and tired, the fix is in some other commit and i had already pushed to main...

**Comment by bilelmoussaoui** [comment]
That comes from gtk::CallbackAction itself, which is not related to this issue which was about the required argument to pass when using `add_binding`

**Comment by sophie-h** [comment]
Created a new issue #1590
