### ISSUE TITLE
```ColumnView``` contains a child which type does not exist in the binding

### ISSUE THREAD

**Issue by if0ne** [gtk-rs/gtk4-rs#1543]
I try to access to the ```ColumnView```'s header:
```rust
let column_view = gtk::ColumnView::new(Option::<gtk::NoSelection>::None);
let header = column_view.first_child().unwrap();
dbg!(header.type_());
```
This code has next output:
```
header.type_() = GtkColumnViewRowWidget
```

Type ```GtkColumnViewRowWidget``` is similar to ```GtkColumnViewRow```, but it's different types.

**Solution**
Generate code for [```GtkColumnViewRow```](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkcolumnviewrowwidget.c).

**Comment by sdroege** [comment]
It's not public API from what I can see. Why do you need bindings for it, what are you trying to do?

**Comment by if0ne** [comment]
> It's not public API from what I can see. Why do you need bindings for it, what are you trying to do?

I need to make the column header fixed (header stays on top when scrolling). I thought manipulating the ```ColumnView``` child object would help me.

**Comment by bilelmoussaoui** [comment]
That is expected, widgets and any library actually, can have internals that are not part of the public API.

The thing you are trying to achieve is probably something better discussed in the issues tracker of the GTK project itself. The bindings can't do anything here.
