### ISSUE TITLE
[HELP] Rust Analyzer Warning for ObjectSubclass impl

### ISSUE THREAD

**Issue by D0bhareach** [gtk-rs/gtk4-rs#1547]
Starting from around 25.12.23 while reading through examples for repository using VS Code IDE all implementations of ObjectSubclass have red underlined line and error message is: ```not all trait items implemented, missing: `type Interfaces`, `type Instance`, `type Class`rust-analyzer[E0046](https://doc.rust-lang.org/stable/error_codes/E0046.html)```   
This warning wasn't present before and appear only recently. Despite of this message examples still are building and running.

**Comment by sdroege** [comment]
That's a bug in rust-analyzer. It doesn't correctly handle the `#[glib::object_subclass]` attribute macro (which is automatically implementing those associated types if not present).

Please report this to rust-analyzer.
