### ISSUE TITLE
Add binding for GtkGraphicsOffload

### ISSUE THREAD

**Issue by rmader** [gtk-rs/gtk4-rs#1553]
Introduced in https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6533/diffs?commit_id=e2023483803d583a68ba35ad3093c3e3d12619c9, to ship in 4.14.

The intention is to use if for `gtk4paintablesink`, see https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/issues/441

---

cc @sdroege

**Comment by sdroege** [comment]
Probably need to get https://github.com/gtk-rs/gir-files/pull/181 in first, and then this can be done.

Also as part of this you probably need support for creating textures from dmabufs? Anything else?

**Comment by rmader** [comment]
> Also as part of this you probably need support for creating textures from dmabufs? Anything else?

Right, `GdkDmabufTextureBuilder` bindings. That should be all I think, judging from https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6618
