### ISSUE TITLE
undefined symbol: gtk_file_dialog_open_finish [HELP]

### ISSUE THREAD

**Issue by Necro-U** [gtk-rs/gtk4-rs#1557]
I am tryig to run text_viewer example that you provided. It returns me with this error:

`target/debug/ui: symbol lookup error: target/debug/ui: undefined symbol: gtk_file_dialog_open_finish`

About my system:
Ubuntu 22.04.3 
Windowing System: Wayland
gtk version that I am using: 4.10.5

I found something at [here](https://stackoverflow.com/questions/67090039/undefined-symbol-gdk-display-get-primary-monitor), it looks my error. but I am not be sure because other application [windows](https://gtk-rs.org/gtk4-rs/stable/latest/book/hello_world.html) runs correctly.

**Comment by bilelmoussaoui** [comment]
This is an issue, will fix it

**Comment by bilelmoussaoui** [comment]
Actually, there is nothing broken on gtk4-rs, it is likely your gtk build.

**Comment by Necro-U** [comment]
yes, the reason that i got this error is about gtk version on my ubuntu i think.
