### ISSUE TITLE
gtk::PopoverMenuFlags erroneously locked behind v4_14 feature flag in 0.8.0

### ISSUE THREAD

**Issue by awused** [gtk-rs/gtk4-rs#1617]
**Bug description**

Code that used gtk4::PopoverMenuFlags in 0.7.x, no longer builds with 0.8.0 unless I update my system GTK to 4.13 and add the v4_14 feature flag. https://github.com/gtk-rs/gtk4-rs/commit/203267a06aa5af3548ee017567fcbddee088d59b#diff-91bde5f398691e1b094f02f2857771e5c5795c443133b73a20adbaca0ef4c944 added a feature flag to existing types and methods, so I assume something went wrong when regenerating the files. I haven't looked to see if there are other similar bugs, but I'd assume any other cases where a brand new flag is added to an existing method or type are also likely to be bogus.

**Comment by awused** [comment]
Seems it wasn't a gir bug, but a mistake in gtk. It should be fixed by regenerating the bindings with https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6938

**Comment by bilelmoussaoui** [comment]
0.8.1 is out
