### ISSUE TITLE
Shortcut keys are not working on macOS

### ISSUE THREAD

**Issue by abhi3700** [gtk-rs/gtk4-rs#1636]
Does `gtk4-rs` support using shortcut keys on macOS:
- <kbd>cmd+v</kbd>: paste text.

Currently, using `gtk-rs` (`v0.7.3`) version.

For more details about the error, this [issue](https://github.com/subspace/space-acres/issues/145) can be referred to.

If yes, could you please provide an example code?

**Comment by bilelmoussaoui** [comment]
As was mentioned in that issue, the error should probably reported upstream as the bindings don't do anything and I don't have access to a macos so can't help more.
