### ISSUE TITLE
docs for setting PATH on windows in book is wrong

### ISSUE THREAD

**Issue by pm100** [gtk-rs/gtk4-rs#1645]
Book says to set PATH to include

`Edit the variable named Path and add C:\gtk-build\gtk\x64\release\lib\pkgconfig to it`

Should say

`Edit the variable named Path and add C:\gtk-build\gtk\x64\release\bin to it`

**Comment by Hofer-Julian** [comment]
Closed by https://github.com/gtk-rs/gtk4-rs/pull/1675
