### ISSUE TITLE
`impl Default` that can be derived in the examples

### ISSUE THREAD

**Issue by enaut** [gtk-rs/gtk4-rs#1662]
https://github.com/gtk-rs/gtk4-rs/blob/1e12dc2af30d9cf18a80dbc21f07e2bdeeaa1974/examples/tokio_async_request/main.rs#L23-L27

Hey while learning I stumbled upon the clippy lint hinting, that this `impl` is actually also generated automatically via derive default. Should I open a PR removing and adjusting the example?

**Comment by sdroege** [comment]
Sounds like a good idea, thanks!
