### ISSUE TITLE
Infrastructure to provide Rust code samples in the docs

### ISSUE THREAD

**Issue by pieterdd** [gtk-rs/gtk4-rs#1664]
I noticed that the code snippets in gtk4-rs' documentation are mostly written in C. This adds friction to the learning process, requiring users to understand and translate C code to Rust in their heads to get value from the snippets.

I'm aware that this isn't easy to solve from a maintainer's perspective, as it is a logical consequence of Gir importing widget documentation from GTK's C codebase. Any thoughts on how to pave the way for contributors to replace the C snippets with Rust?

The most obvious option I see would be to inline the widget documentation so contributors can easily replace the C snippets with Rust ones. But that doesn't seem desirable in the long term, since it's good to keep the docs in sync with GTK's core.

Another option could be to let the core GTK codebase introduce snippet IDs so bindings in other languages may replace the snippets with language-appropriate ones. Here's how that could work in the C codebase:

```c
/**
  * GtkLabel:
  *
  * The `GtkLabel` widget displays a small amount of text. (..)
  *
  * Here’s a simple example where the label is inside a button:
  * 
  * ```c[id="inside_button"]
  * // Pressing Alt+H will activate this button
  * GtkWidget *button = gtk_button_new ();
  * GtkWidget *label = gtk_label_new_with_mnemonic ("_Hello");
  * gtk_button_set_child (GTK_BUTTON (button), label);
  * ```
  */
```

On gtk4-rs' end, you could then implement an annotation mechanism to provide Gir with Rust-specific snippets for those IDs, allowing it to seamlessly merge the upstream C documentation with the Rust code blocks. Heck, maybe you could even run the snippets as documentation tests.

What would you recommend?

**Comment by sdroege** [comment]
Maybe @GuillaumeGomez has some ideas here.

> The most obvious option I see would be to inline the widget documentation so contributors can easily replace the C snippets with Rust ones. But that doesn't seem desirable in the long term, since it's good to keep the docs in sync with GTK's core.

This is also a license problem because the GTK docs are LGPL licensed.

**Comment by bilelmoussaoui** [comment]
I think we would need to add such identifier upstream. From there, it would be pretty easy to implement in the rust gir project.

**Comment by pieterdd** [comment]
I've pitched this idea and a variation on it to the GTK developers, but they were unlikely to be implemented so the ideal scenario doesn't seem to be possible right now. While there are alternatives not requiring upstream changes, they seem less clean and/or less appealing for end users. I'll close this thread for now.
