### ISSUE TITLE
Update each widget struct doc page with supported builder XML sections (and pre-defined identifier strings)

### ISSUE THREAD

**Issue by jerrywrice** [gtk-rs/gtk4-rs#1674]
Review and determine, while discussing with team, a reasonable and manageable way to revise the document page for the various widgets, to concisely, accurately and thoroughly specify the supported builder XML sections. In addition to concise descriptions of the supported section options, each predefined identifier string required for the XML should be specified.

**Comment by bilelmoussaoui** [comment]
The documentation comes from the gtk project, please report any missing documentation there https://gitlab.gnome.org/GNOME/gtk/. But note, a very broad issue like this is not really actionable. Instead, write down the list of widgets that you think should contain more documentation of how to use the widget in an xml file.

**Comment by jerrywrice** [comment]
> The documentation comes from the gtk project, please report any missing documentation there https://gitlab.gnome.org/GNOME/gtk/. But note, a very broad issue like this is not really actionable. Instead, write down the list of widgets that you think should contain more documentation of how to use the widget in an xml file.

Understood. I'll close this issue, and submit a revised edition of it which lists those Gtk widgets which insufficiently document their buildable XML section details.
