### ISSUE TITLE
get_xdisplay() is missing from gdk4-x11::X11Display

### ISSUE THREAD

**Issue by mmMike** [gtk-rs/gtk4-rs#170]
Hi, 

I want to move a window on X11, so I need to get access to the respective X11 display and window. 
Following the GDK4 documentation this API call should be used: https://developer.gnome.org/gdk4/stable/gdk4-X-Window-System-Interaction.html#gdk-x11-display-get-xdisplay

Gir.toml mentions it in line 55: https://github.com/gtk-rs/gtk4-rs/blob/master/gdk4-x11/Gir.toml#L55
But the source doesn't contain the API call: https://github.com/gtk-rs/gtk4-rs/blob/master/gdk4-x11/src/auto/x11_display.rs

I'm not sure if this is really a bug, or if I need to generate something. A hint how to fix it manually would also be welcome.

gtk4-rs, gdk4-x11

**Comment by bilelmoussaoui** [comment]
The line below mentions that it's manual, although, it could have used a "# TODO ` comment :) The functions can't be generated automatically and needs to be written manually

**Comment by mmMike** [comment]
Ok, thank you for your reply. Meanwhile I managed to implement the function locally in my app. But should these "manual" functions be part of the crate in the future or will it stay a manual task for all users of that crate who need them?

**Comment by bilelmoussaoui** [comment]
> Ok, thank you for your reply. Meanwhile I managed to implement the function locally in my app. But should these "manual" functions be part of the crate in the future or will it stay a manual task for all users of that crate who need them?

We definitely want them to be included in the crate, see how I did the wayland ones for example, https://github.com/gtk-rs/gtk4-rs/blob/master/gdk4-wayland/src/wayland_device.rs

**Comment by bilelmoussaoui** [comment]
I have added explicit todo notes for those missing functions :)

**Comment by alatiera** [comment]
I will take a look at this :)
