### ISSUE TITLE
Invalid property: GtkApplicationWindow.window-position

### ISSUE THREAD

**Issue by aadog** [gtk-rs/gtk4-rs#1706]
(nwguitest.exe:5140): Gtk-ERROR **: 14:05:33.817: failed to add UI: .:7:39 Invalid property: GtkApplicationWindow.window-position
error: process didn't exit successfully: `target\debug\nwguitest.exe` (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)

**Comment by bilelmoussaoui** [comment]
Because there is no such property. Not sure what I am supposed to do with such an unclear issue other than closing it.
