### ISSUE TITLE
 gtk::DragIcon::for_drag returns Widget, not DragIcon

### ISSUE THREAD

**Issue by felinira** [gtk-rs/gtk4-rs#1748]
gtk::DragIcon::for_drag returns a gtk::Widget. Usually we return the concrete type in such methods.

**Comment by bilelmoussaoui** [comment]
Should be fixed upstream https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkdragicon.c#L413

**Comment by bilelmoussaoui** [comment]
> `from_icon_name`

I don't see where we override those...

**Comment by bilelmoussaoui** [comment]
I see why, `gtk_drag_icon_get_for_drag` is not marked as a constructor.

**Comment by bilelmoussaoui** [comment]
Sent a fix upstream
