### ISSUE TITLE
No method named `dispose_template` found for reference `&custom_buildable::imp::CustomBuildable` in the current scope

### ISSUE THREAD

**Issue by mtilda** [gtk-rs/gtk4-rs#1754]
I am copying the Custom Buildable example in [this repo](https://github.com/mtilda/example-rust-gtk4/tree/58219b55692b8b1a240c8265e587fd415ae9002e/src/custom_buildable) using GTK 4.10.4 on Ubuntu 23.04.

You can see what crates I'm using in my [Cargo.toml](https://github.com/mtilda/example-rust-gtk4/blob/58219b55692b8b1a240c8265e587fd415ae9002e/Cargo.toml) and [Cargo.lock](https://github.com/mtilda/example-rust-gtk4/blob/58219b55692b8b1a240c8265e587fd415ae9002e/Cargo.lock) files.

    gtk4 = "0.8.2"
    imp = "0.1.0"

#### Problem

The program panics with the following error:

    error[E0599]: no method named `dispose_template` found for reference `&custom_buildable::imp::CustomBuildable` in the current scope

Commenting out [this line](https://github.com/mtilda/example-rust-gtk4/blob/58219b55692b8b1a240c8265e587fd415ae9002e/src/custom_buildable/imp.rs#L52) in my version of the code avoids the panic, but causes the following warning when I run the application and close the Custom Buildable window:

    Gtk-WARNING **: 19:23:52.941: Finalizing CustomBuildable 0x55bcfa532b90, but it still has children left:
    - GtkBox 0x55bcfa532ff0

#### Open questions

- [x] Are others able to reproduce this behavior?

- [x] Should we change the following line or some other code in this example?

  https://github.com/gtk-rs/gtk4-rs/blob/44ec2cf599a33df0990ecb579493b5305e604885/examples/custom_buildable/custom_buildable/imp.rs#L38

**Comment by mtilda** [comment]
When I clone this repo, `cd` into `examples`, and run `cargo run --bin custom_buildable --features="v4_10"`, there is no error or warning. Surely I have configured something differently in my repo...

**Comment by bilelmoussaoui** [comment]
You forgot to enable the required feature for that function. As you can see in your command, you are enabling v4_10

**Comment by mtilda** [comment]
Okay, that makes sense. I am able to fix the error by modifying my Cargo.toml file like this:

```diff
 [dependencies]
-gtk4 = "0.8.2"
 imp = "0.1.0"
+
+[dependencies.gtk]
+package = "gtk4"
+version = "0.8.2"
+features = ["v4_10"]
```
