### ISSUE TITLE
Is it possible to improve compile times?

### ISSUE THREAD

**Issue by coderedart** [gtk-rs/gtk4-rs#1767]
I just created the basic gtk button example from the book and ran `cargo build --timings` on windows 11, ryzen 2600x (12 threads), 16 GB DDR4. 

![image](https://github.com/gtk-rs/gtk4-rs/assets/24411704/dcadd11f-f343-4bd2-b006-78618f7923f3)

95 seconds seems really long on a reasonably powerful machine. Especially considering that gtk is dynamically linked. 

I was wondering if there's a way to reduce compile times.

**Comment by sdroege** [comment]
I think the only way to improve compile times here is optimizing the compiler. My main guess for the long compile times is the huge amount of extension traits used by gio/gtk4.

Outside compile times, using mold as linker improves linking times for gtk4-rs applications considerably.
