### ISSUE TITLE
Support for dark mode

### ISSUE THREAD

**Issue by philip-peterson** [gtk-rs/gtk4-rs#1797]
I went looking for information on dark mode. It seems like it is normally supported by GTK4 apps through libadwaita. The way to access this through Rust may be libadwaita's `StyleManager::is_dark`.

https://docs.rs/libadwaita/latest/libadwaita/struct.StyleManager.html#method.is_dark

**Comment by sdroege** [comment]
As this is a general GTK question not directly related to the bindings, you'll probably have more luck at https://discourse.gnome.org

**Comment by martinling** [comment]
See https://github.com/greatscottgadgets/packetry/pull/166 for an example of doing this without libadwaita.

**Comment by bilelmoussaoui** [comment]
You can use https://docs.rs/ashpd/latest/ashpd/desktop/settings/struct.Settings.html#method.receive_color_scheme_changed as well.

Closing as it is not really an issue on the bindings side.
