### ISSUE TITLE
Book: Issue with glib::spawn_future_local in gtk-rs Chapter 6

### ISSUE THREAD

**Issue by azurekite83** [gtk-rs/gtk4-rs#1798]
When using glib::spawn_future_local with clone macro from Chapter 6 in gtk-rs, compiler spits out error stating:
 `
error: Unexpected token [weak]  --> src/main.rs:53:10
   |
53 |         #[weak]
   |         
`

**Comment by sdroege** [comment]
Which version of gtk4-rs are you using? This sounds like you're using 0.8 (glib-rs 0.19) and not 0.9 (glib-rs 0.20). The `#[weak]` syntax is new in that release.

**Comment by azurekite83** [comment]
You're right. I'm using MSYS2 and built gtk4 differently so I've been trying to cargo update instead of updating from MSYS2. I appreciate it.

**Comment by azurekite83** [comment]
Just tried updating with MSYS2. No updates for gtk happened, tried uninstalling and building using gvsbuild but gvsbuild is installing 0.8 still. Is 0.9 going to be built from scratch until gvsbuild is updated?

**Comment by sdroege** [comment]
gvsbuild has nothing to do with gtk-rs updates, that's all handled by cargo. Check that you have version 0.9 in your `Cargo.toml`.

**Comment by azurekite83** [comment]
Oh ok, thank you.
