### ISSUE TITLE
Should connect_unrealize and connect_destroy be FnOnce() rather than Fn()?

### ISSUE THREAD

**Issue by alshdavid** [gtk-rs/gtk4-rs#1806]
Currently `connect_unrealize` and `connect_destroy` are typed as `Fn()`s [source](https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/prelude/trait.WidgetExt.html#method.connect_unrealize).

This can cause some annoyances when it comes to passing single use values into these callbacks.

I have been using this adapter:

```rust
let label = gtk::Label::builder().build();

g1.connect_unrealize(fnonce_to_fn(move |_label| {
  println!("Removed");
}));

// Adapter
pub fn fnonce_to_fn<P, I>(input: I) -> Box<dyn Fn(&P)>
where
  P: IsA<gtk::Widget>,
  I: FnOnce(&P) + 'static,
{
  let cell = Cell::new(Some(input));

  Box::new(move |p: &P| {
    let func = (&cell).take().expect("Can only run once");
    func(p);
  })
}
```

My question is, can callbacks like `connect_unrealize` and `connect_destroy` really be called multiple times? Is an `Fn()` an accurate type signature for them or should they be an `FnOnce()`?

**Comment by sdroege** [comment]
As mentioned on Matrix, these can actually be called multiple times.
