### ISSUE TITLE
[HELP] Examples to use `block_signal` and `unblock_signal`

### ISSUE THREAD

**Issue by Doublonmousse** [gtk-rs/gtk4-rs#1817]
The two fonctions `block_signal` and `unblock_signal` don't have examples and I can't seem to find any way to use them because of [SignalHandlerId](https://gtk-rs.org/gtk-rs-core/git/docs/glib/signal/struct.SignalHandlerId.html#) not implementing `Clone`.

I'd want to setup a spinbutton with a `connect_value_changed` signal handler and block/unblock this signal when changing the value programmatically to distinguish this from user input (and makind it easier to not have issues related to additional signals being triggered).

But adding custom methods (like a `block` and `unblock`)in my template won't work even using a `RefCell` from this lack of `Clone`. 
I failed to do the "take the Signal handler id -> convert to c_ulong -> reconstruct the signal handler ID" as well. But at this point it's more of a hacky workaround than anything else.

**Comment by bilelmoussaoui** [comment]
You should store the signal handler in a RefCell<Option<SignalHandlerID>> so you can take the value and leave None there.

**Comment by bilelmoussaoui** [comment]
also use the forum for discussions.

**Comment by Doublonmousse** [comment]
Well the thing is that this is a operation done once right ?
I need to block/unblock multiple times

**Comment by bilelmoussaoui** [comment]
Then instead of using .take() you should use borrow().

if let Some(handler) = self.handler.borrow() {}...

**Comment by bilelmoussaoui** [comment]
The handler is on purpose not Clone, so you don't do unsafe things with it.
