### ISSUE TITLE
[HELP] Segmentation fault while attaching tab to gtk::Notebook

### ISSUE THREAD

**Issue by ggodlewski** [gtk-rs/gtk4-rs#1823]
I'm creating browser-like app with multiple tabs which can be detached as separated windows.
I extracted small example here: https://github.com/ggodlewski/gtk4-notebook-app/blob/main/src/main.rs

The result is something like that:

![image](https://github.com/user-attachments/assets/31a393ec-c150-40bd-b379-16e0156efa34)

After detaching I have 2 windows (if it doesn't randomly crash):

![image](https://github.com/user-attachments/assets/e168cc3b-381d-4087-961b-34e3a361f4d9)

When I try to reattach Tab1 to first window I'm getting: `Segmentation fault (core dumped)`
Is there anything else than `set_tab_detachable` that I need to do or is it some bug in the library?

I'm running this on Ubuntu 24.04

**Comment by ggodlewski** [comment]
For the future generations:

It's a problem with gtk.

I did a test using python https://github.com/ggodlewski/gtk4-notebook-app/blob/main/gtk3.py https://github.com/ggodlewski/gtk4-notebook-app/blob/main/gtk4.py and it also doesn't work while working perfectly fine under gtk3

Doing some debugging I located it:
```
Core was generated by `target/debug/app'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  gtk_notebook_dnd_finished_cb (drag=<optimized out>, widget=0x59b940d47cd0 [GtkNotebook]) at ../../../gtk/gtknotebook.c:3244
3244          g_signal_emit (notebook, notebook_signals[CREATE_WINDOW], 0,
[Current thread is 1 (Thread 0x756ddf9d7f40 (LWP 331473))]
(gdb) f 0
#0  gtk_notebook_dnd_finished_cb (drag=<optimized out>, widget=0x59b940d47cd0 [GtkNotebook]) at ../../../gtk/gtknotebook.c:3244
3244          g_signal_emit (notebook, notebook_signals[CREATE_WINDOW], 0,
(gdb) p notebook->detached_tab->child
Cannot access memory at address 0x18
(gdb) p notebook->detached_tab
$5 = 0x0
```

https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtknotebook.c?ref_type=heads#L3337

Instead of
```
      g_signal_emit (notebook, notebook_signals[CREATE_WINDOW], 0,
                     notebook->detached_tab->child, &dest_notebook);
```

There should be

```
if (notebook->detached_tab)
      g_signal_emit (notebook, notebook_signals[CREATE_WINDOW], 0,
                     notebook->detached_tab->child, &dest_notebook);
```

`do_detach_tab` is called prior setting  notebook->detached_tab to` NULL`. Since in this case tab is dropped on another notebook `create-window` event is not necessary.

However, I have other issues and I'm on the edge of switch to qt/anything else. GTK has it's own gitlab instance, I'm not creating yet another account to do this trivial PR.

**Comment by sdroege** [comment]
You can create an account with your github account.

There's nothing we can do about this crash here, it's an issue in gtk. Closing for now but please feel free to create new issues or discussions about anything bindings / Rust-related here.
