### ISSUE TITLE
[HELP]  example clipboard

### ISSUE THREAD

**Issue by CodigoCristo** [gtk-rs/gtk4-rs#1861]
[dependencies]
gdk = "0.13"
glib = "0.20.4"
gtk = { version = "0.9.2", package = "gtk4", features = ["v4_12"] }

```
(rust:76491): GLib-GObject-CRITICAL **: 11:41:37.215: cannot register existing type 'GdkDisplayManager'

(rust:76491): GLib-CRITICAL **: 11:41:37.215: g_once_init_leave_pointer: assertion 'result != 0' failed

(rust:76491): GLib-GObject-CRITICAL **: 11:41:37.215: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
fish: Job 1, 'cargo run' terminated by signal SIGSEGV (Address boundary error)
```

![image](https://github.com/user-attachments/assets/fa10c222-2cf1-461c-b45b-0e7e67732a91)

**Comment by bilelmoussaoui** [comment]
> 
gdk = "0.13"
glib = "0.20.4"
gtk = { version = "0.9.2", package = "gtk4", features = ["v4_12"] }

You are mixing gtk3 and gtk4. You don't need the gdk = nor the glib one.

**Comment by bilelmoussaoui** [comment]
you can use `use gtk::{gdk, glib};` and so on.
