### ISSUE TITLE
I'm having an issue creating a custom GtkLabel

### ISSUE THREAD

**Issue by pixel27** [gtk-rs/gtk4-rs#1918]
My main window class as getting huge with all the state and code, so I broke the code out to custom GTK objects that just worry about the state they are interested in.  I have a message router notifying the Widgets of state changes so they can update their state.

For example I have two custom buttons, previous and next.  They are notified about state changes so they know if it makes sense to move to the next page or the previous page. When they are clicked they send out a message requesting to move to the next page.  I wanted to create a custom label that just tracks the current page (and the total pages) and displays that to the user.

From the examples for other custom components, I created:
```
use gtk4 as gtk;
use gtk::glib;

glib::wrapper! {
    pub struct CustomLabel(ObjectSubclass<imp::CustomLabel>)
        @extends gtk::Label,
                 gtk::Widget,
        @implements gtk::Accessible,
                    gtk::Actionable,
                    gtk::Buildable,
                    gtk::ConstraintTarget;
}

mod imp {
    use gtk4 as gtk;
    use gtk::{glib, subclass::prelude::*};

    #[derive(Default)]
    pub struct CustomLabel;

    #[glib::object_subclass]
    impl ObjectSubclass for CustomLabel {
        const NAME: &'static str = "CustomLabel";
        type Type                = super::CustomLabel;
        type ParentType          = gtk::Label;
    }

    impl ObjectImpl for CustomLabel {}
    impl WidgetImpl for CustomLabel {}
    impl LabelImpl for CustomLabel { }
}
```
However **LabelImpl** is not found. If I just comment out that line, I get a compiler error:

```
error[E0277]: the trait bound `gtk4::Label: IsSubclassable<custom_label::imp::CustomLabel>` is not satisfied
   --> src/custom_label.rs:25:36
    |
25  |         type ParentType          = gtk::Label;
    |                                    ^^^^^^^^^^ the trait `IsSubclassable<custom_label::imp::CustomLabel>` is not implemented for `gtk4::Label`
    |
    = help: the following other types implement trait `IsSubclassable<T>`:
              Adjustment
              ApplicationWindow
              BuilderCScope
              CellArea
              CellAreaContext
              CellRenderer
              CellRendererText
              CheckButton
            and 48 others
note: required by a bound in `gtk4::subclass::prelude::ObjectSubclass::ParentType`
   --> /home/****/.cargo/registry/src/index.crates.io-6f17d22bba15001f/glib-0.20.6/src/subclass/types.rs:647:22
    |
647 |     type ParentType: IsSubclassable<Self>
    |                      ^^^^^^^^^^^^^^^^^^^^ required by this bound in `ObjectSubclass::ParentType`
```
It seems like LabelImpl really doesn't exist, I have the gtk-rs code and searched through it. I don't know if there is a different class I  need to pull in? Or maybe customizing a GtkLabel is just not something people do?

**Comment by bilelmoussaoui** [comment]
You can't create a custom GtkLabel. If you want to have a custom label, you would have to create a custom GtkWidget, embed the GtkLabel inside of it and change it depends on your needs. Anything that doesn't provide a `TImpl` trait is not subclassable.
