### ISSUE TITLE
RGBA::new object does not apply to TextTag::set_foreground_rgba

### ISSUE THREAD

**Issue by d47081** [gtk-rs/gtk4-rs#1931]
I spent few hours until understand that found a bug, could somebody try to reproduce combination for

``` rust
tag = TextTag::new(None);
tag.set_foreground_rgba(Some(&RGBA::new(1.0, 1.0, 1.0, 1.0)));
```
and `a`, `b` variants

```rust
    let a = RGBA::new(1.0, 1.0, 1.0, 1.0);
    let b = RGBA::parse(format!(
        "rgba({},{},{},{})",
        1.0, 1.0, 1.0, 1.0
    ))
    .unwrap();
```

`RGBA::new` here does not apply color, I don't know why, but it work when parsed from string (`b`) 
The problem with `a`, even it contains valid object dump:

```bash
RGBA { red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0 }
```

``` Cargo.toml
[dependencies.gtk]
package = "gtk4"
version = "0.9.1"
features = ["gnome_47"]
```

**Comment by sdroege** [comment]
See the docs

> “r”, “g”, and “b” are either integers in the range 0 to 255 or percentage values in the range 0% to 100%, and a is a floating point value in the range 0 to 1.

```rust
    let b = RGBA::parse(format!(
        "rgba({},{},{},{})",
        255, 255, 255, 1.0
    ))
```

should give the same result. If you print both `a` and `b` the difference should also be clear.
