### ISSUE TITLE
Links Crash Application on Macos

### ISSUE THREAD

**Issue by snoweuph** [gtk-rs/gtk4-rs#1936]
**Bug description**

I've built an desktop application with gtk-rs and adw.
A few days ago, I had a change to test it out on a MacBook (M2).
There was only one problem: links in the application were crashing it.

Specifically, I'm using the  `adw::AboutWindow`.
The crashes are happening for mailto, and for normal links as well.

**Log**
```bash
Gtk-WARNING **: 16:24:55.004: Cannot connect to session bus when initializing OpenURI portal: Ein Nachrichtenbus kann nicht ohne eine Rechner-Kennung erzeugt werden: /usr/local/var/lib/dbus/machine-id oder /etc/machine-id kann nicht geladen werden: Datei »/usr/local/var/lib/dbus/machine-id« konnte nicht geöffnet werden: No such file or directory
```

The Problem seem to be, that there is no `/etc/machine-id` on macOS, and thus the lib seem to panic and crash.

**Comment by bilelmoussaoui** [comment]
The issue should be reported on the C library. It has nothing to do with the bindings

**Comment by snoweuph** [comment]
okay

**Comment by snoweuph** [comment]
I nee

> The issue should be reported on the C library. It has nothing to do with the bindings

would you say its an ADW or GTK Problem?

**Comment by bilelmoussaoui** [comment]
If you can paste a back trace of the crash using something like gdb then i can point you where to report it.

**Comment by snoweuph** [comment]
For now I've reported it to Adw: https://gitlab.gnome.org/GNOME/libadwaita/-/issues/974
But this might even be a regression of: https://gitlab.gnome.org/GNOME/glib/-/issues/3403
I got a Dump from that Macos Device for the Crash, gonna start sanitizing it, and then provide it

**Comment by snoweuph** [comment]
[Uploading bhg_error_dump.txt…]()
