### ISSUE TITLE
Non-future, async gdk4::Clipboard functions require Send-type callbacks

### ISSUE THREAD

**Issue by xerz-one** [gtk-rs/gtk4-rs#202]
The following functions demand a callback function which includes `Send` in its type parameters:

- `gdk4::Clipboard::read_async`
- `gdk4::Clipboard::read_texture_async`
- `gdk4::Clipboard::read_text_async`
- `gdk4::Clipboard::read_value_async`
- `gdk4::Clipboard::store_async`

This seems to be redundant, and can prevent their usage with thread-unsafe variables.

**Comment by felixfaisal** [comment]
Hey @bilelmoussaoui can I work on this

**Comment by bilelmoussaoui** [comment]
Sure, let's us know if you need any help
