### ISSUE TITLE
Handle Gtk.*Expression

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#21]
Needs something similar to 

quoting slomo
>Actually nevermind, it shouldn't have a new() function but basically work like https://gitlab.freedesktop.org/gstreamer/gstreamer-rs/-/blob/master/gstreamer/src/param_spec.rs#L13 . That way it will work well with the subclass property API.

**Comment by sdroege** [comment]
> Using Expressions from source code has been super weird so far, but thankfully you can use those from the UI file as well.

Maybe we can provide a manual API on top of the plain bindings that makes it more convenient. Maybe something macro based
