### ISSUE TITLE
`ListView::set_model()` takes the wrong type

### ISSUE THREAD

**Issue by JMS55** [gtk-rs/gtk4-rs#220]
According to https://developer.gnome.org/gtk4/3.98/GtkListView.html#gtk-list-view-set-model

`ListView::set_model()` should take a `ListModel`, and then if it's not a `SelectionModel`, it should wrap it in a `SingleSelection`.

Currently, it only takes a `SelectionModel`.

**Comment by bilelmoussaoui** [comment]
You're looking at an old version of the docs. See https://developer.gnome.org/gtk4/stable/GtkListView.html#gtk-list-view-set-model. It does require a SelectionModel. 

You're supposed to use [`gtk::NoSelection`](https://gtk-rs.org/gtk4-rs/gtk4/struct.NoSelection.html)
