### ISSUE TITLE
Implement Gtk.CustomLayout

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#23]
The `gtk_custom_layout_new` needs some manual bindings

**Comment by ebassi** [comment]
I don't recommend implementing CustomLayout. It's a C API for transitioning existing widgets from the `GtkWidget` virtual functions of GTK3 to the virtual functions in `GtkLayoutManager`. Writing subclasses, even private ones, in Rust is definitely easier than doing so in C.

**Comment by bilelmoussaoui** [comment]
Thanks @ebassi for confirming that's something we shouldn't include. It's already possible to subclass `GtkLayoutManager` which should cover the custom layout manager use case
