### ISSUE TITLE
ShortcutTrigger should impl `Eq/PartialEq/Hash`

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#240]
Instead of exposing `eq`, `compare`, `hash` methods.

**Comment by sdroege** [comment]
As it's a `GObject`, this is not possible without causing coherence problems (e.g. `obj1.downcast::<glib::Object>() != obj2.downcast::<glib::Object>()` but `obj1.downcast::<gtk::ShortcutTrigger>() == obj2.downcast::<gtk::ShortcutTrigger>()`). Traits don't compose well with subtyping.

**Comment by bilelmoussaoui** [comment]
Ah. I didn't thought of it. Not great :/ I guess we can at least improve the `compare` function to return a `std::cmp::Ordering` instead of a `i32`

**Comment by sdroege** [comment]
Yes that would be a good idea. There's even a `impl FromGlib<i32> for std::cmp::Ordering` for this purpose :)
