### ISSUE TITLE
Resolve links to other gtk-rs crates in docs

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk4-rs#249]
This is a known problem, but not documented yet as far as I can see.
If we for example look at the implemented traits of Button, the link to `glib::object::ObjectExt` is broken.
https://gtk-rs.org/gtk4-rs/gtk4/struct.Button.html#implements

**Comment by bilelmoussaoui** [comment]
I think we should build the docs for all the packages, then replaces on all the files the links for specific crates that are part of the public API & remove the rest. I will have a look before the hackfest.

**Comment by bilelmoussaoui** [comment]
What do you think @GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
The problem is how we handle the documentation generation. The link is correct in the context the crate was documented, but isn't anymore there. The simplest way is to try to figure out what went wrong: is it rustdoc intra-doc or is it gir which creates the issue? :)

**Comment by bilelmoussaoui** [comment]
Yes, but it's the same for all the public APIs that use glib/gio/ and other crates. They must build the docs for all the packages which is confusing I think. My idea was to link from the gtk4-rs docs to gtk-rs ones manually. So that the broken link mentioned by @Hofer-Julian would point to the gtk-rs docs

**Comment by GuillaumeGomez** [comment]
There are arguments to be used in rustdoc which allow that. We just need to test a few things.

**Comment by bilelmoussaoui** [comment]
I have fixed half the issue, the other half is at https://github.com/gtk-rs/gir/blob/7edc5fbedae250296f4ba60fbba10e7a85558d59/src/codegen/doc/mod.rs#L233-L236 it should detect the `RUSTDOCFLAGS` & make use of `--extern-html-root-url` to generate a link to each trait 

Please open an issue in https://github.com/gtk-rs/gir for that

**Comment by GuillaumeGomez** [comment]
I'm not sure to understand why `gir` should do about `RUSTDOCFLAGS`... What would it use it for?

**Comment by bilelmoussaoui** [comment]
It generates a list of the trait implemented by each object, one of them is `glib::object::ObjectExt` and it links it as `[glib::object::ObjectExt](../glib/object/trait.ObjectExt.html)`. Instead it should check for the glib root url and use it. It's the only link that's broken currently, at least in gtk4-rs.

**Comment by bilelmoussaoui** [comment]
See https://gtk-rs.org/gtk4-rs/gtk4/struct.SignalAction.html for an example

**Comment by GuillaumeGomez** [comment]
> It generates a list of the trait implemented by each object, one of them is `glib::object::ObjectExt` and it links it as `[glib::object::ObjectExt](../glib/object/trait.ObjectExt.html)`. Instead it should check for the glib root url and use it. It's the only link that's broken currently, at least in gtk4-rs.

Ah right. With intra-docs, it doesn't need the part between parens anymore. We can completely remove that. Then rustdoc will generate using the root path like it should. Yeay intra-doc links!
