### ISSUE TITLE
Generate index page for the docs

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#254]
Currently, the CI pushes the docs output into the `docs/git` subdirectory in the `gh-pages` branch and the book into `book/git`. I created a very simple page in the main directory so that https://gtk-rs.org/gtk4-rs would point you to both the docs/book. 

The link above works fine, but the docs have to point to a specific crate as there's no generic index page. It seems like there's a `index-page` flag we can pass to rustdoc but that doesn't actually works :D 

Building the docs with `RUSTDOCFLAG="--index-page=./README.md -Z unstable-options" cargo doc` doesn't seem to generate an index.html page. 

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
It requires an option for that: https://doc.rust-lang.org/rustdoc/unstable-features.html?highlight=index#--enable-index-page-generate-a-default-index-page-for-docs

**Comment by bilelmoussaoui** [comment]
The docs mentions 
> Using index-page option enables enable-index-page option as well.

Even with `--enable-index-page` it doesn't do anything

**Comment by GuillaumeGomez** [comment]
I think it requires another parameter (for the index page file). Let's check together that in the hackfest.

**Comment by jsparber** [comment]
it needs nighlty rust. This works: https://github.com/matrix-org/matrix-rust-sdk/blob/master/.github/workflows/docs.yml
