### ISSUE TITLE
Signals comments

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk4-rs#258]
- Maybe mention the difference between `connect` and `connect_local`, and that the properly typed connector functions take care of this distinction themselves. Might be just a footnote
 - `let button = args.get(0).unwrap().get::<Button>().unwrap().unwrap();` explain the `unwrap`s here like for properties, and also why not `args[0]`? It's a slice after all :) Maybe also mention that the first argument to signals is always the object that emitted the signal, and that this specific signal has no other arguments
 - "// Types of the values which will be sent to the receiver" (and below that): Receiver would be better called "signal handler" as that's the GObject terminology
 - You do it correct, but it's worth a note in the `clicked` function that you should really never ever keep a mutex (or refcell) locked/borrowed while: emitting signals, notifying property changes, anything that can cause these to happen. Because that will call into external code, and that external code might call back into your object, trying to use the same mutex/refcell and then you have a problem :)

**Comment by Hofer-Julian** [comment]
> why not args[0]

Is the reason, that it is Rust convention that [...] panics and `get` returns an `Err` if something goes wrong?

**Comment by sdroege** [comment]
Well, you `unwrap()` so it will panic anyway... also if that ever fails there's really no way how you can handle that gracefully. That would mean that GLib is broken and then everything's beyond repair :)

**Comment by Hofer-Julian** [comment]
Ah now I get it, that was a suggestion.
I didn't use it, because I didn't know it was possible.
Will fix it in the next commit.
