### ISSUE TITLE
Fix links to screenshots

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk4-rs#317]
In the latest version of GTK4's docs, links to screenshots of widgets were added.
For `Button` this looks like this
```markdown
![An example GtkButton](button.png)
```
The images are stored [here](https://gitlab.gnome.org/GNOME/gtk/-/tree/master/docs/reference/gtk/images)

If we would store them somewhere and the publish them in the CI, we could make use of them as well.

**Comment by bilelmoussaoui** [comment]
Oh that's even simpler to do I guess, we can just grab them from gtk's source tree i guess. But it would be so inefficient to fetch the whole gtk repository every time just for them.

**Comment by bilelmoussaoui** [comment]
Also we probably don't need all those images

**Comment by Hofer-Julian** [comment]
Maybe like this?
https://stackoverflow.com/a/60729017
