### ISSUE TITLE
TreeModelExtManual::get should return the requested type

### ISSUE THREAD

**Issue by mehmooda** [gtk-rs/gtk4-rs#332]
Currently `TreeModelExtManual::get` returns  a glib::Value. And you are required to use `glib::Value::get()` to convert it to a requested type. 

This leads to the unsightly:

```rust
let value: i32 = treemodel.get(column, iter).get().unwrap()
```

It would be nice if you could just write:
```rust
let value: i32 = treemodel.get(column, iter).unwrap()
```

Other possible places to allow conversion to requested type:
- `DropTarget::value`
- `ConstantExpression::value`
- `CellAreaExtManual::cell_get` (should this have been renamed to cell or get?
- `Expression::evaluate`
- `ObjectExt::property`
- ...

**Comment by bilelmoussaoui** [comment]
The method signature could be changed to `TreeModelExt::get<T: ValueType>(...) -> T` then instead of doing `glib::Value::uninitialized` , we would call `glib::Value::for_value_type<T>()`; & then return `value.get::<T>().expect("Invalid value type")`

**Comment by bilelmoussaoui** [comment]
The ObjectExt::property should be handled on glib's side

**Comment by mehmooda** [comment]
There should probably be a impl ValueType for glib::Value in glib. Or an equivalent trait. To allow someone to:
```rust
let value: Value = ...
```

**Comment by bilelmoussaoui** [comment]
I think i covered all of them, please open an issue if I missed any
