### ISSUE TITLE
gdk::ContentFormats::mime_types() return useless size value

### ISSUE THREAD

**Issue by elmarco** [gtk-rs/gtk4-rs#334]
The method `pub fn mime_types(&self) -> (Vec<glib::GString>, usize)` return value isn't great, the extra usize should be ignored. I don't know how to do that with Gir.toml, perhaps a manual binding needed.

**Comment by sdroege** [comment]
It needs a proper annotation in C code. The `n_mime_types` parameter should be annotated to be the length of the return value.

**Comment by bilelmoussaoui** [comment]
I would open an issue/send a PR upstream to fix the annotation and do bind the function manually for now
