### ISSUE TITLE
Merge gtk4 crates

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#34]
Currently there's the following gtk4 specific crates
- gtk4/gtk4-sys
- gdk4/gdk4-sys
- gsk4/gsk4-sys
- gdk4x11/gdk4x11-sys (to be generated)
- gdk4wayland/gdk4wayland-sys (to be generated)
- examples4

As the other sys crates are moving to gtk-rs, we will probably need to move the 3 first sys crates to their individual repositories. Along with the creation of two new repositories to handle the missing bindings.

What I suggest: 

Migrate all the gtk4 repositories into this one (if possible), the same way it was handled for gtk3. Both repositories could be merged later in the future once they are "ready" (as in gtk-rs & gtk4-rs?)
 

The benefits: 
- Regenerating the bindings for a new gtk4 release would be much easier than having to check the status in 6 (once all created) repositories 
- Simplify maintaince

cc @sdroege @GuillaumeGomez

**Comment by bilelmoussaoui** [comment]
cc @BrainBlasted @sophie-h @kavanmevada  
As gtk4-rs contributors, would such change simplify things for you?

**Comment by GuillaumeGomez** [comment]
So, I basically agree on merging all the gtk4 repositories into one, however I just wonder about one thing: do we want to merge them in a separate repository or in the `gtk-rs` one? I have a personal preference over keeping them both separate, but not sure what you prefer?

**Comment by bilelmoussaoui** [comment]
I tend to prefer keeping them separate as well

**Comment by sophie-h** [comment]
> As gtk4-rs contributors, would such change simplify things for you?

I think especially having the examples with the code might reduce the number of 'coordinated PRs,' which might be annoying while things are moving faster.

**Comment by bilelmoussaoui** [comment]
Now that the different crates are merged together. Can someone update the repository name to gtk4-rs? This we can close this one I guess. Unless there's something else we should handle?

**Comment by sdroege** [comment]
> Now that the different crates are merged together. Can someone update the repository name to gtk4-rs?

@GuillaumeGomez ?

**Comment by GuillaumeGomez** [comment]
Done! Thanks a lot for your work on the merge @bilelmoussaoui !

**Comment by bilelmoussaoui** [comment]
Thanks! I think we can close this then
