### ISSUE TITLE
docs: Not re-exporting traits from root breaks docs?

### ISSUE THREAD

**Issue by sophie-h** [gtk-rs/gtk4-rs#348]
For example in https://gtk-rs.org/gtk4-rs/git/docs/gtk4/struct.SortListModel.html the link `[trait@gio::ListModelExt]` can no longer resolved. Which makes sense because it no longer exists since gtk-rs/gtk-rs#487.

**Comment by bilelmoussaoui** [comment]
It's an issue we should resolve in gir, see https://github.com/gtk-rs/gir/pull/1119

**Comment by MarijnS95** [comment]
I'm pushing the correct fix in ~10 minutes :)

**Comment by sophie-h** [comment]
Oh, sorry, I should have checked gir

**Comment by MarijnS95** [comment]
@sophie-h Can you check if the linked PR fixes the issue for the broken link(s) you came across?

**Comment by bilelmoussaoui** [comment]
I will go ahead and close this as there's a PR to fix it on gir side already
