### ISSUE TITLE
Make regen checker job test the commit id

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#352]
In the past, the commit id was used in the automatically generated code which made the regen checker job to fail in case a commit from a fork was used. As that's not used anymore, the job doesn't catch such mistakes and we should figure out another way to do that.

**Comment by bilelmoussaoui** [comment]
cc @MarijnS95, any ideas how we can do such thing?

**Comment by MarijnS95** [comment]
@bilelmoussaoui The generator still puts the hash in [`versions.txt`](https://github.com/gtk-rs/gtk4-rs/blob/master/gdk4/src/auto/versions.txt) right?

This only protects against situations where the submodule hash changed but generated code wasn't updated, or vice-versa. I don't think there's a way to prevent against fork commits unless you add some logic that checks if the recorded submodule hash in git is an ancestor of `gir`'s `master` branch.

**Comment by bilelmoussaoui** [comment]
This is no longer needed
