### ISSUE TITLE
Port C examples

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#36]
It would be nice to port most if not all the examples in the upstream gtk repository to Rust as a replacement of the current examples that are mostly a copy paste of the gtk3 ones.

**Comment by grantshandy** [comment]
I can do this, the upstream C `gtk` examples are fairly simple.

Some are formatted like a guide, (`application1`-`application9`), and I will place these in their own directory, each file is a separate bin. I will also add the upstream `README` files from each directory and add screenshots like the other examples.

I don't have much time to do this, so it may take around a week and a half to complete.

**Comment by bilelmoussaoui** [comment]
@grantshandy Thanks for having a look at this! I would rather port one example after another to simplify the review process for us and we can get them merged much sooner.

**Comment by grantshandy** [comment]
Sure that sounds great, I'll have each one as a separate pull request.

**Comment by bilelmoussaoui** [comment]
Perfect! let me know if I can help somehow :)

**Comment by mairacanal** [comment]
Hi! I have interest in working on this task, but I have a couple of questions. Is there interest in porting the application* examples? Also, examples such as `basics` are called `hello-world` on the C repo, should I rename them to make them more similar to the C examples?

I am excited to get to work on this, thanks!

**Comment by Hofer-Julian** [comment]
@mairacanal great that you want to look into this.

> Also, examples such as basics are called hello-world on the C repo, should I rename them to make them more similar to the C examples?

IMO there is no need to change existing names to be closer to the GTK ones

>  Is there interest in porting the application* examples? 

Any example that is concise and isn't already covered by existing examples would be good to port.

**Comment by bilelmoussaoui** [comment]
I think we are doing quiet good in terms of examples nowadays, more are always welcome though. But the main purpose of this issue is no longer that relevant so closing it.
