### ISSUE TITLE
show_about_dialog doesn't do what the real one does

### ISSUE THREAD

**Issue by YaLTeR** [gtk-rs/gtk4-rs#368]
This cost me some debugging time because I didn't realize gtk4-rs implemented its own `show_about_dialog`, but the [real function](https://gitlab.gnome.org/GNOME/gtk/-/blob/dc878f24d2e26af542abca2289fea63f2c96e68e/gtk/gtkaboutdialog.c#L2210) also does things like:
- correctly set modal = TRUE
- set destroy with parent
- cache the dialog instead of re-creating it every time

**Comment by sdroege** [comment]
> I didn't realize gtk4-rs implemented its own `show_about_dialog`

That's because the C functions uses varargs, and that's not something that can be autogenerated for the bindings.

> , but the [real function](https://gitlab.gnome.org/GNOME/gtk/-/blob/dc878f24d2e26af542abca2289fea63f2c96e68e/gtk/gtkaboutdialog.c#L2210) also does things like:

That on the other hand should be fixed. CC @bilelmoussaoui :)

**Comment by bilelmoussaoui** [comment]
> cache the dialog instead of re-creating it every time

is that actually really needed? doesn't sound super useful

**Comment by YaLTeR** [comment]
> is that actually really needed? doesn't sound super useful

I agree, although there's also an argument to be made here about silently replacing an implementation that's documented to do a thing with one that doesn't do it. I could imagine relying on this particular property by associating the about dialog with something or setting some key value on it (can't gobject do something like this) once, then expecting to have the same object throughout the program lifetime.

**Comment by bilelmoussaoui** [comment]
I have opened a PR that should make the function's behaviour much closer to the upstream one minus one little thing: 
- We don't store the about dialog in a global static if no parent is passed.
