### ISSUE TITLE
FileChooserDialog focus go on search instead of filename field when used as save dialog

### ISSUE THREAD

**Issue by IvanArsenault** [gtk-rs/gtk4-rs#382]
Hi,
    in my project I actually use gtk4-rs from git with all gtk4.2 stuff installed in /usr/local/*. My program compile and work like I wan't except the FileChooserDialog in save mode alway focus on search when I try to write the file name.

My code for FileChooseDialog look like this :    

...  
  action!(
        action_group,
        "save",
        clone!(@weak window, @weak settings => move |_action, _parameter| {

            let file_chooser = FileChooserDialog::new(
                Some("Save File"),
                Some(&window),
                FileChooserAction::Save,
                &[("Save", ResponseType::Ok), ("Cancel", ResponseType::Cancel)],
            );
            file_chooser.set_current_name("Untitled");

            // File Chooser response call back
            file_chooser.connect_response(move |fcd: &FileChooserDialog, response: ResponseType| {
                if response == ResponseType::Ok {
                    let file = fcd.file().expect("Couldn't get file");
                    let filename = file.path().expect("Couldn't get file path");

                    // Construct de ini file to save actual settings values on a file
                    let mut ini_conf = Ini::new();
                    ini_conf.with_section(Some(" 
                           .... // blabla code to save file in ini format
                }

                fcd.close();
            });

            file_chooser.show();
        })
    );
...

Do I do something bad ?

Any idea !

Thank you

Ivan

![focus_on_search_not_filename](https://user-images.githubusercontent.com/54188109/118729363-c84f8780-b803-11eb-9674-a926e03dfdcb.png)

**Comment by bilelmoussaoui** [comment]
Not a binding issue. Please open an issue at https://gitlab.gnome.org/GNOME/gtk/

**Comment by IvanArsenault** [comment]
Issue created : https://gitlab.gnome.org/GNOME/gtk/-/issues/3962

**Comment by IvanArsenault** [comment]
Hi,  find my problem read my last comment there :  https://gitlab.gnome.org/GNOME/gtk/-/issues/2638
