### ISSUE TITLE
gtk4::init() immediately panics unconditionally

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk4-rs#389]
Assuming the docs are correct, the gtk4::init() can be used to initialize a GTK app. However it just panics on my system and does so unconditionally.

My system: Ubuntu 21.04 with gtk4 4.0.3-4 and rustc 1.52.1

Code to reproduce:
```rust
fn main() {
  gtk4::init().unwrap();
}
```

Cargo.toml:
```toml
[dependencies]
gtk4 = { git = " https://github.com/gtk-rs/gtk4-rs" }
```

Output:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to acquire default main context", filename: "/home/aaron/.cargo/git/checkouts/gtk4-rs-e74ad56283dfeb5e/8d674b0/gtk4/src/rt.rs", function: "gtk4::rt", line: 104 }', src/main.rs:2:16
```

Interestingly, the [example](https://gtk-rs.org/gtk4-rs/git/docs/gtk4/index.html#the-main-loop) provided in the docs did work correctly on my system (btw. `gtk` needs to be replaced with `gtk4` there). (However, creating a gtk4::Application myself did also crash despite the application being created before any widgets. Yet, I don't know why this happened so let's focus on this issue first)

**Comment by bilelmoussaoui** [comment]
yes, that comes from the change in https://github.com/gtk-rs/gtk4-rs/commit/7e61f5919f343dc17bf3a24393f8098b286733c9 no idea why the examples works fine though :/

**Comment by bilelmoussaoui** [comment]
you can work around it by adding `glib::MainContext::default().acquire()` before the `gtk::init()` call

**Comment by bilelmoussaoui** [comment]
>  (btw. gtk needs to be replaced with gtk4 there). 
No, the docs explains that it expects you to rename the gtk4 to gtk in your Cargo.toml

**Comment by sdroege** [comment]
> no idea why the examples works fine though

The examples use `GtkApplication` instead of `gtk::init`, that's why.
