### ISSUE TITLE
Move licence of book content

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk4-rs#399]
Fedora moved to CC BY-SA 4.0.
The reasons seem reasonable to me, so I propose to switch to it as well.
Context: https://communityblog.fedoraproject.org/policy-proposal-update-default-content-license-to-cc-by-sa-4-0/

Ping @sdroege & @bilelmoussaoui

**Comment by sdroege** [comment]
Works for me, just make sure that the code stays MIT or BSD.

**Comment by bilelmoussaoui** [comment]
Works for me as well (a bit later as I already merged the change :P)
