### ISSUE TITLE
don't use a macro for glib::wrapper

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#414]
we use a macro to define fundemental types such as `gdk::Event`/`gsk::RenderNode`/`gtk::Expression`, by doing so, `rustdoc-stripper` cannot find `glib::wrapper` call to re-add the docs to the right place. Which means we lose the documentation of such items.

Instead, we should move the glib::wrapper call outside of those macros. A bit of code duplication is okay if at the same price we get more complete docs.

**Comment by bilelmoussaoui** [comment]
We define this part
```
glib::wrapper! {
            #[derive(Debug)]
            pub struct $rust_type(Shared<$ffi_type>);

            match fn {
                ref => |ptr| ffi::gtk_expression_ref(ptr as *mut ffi::GtkExpression) as *mut $ffi_type,
                unref => |ptr| ffi::gtk_expression_unref(ptr as *mut ffi::GtkExpression),
            }
        }
```
manually for each type, and use the macro just to implement the various traits.

**Comment by sdroege** [comment]
Oh I see. Yes that makes sense.
