### ISSUE TITLE
Getting warning implementing ObjectSubclass

### ISSUE THREAD

**Issue by Umenokin** [gtk-rs/gtk4-rs#442]
Hi everyone,

I am new to the rust and trying to play around with gtk4-rs.

I subclassed the ApplicationWindow. Everything is compiling but `impl ObjectSubclass for TestWindow {` is showing an error:

> 
> Not all trait items implemented, missing: `Interfaces`, `Instance`, `Class` [E0046] 
> the trait bound `TestWindow: ObjectSubclassType` is not satisfied [E0277] the trait `ObjectSubclassType` is not implemented for `TestWindow`

> The central trait for subclassing a GObject type.
> Links together the type name, parent type and the instance and class structs for type registration and allows subclasses to hook into various steps of the type registration and initialization.
> See register_type for registering an implementation of this trait with the type system.
> 

Below is the code snippet, but again, this code is compiling successfully and I can see this error only in IDE (IntelJ)

```
// imp
#[derive(Default)]
pub struct TestWindow;

#[glib::object_subclass]
impl ObjectSubclass for TestWindow {
    const NAME: &'static str = "MyGtkAppTestWindow";
    type Type = super::TestWindow;
    type ParentType = gtk::ApplicationWindow;
}

impl ObjectImpl for TestWindow {

    fn constructed(&self, obj: &Self::Type) {
        self.parent_constructed(obj);
        obj.set_title(Some("First GTK Program"));
        obj.set_default_size(350, 70);

        let button = gtk::Button::with_label("Click me!");

        button.connect_clicked(|_| {
            std::process::exit(0);
        });

        obj.set_child(Some(&button));
    }
}

impl WidgetImpl for TestWindow {}

impl WindowImpl for TestWindow {}

impl ApplicationWindowImpl for TestWindow {}

```

```
mod imp;

use glib::Object;
use gtk::{glib, Application};
use glib::object::IsA;

glib::wrapper! {
    pub struct TestWindow(ObjectSubclass<imp::TestWindow>)
        @extends gtk::ApplicationWindow, gtk::Window, gtk::Widget;
}

impl TestWindow {
    pub fn new<P: IsA<Application>>(application: &P) -> Self {
        let window: TestWindow = Object::new(&[("application", &application)])
            .expect("Failed to create TestWindow");

        window
    }
}

impl Default for TestWindow {
    fn default() -> Self {
        panic!("Application instance must be provided");
    }
}
```

Would be great, if someone could help me.
Thanks!

**Comment by bilelmoussaoui** [comment]
That's probably a limitation of the Intellij's Rust integration where it can't detect optional associated types. I don't reproduce that here with VSCode & Rust Analyzer

**Comment by Umenokin** [comment]
Thank you @bilelmoussaoui ! Glad to know it is an IDE issue

**Comment by bilelmoussaoui** [comment]
There's nothing we can do here, you won't notice the issue once Intellij's Rust integrations supports macros properly.
