### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Umenokin** [gtk-rs/gtk4-rs#454]
I was not able to properly configure gtk with installation instructions from the book.

Could be it is outdated instructions?
```
[dependencies.gtk]
version = "0.1"
package = "gtk4"
```

I do not remember the message I got a few weeks ago, but if I would try it now I will get:
```
candidate versions found which didn't match: 0.0.0
location searched: crates.io index
```

Setting version to 0.9.2 would not work as well.

I was able to make it work if I will point git repo directly. This one I steal from examples:
```
[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk4-rs"
package = "gtk4"
```

**Comment by Hofer-Julian** [comment]
The instructions will work when gtk4-rs is released in a week 😊
