### ISSUE TITLE
gtk4::Dialog set_current_folder is not taking a Path as an argument

### ISSUE THREAD

**Issue by A6GibKm** [gtk-rs/gtk4-rs#455]
**Bug description**

set_current_folder used to take a Path as an argument, now it only accepts a gio::File, e.g. 

```rust
        let xdg_pictures_dir = glib::user_special_dir(glib::UserDirectory::Pictures);
        let gxdg_pictures_dir = gio::File::for_path(&xdg_pictures_dir);
        dialog.set_current_folder(&gxdg_pictures_dir);
```

The original code in gtk-rs was

```rust
        let xdg_pictures_dir = glib::get_user_special_dir(glib::UserDirectory::Pictures);
        dialog.set_current_folder(&xdg_pictures_dir);
```

**Comment by bilelmoussaoui** [comment]
Per the gtk4 docs, it seems to actually take a GFile https://docs.gtk.org/gtk4/method.FileChooser.set_current_folder.html so I assume it's supposed to be used like this. Sorry for asking you to open an issue before checking whether it makes sense before.
