### ISSUE TITLE
Improve book documentation of gobject macros

### ISSUE THREAD

**Issue by blackwolf12333** [gtk-rs/gtk4-rs#483]
I just finished reading the available book chapters. The main thing that seemed unclear to me were the macros used for creating gobjects and types and such. They seem a bit magical and are mostly glossed over. I think it would be useful to have a chapter dedicated to explaining what they do, maybe also for people who are completely new to GTK/GObject.

So depending on what you guys consider in scope for the book project, I think the following would be nice to have:

1. An explanation of the GObject type system
2. An explanation how the macros in the glib crate allow you to define your own types
3. Some kind of reference where the syntax and allowed options of those macros are explained.

It looks like there is some reference documentation in the actual docs, so you can probably link to that as well.

**Comment by Hofer-Julian** [comment]
Thanks @blackwolf12333 for opening the issue.

>  An explanation of the GObject type system

Could you please be more specific where you would like the book to be more elaborate.

> An explanation how the macros in the glib crate allow you to define your own types

We do have the [subclassing](https://gtk-rs.org/gtk4-rs/stable/latest/book/gobject_subclassing.html) which is the way to create custom GObjects. Or do you mean something else?

> Some kind of reference where the syntax and allowed options of those macros are explained.

Agreed.
We should
1. Link to [`glib::wrapper!`](https://gtk-rs.org/gtk-rs-core/stable/latest/docs/glib/macro.wrapper.html)
2. Explain the options a bit more in the book

**Comment by blackwolf12333** [comment]
> Could you please be more specific where you would like the book to be more elaborate.

I'm not really sure how important this is for rust, but my limited experience with GObject in C tells me there is quite a bit of "magic" going on under the hood in C with macros that ensure the GObject "type system" works correctly with different language bindings. To be honest, I really don't know or understand much of what happens in C land so whatever I'm saying might not make a lot of sense to anyone.

So maybe what I'm wondering about is how gobject introspection works with rust? There's a lot of unknown unknown about this request for more documentation to be completely honest.

> We do have the subclassing which is the way to create custom GObjects. Or do you mean something else?

I don't know if this is possible at all from rust yet, but if it is, also include something about creating gobject interfaces for instance?

**Comment by sdroege** [comment]
> So maybe what I'm wondering about is how gobject introspection works with rust?

The bindings are autogenerated (to some degree) from the gobject-introspection data of the C libraries, if that's what you mean. The macros for creating the GObject subclasses don't really do much magic but reduce the amount of boring code you'd have to otherwise write yourself. Especially the `glib::object_subclass` macro is really boring (it does exactly what is written in its docs, nothing else). `glib::wrapper!` is a bit more elaborate and implements lots of (safe and unsafe) traits so your objects behave like the ones from the bindings.

> I don't know if this is possible at all from rust yet, but if it is, also include something about creating gobject interfaces for instance?

Implementing an interface or creating a new interface? Both is possible, but the latter is not as nice as it could be API-wise yet.

**Comment by bilelmoussaoui** [comment]
I suppose this is somehow related to https://github.com/gtk-rs/gtk-rs-core/issues/52?

**Comment by blackwolf12333** [comment]
I think the documentation improved a lot, I'll close this :)
