### ISSUE TITLE
gtk4-sys: test-failed in fedora copr

### ISSUE THREAD

**Issue by remilauzier** [gtk-rs/gtk4-rs#488]
**Bug description**
https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-x86_64/02306636-rust-gtk4-sys/builder-live.log.gz

In file included from tests/constant.c:5:
tests/manual.h:3:10: fatal error: gtk/gtk-a11y.h: No such file or directory
    3 | #include <gtk/gtk-a11y.h>
      |          ^~~~~~~~~~~~~~~~
In file included from tests/layout.c:5:
tests/manual.h:3:10: fatal error: gtk/gtk-a11y.h: No such file or directory
    3 | #include <gtk/gtk-a11y.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
test cross_validate_layout_with_c ... FAILED
compilation terminated.
test cross_validate_constants_with_c ... FAILED

**Comment by bilelmoussaoui** [comment]
They are disabled upstream as well and probably a gtk issue, see https://github.com/gtk-rs/gtk4-rs/issues/39
