### ISSUE TITLE
gtk4-macros: test failed on fedora copr

### ISSUE THREAD

**Issue by remilauzier** [gtk-rs/gtk4-rs#489]
**Bug description**
https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-x86_64/02306658-rust-gtk4-macros/builder-live.log.gz

error[E0433]: failed to resolve: use of undeclared crate or module `gtk`
 --> src/lib.rs:35:5
  |
3 | use gtk::prelude::*;
  |     ^^^ use of undeclared crate or module `gtk`

**Comment by bilelmoussaoui** [comment]
gtk is definitely included as a test package here https://github.com/gtk-rs/gtk4-rs/blob/0.1/gtk4-macros/Cargo.toml#L28 and the tests succeeds just fine on the CI

**Comment by bilelmoussaoui** [comment]
Looks to me like whatever fedora uses to fetch the dependencies before running the tests inside the sandbox, ignores the dev-dependencies.

**Comment by remilauzier** [comment]
Fedora build in offline mode only. Maybe that the problem.

**Comment by bilelmoussaoui** [comment]
It's a test dependency, it should be downloaded; anyway, not an issue on our side.
