### ISSUE TITLE
error: failed to run custom build command for `glib-sys v0.14.0`

### ISSUE THREAD

**Issue by BrandonLeeDotDev** [gtk-rs/gtk4-rs#508]
Compiling glib-sys v0.14.0
The following warnings were emitted during compilation:

warning: `"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.66"` did not exit successfully: exit status: 1

error: failed to run custom build command for `glib-sys v0.14.0`

Caused by:
  process didn't exit successfully: `/home/user/Documents/gui/target/debug/build/glib-sys-d81651d6e7791f4f/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=GLIB_2.0_STATIC
  cargo:rerun-if-env-changed=GLIB_2.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:warning=`"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.66"` did not exit successfully: exit status: 1
  --- stderr
  Requested 'glib-2.0 >= 2.66' but version of GLib is 2.64.6

**Comment by bilelmoussaoui** [comment]
You need newer glib on your system. 2.66 is required compared to what you have installed 2.64 on your machine.

**Comment by sdroege** [comment]
Note that the minimum version required for the GLib bindings is 2.48 but you can opt-in to newer APIs via the `v2_66` etc cargo features. GTK4 requires at least GLib 2.66 and that's where this requirement here comes from.
