### ISSUE TITLE
[BUG] Window resizing, from the corner resize handle, crashes on Windows 10, but not in Linux (Pop!_OS)

### ISSUE THREAD

**Issue by Nejat** [gtk-rs/gtk4-rs#522]
**Bug description**

Working with any of the examples in this project, when I resize width and height simultaneously, by the corner resize handle, the program crashes. 

It has been 100% repeatable.

This only happens on Windows 10, but not Linux (running on metal, not VM).

And it only happens when both dimensions are being resized simultaneously.
I have not been able to crash a program with either vertical or horizontal only resizing from the edge.

**Environment**

```
installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-gnu
nightly-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-pc-windows-gnu

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.53.0 (53cb7b09b 2021-06-17)
```

**Code Sample**

[Clipboard Example](https://github.com/gtk-rs/gtk4-rs/tree/master/examples/clipboard)

**Backtrace**

Even with the environment variable `RUST_BACKTRACE=full`, I only get the following output ...

```
(clipboard.exe:35976): GLib-GIO-WARNING **: 22:00:35.173: Unexpectedly, UWP app `draw.io.draw.ioDiagrams_14.6.13.0_x64__1zh33159kp73c' (AUMId `draw.io.draw.ioDiagrams_1zh33159kp73c!draw.io.draw.ioDiagrams') supports 2 extensions but has no verbs
error: process didn't exit successfully: `target\debug\clipboard.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

\* _Incidentally, the_ ```GLib-GIO-WARNING``` _listed above always outputs, whether the application crashes or not_

**Comment by bilelmoussaoui** [comment]
Looks like an upstream issue that be reported to GTK directly.

**Comment by Nejat** [comment]
I just verified this by building Gtk 4.3.1, 4.2.1 & 4.2.0 from source on Windows and running the C examples and demos.

The demos, examples and tests I checked all exhibited the same behavior, in all three versions. 

GTK4 on windows feels unstable, which is unfortunate.

**Comment by Nejat** [comment]
btw, I reported the problem upstream

**Comment by bilelmoussaoui** [comment]
Thanks !
