### ISSUE TITLE
[FEATURE REQUEST] MacOS integration

### ISSUE THREAD

**Issue by Serentty** [gtk-rs/gtk4-rs#528]
It seems like the bindings for `GtkOsxApplication` are missing.

**Comment by bilelmoussaoui** [comment]
we already have an issue for the missing parts in gdk at #520; so let's limit this one to gtk only.

**Comment by bilelmoussaoui** [comment]
I'm going to go ahead and close this, if you find some macos specific functions/features that are missing please open a specific issue. There's nothing actionable on this one. See also #520
