### ISSUE TITLE
[FEATURE REQUEST] Implement a set_margin_all method for WidgetExt

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk4-rs#539]
I often use the same margins for my widgets and find using the methods in `WidgetExt` rather repetitive. To reduce redundant code I'd like to have a method `set_margin_all()` that sets all margins at once. 

This would reduce this code:

```rust
let margin = 10;
widget.set_margin_bottom(margin);
widget.set_margin_end(margin);
widget.set_margin_start(margin);
widget.set_margin_top(margin);
```

to just one line:

```rust
widget.set_margin_all(10);
```

Maybe there's already a solution for this I'm not aware of and of course I could just implement my own trait for this but I think this could be useful for others, too.

**Comment by bilelmoussaoui** [comment]
Upstream removed such method in GTK 4. I don't see why we should do it here.

**Comment by bilelmoussaoui** [comment]
Well to be more precise, before there used to be a property margin other than the other specific margin ones which was confusing. I would open an issue upstream asking for providing such helper method if possible

**Comment by AaronErhardt** [comment]
Upstream doesn't want this feature, so I'm closing this issue as well: [https://gitlab.gnome.org/GNOME/gtk/-/issues/4145](https://gitlab.gnome.org/GNOME/gtk/-/issues/4145).
