### ISSUE TITLE
Collect gtk3-rs -> gtk4-rs migrations patches

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#54]
Would be nice to have a list of PR/MR of each application that migrated from gtk3-rs to gtk4-rs somehow here 

cc @BrainBlasted

**Comment by sophie-h** [comment]
- https://gitlab.gnome.org/World/pika-backup/-/merge_requests/34

(It's possible that I will redo the migration. This is to check if something is missing in gtk4-rs.)

**Comment by sdroege** [comment]
Isn't this the same as https://github.com/gtk-rs/gtk4-rs/issues/33 ?

**Comment by JAicewizard** [comment]
* https://github.com/JAicewizard/druid/pull/14

This has not yet made it upstream, and might never. Also not complete, since the druid-shell API doesnt really fit GTK4/wayland so some things dont work properly/only in common cases.

**Comment by bilelmoussaoui** [comment]
Closing this one as we didn't had much success collection these patches and most of the famous gtk-rs apps were ported to gtk4 already.
