### ISSUE TITLE
[BUG] Wrong type signature in gtk::Expression::bind (maybe?)

### ISSUE THREAD

**Issue by aledomu** [gtk-rs/gtk4-rs#551]
**Bug description**

Right now the signature of the method `gtk::Expression::bind` is as follows:

```rust
pub fn bind<T: IsA<Object>>(&self, target: &T, property_name: &str, this: Option<&T>) -> ExpressionWatch
```

I'd expect that the `target` and `this` objects are most of the time of different types. Because of the single generic type common to both objects, they have to be upcast to a common parent (usually `glib::Object`). My intuition tells me that there should be two different generic types declared with the same constraints for each argument.

**Comment by sdroege** [comment]
Yes, this should have two generic types. Do you want to submit a PR?

**Comment by aledomu** [comment]
Thanks!
