### ISSUE TITLE
[HELP]fields of subclasses

### ISSUE THREAD

**Issue by peter-jerry-ye** [gtk-rs/gtk4-rs#557]
Hello,

I'm new to rust and gtk-rs and during my exploration, I encountered a problem.

If a define my subclass in `imp.rs` such as:
```rust
#[derive(Default)]
pub struct CustomButton {
    pub number: Cell<i32>,
}
```
and I'd like to use it somewhere in some other function I'd define for the `CustomButton`, for example, in file `mod.rs`:
```rust
glib::wrapper! {
    pub struct CustomButton(ObjectSubclass<imp::CustomButton>)
        @extends gtk::Button, gtk::Widget;
}

impl CustomButton {
    pub fn get_count(&self) -> i32 {
        self.number.get()
    }
}
```
which would give me an error saying that

> available fields are: `0`

Is that the expected behavior? Is there any way I can retrieve the value inside the struct?

Thanks.

**Comment by sdroege** [comment]
> Is there any way I can retrieve the value inside the struct?

Yes, via [`ObjectSubclass::from_instance`](https://gtk-rs.org/gtk-rs-core/git/docs/glib/subclass/types/trait.ObjectSubclassExt.html#tymethod.from_instance), see e.g.

https://github.com/gtk-rs/gtk4-rs/blob/9540e4dd72e1fa8a99bb519b3518b52ce65fa221/examples/composite_template/ex_application_window/mod.rs#L16-L23
