### ISSUE TITLE
Documentation for Widget is cut off

### ISSUE THREAD

**Issue by mahkoh** [gtk-rs/gtk4-rs#560]
https://gtk-rs.org/gtk4-rs/stable/0.2/docs/gtk4/struct.Widget.html

Scroll to the bottom.

I believe the same holds for gtk3.

![2021-08-28-204750_974x253_scrot](https://user-images.githubusercontent.com/1882250/131227914-8f60bcf1-902a-4c78-91a2-9204717ff090.png)

**Comment by bilelmoussaoui** [comment]
It's a known issue and is already opened against gtk-rs/gir

**Comment by sdroege** [comment]
That's https://github.com/gtk-rs/gir/issues/1200 from what I can see.
