### ISSUE TITLE
[HELP] Is it possible to build a static linked binary?

### ISSUE THREAD

**Issue by AllenDang** [gtk-rs/gtk4-rs#563]
Is it possible to use this crate to create a statically linked binary? 

I googled agains `gtk4-rs static build`, not much information there.

**Comment by sdroege** [comment]
It's not possible to statically link GTK, the C library. For bundling everything together with your application it's best to use whatever mechanism your target OS has available: .app on macOS, Flatpak/Snap/AppImage on Linux, etc.

**Comment by whitequark** [comment]
What mechanism should one use on Windows?

**Comment by nirbheek** [comment]
> What mechanism should one use on Windows?

There is nothing gtk-specific to answer regarding this, you would bundle DLLs with your app like every other app does on Windows :)
