### ISSUE TITLE
[BUG] Keeping data alive via object data is unsound

### ISSUE THREAD

**Issue by mahkoh** [gtk-rs/gtk4-rs#567]
In many cases where GTK apis require the callee to hold on to the returned pointer, gtk4-rs uses `g_object_set_qdata` to store a copy of the data so that it sticks around long enough. For example

https://github.com/gtk-rs/gtk4-rs/blob/fb59005041d06bc275de3ff23a740395b6332c1e/gtk4/src/subclass/entry_buffer.rs#L234-L238

However, this is only sound as long as this code path is not taken again until the caller stops using the returned data. In the following example, I subclass `EntryBuffer` to cause the pointer returned by `gtk_entry_buffer_get_text` to become invalid:

```rust
use imp::EbImp;
use gtk4::subclass::prelude::*;
use gtk4::prelude::*;

mod imp {
    #[derive(Default)]
    pub struct EbImp;
}

#[gtk4::glib::object_subclass]
impl ObjectSubclass for EbImp {
    const NAME: &'static str = "EbImp";
    type Type = Eb;
    type ParentType = gtk4::EntryBuffer;
    type Interfaces = ();
}

glib::wrapper! {
    pub struct Eb(ObjectSubclass<EbImp>) @extends gtk4::EntryBuffer;
}

impl ObjectImpl for EbImp {}

impl EntryBufferImpl for EbImp {
    fn length(&self, entry_buffer: &Self::Type) -> u32 {
        let _ = entry_buffer.text(); // invalidate the previous pointer returned by get_text
        self.parent_length(entry_buffer)
    }
}
```

In the following code path, gtk calls `get_text` immediately followed by `get_length`:

https://github.com/GNOME/gtk/blob/8550a04bf42f5e1d8af239ab953c3ff1235dc149/gtk/gtktext.c#L2140-L2141

The call to `get_length` invalidates the pointer returned by `get_text`.

This is currently masked by https://github.com/gtk-rs/gtk4-rs/issues/564

**Comment by sdroege** [comment]
Indeed. This seems hard to fix nicely, it seems like a fundamental limitation of the underlying C API (i.e. https://github.com/gtk-rs/gtk3-rs/issues/333) by using `transfer none` return values and keeping it up to the caller and interface implementer to implement complicated lifetime rules that are rarely even documented.

From the Rust bindings side we have the conflicting requirements here to keep the pointer to the C string of the text alive "long enough" while also allowing other trait functions to be called that might invalidate the returned pointer. In this case, if the requirement is only that `length()` must not be able to invalidate the pointer, a potential solution would be to combine the `text()` and `length()` functions into a single one and also only updating the qdata if the string actually changed.

If that's enough for other usage patterns from C, I don't know.

Thanks for reporting this!

**Comment by sdroege** [comment]
In that sense, this is the same as https://github.com/gtk-rs/gtk4-rs/issues/566 and I'm going to close the other one.

**Comment by sdroege** [comment]
That's only a solution for this specific case, i.e. https://github.com/gtk-rs/gtk4-rs/issues/567 . For other cases this has to be carefully analyzed and implemented according to the requirements of the C API. If you find other cases that are broken, please report them here. I'm going to close this issue for now, let's fix this instance as part of https://github.com/gtk-rs/gtk4-rs/issues/566 and any other cases that are broken should get separate issues.
