### ISSUE TITLE
[BUG] macOS: No input method support.

### ISSUE THREAD

**Issue by AllenDang** [gtk-rs/gtk4-rs#569]
There is no input method support in any text input widget.

I saw a closed issue for gtk4 here https://gitlab.gnome.org/GNOME/gtk/-/issues/3968

Does that mean upstream gtk4 already got this fixed?

**Comment by sdroege** [comment]
This has nothing to do with the bindings but if anything is a bug in GTK, but as you say it looks (from your rather minimal description) like the problem was fixed there already.
