### ISSUE TITLE
[BUG] List Example cant find SignalListItemItemFactory

### ISSUE THREAD

**Issue by jcbritobr** [gtk-rs/gtk4-rs#573]
In source code, about lists, the struct SignalListItemItemFactory can't be found.

```rust
    let factory = SignalListItemFactory::new();
```

**Comment by sdroege** [comment]
@Hofer-Julian It's missing the `gtk::` like in the actual code in the `examples` directory.

**Comment by Hofer-Julian** [comment]
As discussed with @slomo not a bug, just symbol brought into scope

**Comment by jcbritobr** [comment]
Yep, the issue was in the toml - config file. There was not gtk4 in features section. Put this info in dependencies fix the problem.
