### ISSUE TITLE
[BUG] `Snapshot::push_shadow` has an unsound signature

### ISSUE THREAD

**Issue by mahkoh** [gtk-rs/gtk4-rs#575]
https://github.com/gtk-rs/gtk4-rs/blob/a7b3c61fd95a57a980bf17442e5861f58b32c1ad/gtk4/src/auto/snapshot.rs#L236-L245

`gtk_snapshot_push_shadow` expects an array+length.

**Comment by sdroege** [comment]
Indeed. Do you want to provide a PR for that?

**Comment by sdroege** [comment]
CC @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
I wonder if there's an issue in the introspection annotation as well, something to be checked when fixing this issue manually here for now.

**Comment by sdroege** [comment]
You re-import the .gir files once this is done?

**Comment by bilelmoussaoui** [comment]
> You re-import the .gir files once this is done?

Definitely
