### ISSUE TITLE
Memory leak on texture refresh on windows 10 64, mingw 64 [BUG]

### ISSUE THREAD

**Issue by jcbritobr** [gtk-rs/gtk4-rs#586]
gtk4 - mingw-w64-x86_64-gtk4 4.4.0-3
windows 10 pro 64
rust 1.55 gnu toolchain

Gtk-rs 4 presents memory leaks when gui is repainted(Think is a problem with textures). To reproduce, just needs to resize a simple gtk window. Memory will leak a lot.

![image](https://user-images.githubusercontent.com/6579862/134180923-04fa5aaf-d0e0-42d6-887a-ebbba5468bee.png)

**Comment by bilelmoussaoui** [comment]
What makes you think it's a binding issue ?

**Comment by jcbritobr** [comment]
I'll try build a gtkmm4 example here. I'll post the results here as soon as possible.

**Comment by jcbritobr** [comment]
It happens with gtkmm4 also. Its an issue with gtk4 oficial libraries in windows. I'll close the issue, but it will be usefull have it as a historic here.

![image](https://user-images.githubusercontent.com/6579862/134187813-06d2b1e9-338c-4c2a-8937-844c356ec455.png)

**Comment by bilelmoussaoui** [comment]
Please report the bug to upstream gtk project.

**Comment by sdroege** [comment]
And please put a link here for future reference :)

**Comment by jcbritobr** [comment]
Here is the issue created on gtk project repository.
https://gitlab.gnome.org/GNOME/gtk/-/issues/4307
