### ISSUE TITLE
Issue with gtk TreeListModel create function triggering too often

### ISSUE THREAD

**Issue by njust** [gtk-rs/gtk4-rs#597]
Hi, I have an issue with gtk TreeListModel create function triggering too often:
![tree_expand](https://user-images.githubusercontent.com/2380253/135149564-9c56be57-923f-4747-89d7-aa659ae633eb.gif)

I have a small repro here: https://github.com/njust/tree_view_issue

My TreeListModel code looks like the following:
```rust
    let tree_list_model = gtk4::TreeListModel::new(model, false, false, |obj| {
        if let Some(name) = obj.property("name").ok().and_then(|p|p.get::<String>().ok()) {
            println!("Expand: {}", name);
        }

        let list_store = gio::ListStore::new(PersonObject::static_type());
        let persons = get_persons(5);
        for person in persons {
            list_store.append(&person);
        }
        Some(list_store.upcast::<gio::ListModel>())
    });
```

**Comment by sdroege** [comment]
You probably want to ask this on the [GNOME discourse](https://discourse.gnome.org) as this is more a general GTK support question than anything related to the bindings, and especially not a bug (in the bindings) or a feature request :)
