### ISSUE TITLE
[Book] Wrong action name in comment

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk4-rs#604]
https://github.com/gtk-rs/gtk4-rs/blob/ed840ef06f0aa9a2e7412d4fdd9cac53cfbc976c/book/listings/actions/3/main.rs#L68

This should be `win.count`  I think. @Hofer-Julian

Btw. well done with the chapter :)

**Comment by Hofer-Julian** [comment]
Thanks @AaronErhardt :) 

Wanna open a PR?
