### ISSUE TITLE
Command for meson compile wrong

### ISSUE THREAD

**Issue by jethro-djan** [gtk-rs/gtk4-rs#622]
In this article [Prerequisites](https://gtk-rs.org/gtk4-rs/stable/latest/book/prerequisites.html) here, under **Cargo + Meson** it says the commands to compile and install the application are

> `meson -C builddir && meson install -C builddir`

I think it is supposed to be 

> `meson compile -C builddir && meson install -C builddir`

**Comment by Hofer-Julian** [comment]
Indeed, do you want to open a PR for that @jethro-djan?

**Comment by Hofer-Julian** [comment]
You can click on the small pencil icon next to "blame" here: https://github.com/gtk-rs/gtk4-rs/blob/master/book/src/prerequisites.md

**Comment by jethro-djan** [comment]
I already did I think. Thanks
