### ISSUE TITLE
[BUG] gtk4: test failed on fedora rawhide koji

### ISSUE THREAD

**Issue by remilauzier** [gtk-rs/gtk4-rs#687]
**Bug description**
Not sure why it doesn't work.
https://kojipkgs.fedoraproject.org//work/tasks/4854/78484854/build.log

running 11 tests
thread '<unnamed>' panicked at 'Tests failed to initialize gtk: BoolError { message: "Failed to initialize GTK", filename: "src/rt.rs", function: "gtk4::rt", line: 120 }', src/lib.rs:74:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5

**Comment by bilelmoussaoui** [comment]
The gtk4 tests normally requires gtk to be initialized, so it needs to be run through xvfb. Not sure we can do something about it :) Those tests are meant for CI only

**Comment by bilelmoussaoui** [comment]
I'm going to go ahead and close this as there is nothing to be done form our side, if you want the tests to work, use something like xvfb-run
