### ISSUE TITLE
[FEATURE REQUEST] Add convenience methods for GtkExpressions

### ISSUE THREAD

**Issue by SeaDve** [gtk-rs/gtk4-rs#693]
Something like this:

```rust
let list_item_expression = ConstantExpression::new(list_item);
let integer_object_expression = PropertyExpression::new(
    gtk::ListItem::static_type(),
    Some(&list_item_expression),
    "item",
);
let number_expression = PropertyExpression::new(
    IntegerObject::static_type(),
    Some(&integer_object_expression),
    "number",
);
```

could be shorten into this:
```rust
list_item.property_expression("list-item")
    .property_expression("item")
    .property_expression("number")
```

A possible implementation:
https://github.com/SeaDve/Noteworthy/blob/637f20ec9f4a9d6868f26328d8a8f8c324dd313b/src/utils.rs#L28-L71

**Comment by sdroege** [comment]
@SeaDve Do you want to provide a PR for that? Seems useful to me in principle and it's more efficient to discuss around an actual implementation :)

**Comment by SeaDve** [comment]
Sure

**Comment by SeaDve** [comment]
I gave it a try. Should it be another trait and be included on /gtk4/src/expression.rs ?

**Comment by sdroege** [comment]
If you can implement it without adding a new trait then that would be great, if it needs a new trait then that's just how it is :)

Code should be in `src/expression.rs` or `src/property_expression.rs` / `src/closure_expression.rs` I guess. Wherever it fits best.
