### ISSUE TITLE
[BUG] Broken "resources" link in gtk-rs book

### ISSUE THREAD

**Issue by reed-meyerson** [gtk-rs/gtk4-rs#696]
**Bug description**
The "resources" link in the ["Cargo + Meson"](https://gtk-rs.org/gtk4-rs/stable/latest/book/project_setup.html#cargo--meson) section of the gtk-rs book appears to be broken.

**Comment by bilelmoussaoui** [comment]
Mind sending a PR?

**Comment by Hofer-Julian** [comment]
Ah yes, that link should probably be removed until the chapter is actually written
