### ISSUE TITLE
Cleanup & provide a README for all the crates

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#74]
Currently all the crates either have a very poor README or not at all, we should clean things up before the first release. 
Informations to include:

Documentation links / Crates.io link, C documentation link, a list of features of each crate

**Comment by Susurrus** [comment]
I also ran into an issue with the required Rust version. Because of the use of `#[doc(alias = ...)]`, at least version 1.48 is required. It'd be good to have this specified in the README also.
