### ISSUE TITLE
mac run helloworld err   gtk4-rs:v0.3.1

### ISSUE THREAD

**Issue by lontten** [gtk-rs/gtk4-rs#742]
**Bug description**
macOS 12.0.1
gtk4  4.4
rustc 1.57.0
gtk = { version = "0.3.1", package = "gtk4" }

src  Book-Hello World  : listings/hello_world/2/main.rs

cargo run

bug:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000098
Exception Codes:       0x0000000000000001, 0x0000000000000098
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [79743]

VM Region Info: 0x98 is not in any region.  Bytes before following region: 4371619688
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10491a000-104982000    [  416K] r-x/r-x SM=COW  ...ER/*/untitled

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread

**Comment by sdroege** [comment]
Can you get a backtrace of the crash from a debugger (lldb, gdb)?

**Comment by lontten** [comment]
(lldb) r
Process 83341 launched: '/Users/lontten/demo/untitled/target/debug/untitled' (x86_64)
2021-12-05 00:26:15.219424+0800 untitled[83341:2022440] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=83341
2021-12-05 00:26:15.219496+0800 untitled[83341:2022440] SecTaskCopyDebugDescription: untitled[83341]/0#-1 LF=0
2021-12-05 00:26:15.589107+0800 untitled[83341:2022440] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=83341
2021-12-05 00:26:15.589193+0800 untitled[83341:2022440] SecTaskCopyDebugDescription: untitled[83341]/0#-1 LF=0
Process 83341 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x98)
    frame #0: 0x0000000100e8c782 libgtk-4.1.dylib`gdk_macos_gl_context_real_realize + 402
libgtk-4.1.dylib`gdk_macos_gl_context_real_realize:
->  0x100e8c782 <+402>: movl   0x98(%rcx), %eax
    0x100e8c788 <+408>: movl   %eax, -0x58(%rbp)
    0x100e8c78b <+411>: movl   0x9c(%rcx), %eax
    0x100e8c791 <+417>: movl   %eax, -0x54(%rbp)
Target 0: (untitled) stopped.

**Comment by sdroege** [comment]
That's https://gitlab.gnome.org/GNOME/gtk/-/issues/4279 and was already fixed in GTK: https://gitlab.gnome.org/GNOME/gtk/-/commit/e77eaa0acedd86371d9d81de3982d8657864915d
