### ISSUE TITLE
[HELP] windows build fails (libpangoft2-1.0-0)

### ISSUE THREAD

**Issue by Sillyvan** [gtk-rs/gtk4-rs#749]
Maybe this is an issue for the gnome team im not very sure.

I followed the MSVC toolchain instructions on https://gtk-rs.org/gtk4-rs/git/book/installation_windows.html and no problems there.

now if I try to build any example from this repo I get this error

> Entry Point Not Found
> The procedure entry point hb_ft_face_create could not be located in the dynamic link library C:\gnome\bin\libpangoft2-1.0-0.dll

**Comment by bilelmoussaoui** [comment]
Even the basic example doesn't work?

**Comment by bilelmoussaoui** [comment]
I think pango normally builds harfbuzz as subproject, so it should normally work without any issues

**Comment by Sillyvan** [comment]
yes even the basic exmaple dosent work for me

**Comment by bilelmoussaoui** [comment]
For whatever reason, you ended up with a missing/broken harfbuzz build, so i would recommend trying again otherwise open an issue upstream.
