### ISSUE TITLE
Return a `Result` on `WidgetExt::activate_action` instead of a `bool`.

### ISSUE THREAD

**Issue by SeaDve** [gtk-rs/gtk4-rs#762]
According to [C API reference](https://docs.gtk.org/gtk4/method.Widget.activate_action.html), it would only return false if the action name doesn't exist. User might want it to panic, or be told by the compiler

**Comment by sdroege** [comment]
Do you want to provide a PR? You can configure this in the `Gir.toml` with `bool_return_is_error`

**Comment by SeaDve** [comment]
> Do you want to provide a PR? You can configure this in the `Gir.toml` with `bool_return_is_error`

sure
