### ISSUE TITLE
[BUG] Error when using ActionableExtManual::set_action_target

### ISSUE THREAD

**Issue by zecakeh** [gtk-rs/gtk4-rs#767]
I tried to use `ActionableExtManual::set_action_target` like this:

```rust
button.set_action_target(&string));
```

Every time I get these errors in the logs:

```shell
GLib-CRITICAL **: 16:31:11.017: '%s' is not a valid GVariant format string
GLib-CRITICAL **: 16:31:11.017: g_variant_new_va: assertion 'valid_format_string (format_string, !endptr, NULL)' failed
```
It works however with `ActionableExt::set_action_target_value`, like this:

```rust
button.set_action_target_value(Some(&string.to_variant()));
```

**Comment by bilelmoussaoui** [comment]
what's the value of `string` here?

**Comment by sdroege** [comment]
Also I think `set_action_target()` should simply take a `T: ToVariant` and call into `set_action_target_value()` with the result. That makes much more sense.

**Comment by zecakeh** [comment]
> what's the value of `string` here?

For us here it's a single emoji
