### ISSUE TITLE
[BUG] GtkPopover: set_pointing_to/pointing_to implementations are not accurate

### ISSUE THREAD

**Issue by zecakeh** [gtk-rs/gtk4-rs#771]
### 1. `set_pointing_to`

`gtk_popover_set_pointing_to` [is not properly documented](https://gitlab.gnome.org/GNOME/gtk/-/issues/4556), but looking at the code we see that the `rect` parameter is nullable to be able to reset the property, so it should be an `Option<Rectangle>`.

### 2. `pointing_to`

Looking at the docs, it says that `gtk_popover_get_pointing_to` always returns a `Rectangle` and a boolean. With how it is implemented it only returns the rectangle when the boolean is `true`.

I'm not sure if `2.` is really useful but I saw that when looking into `1.`.

**Comment by bilelmoussaoui** [comment]
The issue should be fixed on the C code. The function needs a nullable annotation for the rect

**Comment by bilelmoussaoui** [comment]
Regarding 2, that's how optional values are returned in C. You pass in an inout param and it returns a Boolean whether the pointer was filled by some value or not, nothing to be done here

**Comment by zecakeh** [comment]
But the pointer is always filled. It always returns a `Rectangle`. That's why I was pointing that out.

**Comment by bilelmoussaoui** [comment]
Ah I see, it needs to be manually implemented
