### ISSUE TITLE
[HELP] Example Todo App 1 not compiling ?

### ISSUE THREAD

**Issue by lancecarlson** [gtk-rs/gtk4-rs#778]
I'm trying to figure out why I'm having trouble compiling the full Todo App 1 example application and it looks like there is some missing code or it's outdated or something? Here are the compile issues:

First one involves this line:
https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/todo_app/1/todo_object/imp.rs#L23

Is it missing a ParentType specification? Locally I added this line and it made the compile issue go away:

```
    type ParentType = glib::Object;
```

After I fixed that I still get issues with the ParamSpecBoolean struct. On 32 and 44 it complains that there is no method new on that type.

https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/todo_app/1/todo_object/imp.rs#L32
https://github.com/gtk-rs/gtk4-rs/blob/master/book/listings/todo_app/1/todo_object/imp.rs#L44

I looked at the docs and I don't see new defined either. Am I going crazy? haha

**Comment by sdroege** [comment]
Try running `cargo update`, then this should work fine without changes :)

**Comment by lancecarlson** [comment]
@sdroege Nice! I got this to work by putting my example project's Cargo on the github master branch. Perhaps a new release should be cut so the docs reflect the latest?

Cheers!

**Comment by sdroege** [comment]
If you're using the master version of the docs then you also need to use the master version of the bindings. Otherwise use the released version of the docs :)

A new release is planned really soon now.

**Comment by lancecarlson** [comment]
@sdroege Not sure if it makes sense to open a new ticket (I will if I should), but running through the actions app (#5), I keep getting this error before I click into the app:

(gtk-actions:48300): GLib-GObject-WARNING **: 17:34:56.491: g_object_weak_unref: couldn't find weak ref 0x10cb2ba30(0x7fd57c508100)

That first click doesn't allow me to click Press me to increment the counter, but after I get that first one out of the way it starts counting. Any idea what's up? Still new to debugging these weak reference issues.

**Comment by bilelmoussaoui** [comment]
Please open a new issue

**Comment by lancecarlson** [comment]
@bilelmoussaoui Roger! Thanks
