### ISSUE TITLE
[HELP] weak reference preventing a click on actions app 5

### ISSUE THREAD

**Issue by lancecarlson** [gtk-rs/gtk4-rs#783]
Running through the actions app (the 5th one), I keep getting this warning in the console when I click into the app for the first time:

(gtk-actions:48300): GLib-GObject-WARNING **: 17:34:56.491: g_object_weak_unref: couldn't find weak ref 0x10cb2ba30(0x7fd57c508100)

That first click doesn't allow me to click Press me to increment the counter, but after I get that first one out of the way it starts counting. Any idea what's up? Still new to debugging these weak reference issues.

**Comment by sdroege** [comment]
That seems unrelated to the application code and is likely a problem in GTK itself or your theme. Can you set the environment variable `G_DEBUG=fatal_warnings` and run the application in `gdb` to get a backtrace of that warning?

**Comment by lancecarlson** [comment]
@sdroege So I tried running with that flag and ran `gdb` right after, then tried to click into the application and it crashed.

```
$ G_DEBUG=fatal_warnings cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/gtk-actions`

(gtk-actions:4015): GLib-GObject-WARNING **: 10:33:31.304: g_object_weak_unref: couldn't find weak ref 0x10bccfa30(0x7fdd75a71e40)
Trace/BPT trap: 5
```

**Comment by sdroege** [comment]
Please run in `gdb` so you can get a backtrace of that warning.

**Comment by lancecarlson** [comment]
Sorry I'm not that familiar with gdb. I ran gdb target/debug/gtk-actions. Then once inside I typed run. 

```
Starting program: ***/gtk-actions/target/debug/gtk-actions 
Note: this version of macOS has System Integrity Protection.
Because `startup-with-shell' is enabled, gdb has worked around this by
caching a copy of your shell.  The shell used by "run" is now:
   ***/gdb/bin/bash
Unable to find Mach task port for process-id 4196: (os/kern) failure (0x5).
 (please check gdb is codesigned - see taskgated(8))
(gdb) G_DEBUG=fatal_warnings run
Undefined command: "G_DEBUG".  Try "help".
```

I had run G_DEBUG=fatal_warnings cargo run on another terminal before doing this. I also tried running the program again in the other tab with gdb open and no backtrace was found.

**Comment by lancecarlson** [comment]
@sdroege By the way, there were a TON of warnings right after I ran gdb target/debug/gtk-actions. I'm assuming you don't want me to paste those?

**Comment by lancecarlson** [comment]
I have to do some extra legwork to get gdb setup on mac it looks like. Hold on.

**Comment by lancecarlson** [comment]
@sdroege will lldb work at all?

**Comment by sdroege** [comment]
Sure, any debugger that can print you the call stack on SIGABRT will do. Just make sure to a) set the environment variable, and b) run the application in the debugger and not just `cargo`.

**Comment by lancecarlson** [comment]
@sdroege OK, so with the help of a friend I was able to isolate the issue to line 17 of window.ui. When I comment out this line, the warning goes away. 

Also I can reproduce the warning if I alt+tab away and click on the window again.

```
            <property name="action-name">win.count</property>
```

Any thoughts on this?

**Comment by lancecarlson** [comment]
@sdroege My friend just ran my code on her Linux machine and it worked without any warnings. So I'm guessing it's related to Mac somehow?

**Comment by bilelmoussaoui** [comment]
@lancecarlson that's not the correct source of your issue. The action-name just tells to the GtkButton which action to trigger when you click on it

**Comment by sdroege** [comment]
Can you paste the backtrace?

**Comment by lancecarlson** [comment]
```
2021-12-31 13:30:22.555880-0500 gtk-actions[5975:85400] [] [0x103028400] CVDisplayLinkStop
2021-12-31 13:30:22.555911-0500 gtk-actions[5975:85400] [] [0x103028420] CVDisplayLink::stop
2021-12-31 13:30:22.556057-0500 gtk-actions[5975:85400] [] [0x103028400] CVDisplayLinkStart
2021-12-31 13:30:22.556081-0500 gtk-actions[5975:85400] [] [0x103028420] CVDisplayLink::start
2021-12-31 13:30:22.556168-0500 gtk-actions[5975:85519] [] [0x600002945260] CVXTime::reset
2021-12-31 13:30:22.573218-0500 gtk-actions[5975:85400] [] [0x103028400] CVDisplayLinkStop
2021-12-31 13:30:22.573245-0500 gtk-actions[5975:85400] [] [0x103028420] CVDisplayLink::stop
2021-12-31 13:30:22.777890-0500 gtk-actions[5975:85400] [General] Stale deferred activation count: the current app activation event does not match the previously received deferred activation event. (deferred: 331, current: 332)

(gtk-actions:5975): GLib-GObject-WARNING **: 13:30:22.800: g_object_weak_unref: couldn't find weak ref 0x100dfba30(0x101c19e40)
```

**Comment by sdroege** [comment]
Run it in `lldb` until it crashes, then run `thread backtrace` and paste the output of that.

**Comment by sdroege** [comment]
Let's close this then, there's nothing actionable here at this point :)
