### ISSUE TITLE
[Book] The book is not valid for the current release

### ISSUE THREAD

**Issue by yelhouakmi** [gtk-rs/gtk4-rs#788]
The exemples given in the book on the [List chapter](https://gtk-rs.org/gtk4-rs/stable/latest/book/list_widgets.html) cannot be compiled with the latest release (0.3.1).

It seems that the book is published regularly on not only on release.

The best « fix » would be to publish the book with a version selector. So we can switch between releases and latest.

Exemples of errors:
- On the subclassing, we cannot omit « type ParentType = glib::Object » while on the latest it seems to be the default if omitted.
- « model.splice(0, 0, &vector) » can’t be used.

Overall the book is a good introduction, I can see that it is an express introduction and that many MANY features are not listed but it is what I expect of this kind of book 😃 

Thanks for the work 👍 .

**Comment by bilelmoussaoui** [comment]
> The best « fix » would be to publish the book with a version selector. So we can switch between releases and latest.

That's very hard to achieve :/ At some point the bindings will stabilize +/- and the book would be as well

**Comment by yelhouakmi** [comment]
Sadly i know that it is a hard thing to achieve 😄. It is the best fix but not the easiest.

It is just that being a Java backend dev, i’m inclined to have a tunnel vision while learning Rust AND gtk4. And as such i’ve try to put « GObject » as a ParentType to correct the error because it is what is indicated in the book, the « root » object. And i’ve passed a good amount of time searching for the different compilation error before even thinking that the doc was simply out of sync. And it may discourage others will the book is overall a good start.

At no point in the doc is there a reference to the current release version so it was a bad assertion on my part. A simple warning at the start of the book will be enought.

> Warning, this book represent the state of the latest/nightly/snapshot version. Some part may not work with the current release. If it is the case, please clone the repo and read the exemple/the book on the release tag.

Something like that.

**Comment by bilelmoussaoui** [comment]
The  book is now following the latest stable release instead of git
