### ISSUE TITLE
Provide GDK backend information to dependencies

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk4-rs#789]
See https://github.com/gtk-rs/gtk3-rs/blob/master/gdk/sys/build.rs#L39

**Comment by bilelmoussaoui** [comment]
It seems gtk no longer installs a pkgconfig for gdk and the targets variable exists nowadays in gtk4 itself. 
```bash
bilelmoussaoui@toolbox ~/P/gtk4-rs (bilelmoussaoui/debug) [1]> pkg-config --variable=targets gtk4
broadway\ wayland\ x11
```

**Comment by sdroege** [comment]
Correct, yes
