### ISSUE TITLE
[HELP] Compile and install GTK4 in Windows 

### ISSUE THREAD

**Issue by Chus4** [gtk-rs/gtk4-rs#801]
I run the following command:
meson setup builddir --prefix=C:/gnome -Dbuild-tests=false -Dmedia-gstreamer=disabled

It takes too long to: "Cloning into 'libffi'..." . and throw that error

glib| Dependency libpcre from subproject subprojects/pcre-8.37 found: YES undefined
glib| Library m found: NO
glib| Run-time dependency libffi found: NO (tried pkgconfig and cmake)
glib| Looking for a fallback subproject for the dependency libffi
glib| Using subprojects\glib\subprojects\libffi.wrap
Cloning into 'libffi'...
fatal: unable to access 'https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi.git/': The requested URL returned error: 504

subprojects\glib\meson.build:2024:0: ERROR: Git command failed: ['C:\\Program Files\\Git\\cmd\\git.EXE', 'clone', '--depth', '1', '--branch', 'meson', 'https://gitlab.freedesktop.org/gstreamer/meson-ports/libffi.git', 'libffi']

A full log can be found at C:\gtk\builddir\meson-logs\meson-log.txt

**Comment by sdroege** [comment]
See https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/407
