### ISSUE TITLE
[BUG] Broken EntryCompletion when using builder

### ISSUE THREAD

**Issue by panicbit** [gtk-rs/gtk4-rs#802]
**Bug description**
Setting the `text_column` of an `EntryCompletion` using its builder instead of using `set_text_column` causes weird rendering / behavior of popup completion:

```rust
EntryCompletion::builder()
    .text_column(0)
    .build();
```
[Changing the `entry_completion` example accordingly](https://github.com/panicbit/gtk4-rs/commit/9fa6fbda647aecb68141ba79a45fc44384d52541) produces this:

![image](https://user-images.githubusercontent.com/628445/148662143-b5f596aa-2f1a-45ab-ab1c-9de50ad00cef.png)

**Additional Information**
- GTK: `4.4`
- OS: `Arch Linux`

**Comment by panicbit** [comment]
It seems like [`gtk_entry_completion_set_text_column`](https://github.com/GNOME/gtk/blob/50e4ca8593d12b2de76e4d092d34ec7a1655ede8/gtk/gtkentrycompletion.c#L1052-L1091) does a bit more than simply setting the `text-column` property.
Apparently my assumption that the builder methods are equivalent to their `set_*` counterparts is wrong.
Is this intentional design of `gtk-rs`?

**Comment by bilelmoussaoui** [comment]
Normally properties that expect more than a change of the property value should use their setter on the value at https://github.com/GNOME/gtk/blob/50e4ca8593d12b2de76e4d092d34ec7a1655ede8/gtk/gtkentrycompletion.c#L563 but it doesn't seems to be the case for text-column property. So far we have no way to fix this easily other than: 
- Manually write the builder pattern and call the corresponding method if text-column property is set
- Completely ignore the text-column property, it is blocked by https://github.com/gtk-rs/gir/issues/1302 unless we manually implement the builder pattern
- Report this upstream and see if it makes sense to call `gtk_entry_completion_set_text_column` when setting the value of `text-column` property

**Comment by bilelmoussaoui** [comment]
> It seems like [`gtk_entry_completion_set_text_column`](https://github.com/GNOME/gtk/blob/50e4ca8593d12b2de76e4d092d34ec7a1655ede8/gtk/gtkentrycompletion.c#L1052-L1091) does a bit more than simply setting the `text-column` property (like the builder method does).
> Apparently my assumption that the builder methods are equivalent to their `set_*` counterparts is wrong.
> Is this an intentional design of `gtk-rs`?


Builders are basically wrappers around calling glib::Object::new and passing the various properties to it with a bit of type safety at compile time. It definitely doesn't call the set_ functions

**Comment by bilelmoussaoui** [comment]
Closing this as it is an upstream issue, setting the property should ideally call the setter instead of modifying the property value.
