### ISSUE TITLE
Investigate nullability of GskTransform

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#817]
Seems like a bunch of GskTransform methods returns a nullable but are not annotated as such...

cc @alatiera

**Comment by sdroege** [comment]
Should happen before the release ideally as this will change the API.

**Comment by bilelmoussaoui** [comment]
i don't believe that will happen. At worst it can be pushed to a 0.5 release later on

**Comment by sdroege** [comment]
I can take a look after I finished my tea. It's just 5 or so functions we're talking about here.

**Comment by sdroege** [comment]
See https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/4378

They can actually return `NULL` and we'll have to handle all this a bit differently here by treating `NULL` not as `None` but as an identity transform.
