### ISSUE TITLE
[BUG] Stack::page should be nullable

### ISSUE THREAD

**Issue by SeaDve** [gtk-rs/gtk4-rs#826]
**Bug description**

It seems to be an upstream issue too that it is not marked nullable

**Comment by bilelmoussaoui** [comment]
I tend to disagree here. It is a programmer error to pass a widget that is not a page of the stack and it should panic

**Comment by SeaDve** [comment]
I used it to determine whether a page already exist in a stack

**Comment by bilelmoussaoui** [comment]
in which context you have to do that? i guess open a PR to add nullable annotation upstream and we will backport the changes here

**Comment by bilelmoussaoui** [comment]
Note that libadwaita has similar APIs and we already discussed whether it makes sense to make them nullable, see https://gitlab.gnome.org/World/Rust/libadwaita-rs/-/issues/4 & https://gitlab.gnome.org/GNOME/libadwaita/-/merge_requests/175/diffs

**Comment by SeaDve** [comment]
I see, the arguments make sense for me, should I close it?

**Comment by SeaDve** [comment]
the workaround i did to determine if a child exist is iterating over the page, for now

**Comment by SeaDve** [comment]
> in which context you have to do that?

It's some sort of API where a Widget can add their auxiliary Widget to the main stack. Loading them all at once, would be less efficient than adding them on demand

**Comment by bilelmoussaoui** [comment]
> > in which context you have to do that?
> 
> It's some sort of API where a Widget can add their auxiliary Widget to the main stack. Loading them all at once, would be less efficient than adding them on demand

You could always store the added pages on a Vec

**Comment by SeaDve** [comment]
thanks! closing this
