### ISSUE TITLE
Allow conversion between various Rectangle types

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#836]
There is a gdk::Rectangle, pango::Rectangle, cairo::Rectangle. We should implement From traits for those in the gtk crate

**Comment by sdroege** [comment]
You can't implement that in the `gtk` crate. Has to be in one of the two crates that defines the type. Which is a bit problematic for pango/cairo because they don't depend on each other.

**Comment by bilelmoussaoui** [comment]
Ah yeah, I always forget this constraint. Well, we can implement them in `gdk`, seems like there is a `From<cairo::RectangleInt>` implementation already.
