### ISSUE TITLE
ClosureExpression::new asks for all three generic types

### ISSUE THREAD

**Issue by zecakeh** [gtk-rs/gtk4-rs#838]
A closure expression has to be declared like that:

```rust
gtk::ClosureExpression::new::<bool, _, _>(
    &[a_expr],
    closure!(|_: Option<Object>, a: bool| { !a }),
)
```

One with no parameters must be declared like that:

```rust
gtk::ClosureExpression::new::<String, &[gtk::Expression], _>(
    &[],
    closure!(|member: Option<Member>| { member.map(search_string).unwrap_or_default() }),
)
```

It would be great if at most we only had to annotate the `ValueType`, like in `chain_closure`. But if the `closure!` return type could be used for the `ValueType`, that would be even better.

**Comment by bilelmoussaoui** [comment]
@zecakeh I don't think there is a simple way to figure out the return type of a RustClosure, it all happens at runtime

**Comment by sdroege** [comment]
The types of the `glib::Closure` created by the `closure!` macro are unfortunately not part of the type. Doing this would require making the `glib::RustClosure` type generic at least. It should be doable but is a bit of work.

**Comment by zecakeh** [comment]
No problem. Just wishful thinking :)

**Comment by bilelmoussaoui** [comment]
This can be fixed now as we have bumped the minimum rust version to 1.63
