### ISSUE TITLE
[HELP] Trying to run the todo_app example fails

### ISSUE THREAD

**Issue by DonutDev** [gtk-rs/gtk4-rs#843]
by running
`cargo run --bin todo_app_1`
The app launches fine without issues, but when trying to run
`cargo run --bin todo_app_4`
it returns this error
`(todo_app_4:17542): GLib-GIO-ERROR **: 12:27:46.792: Settings schema 'org.gtk-rs.Todo' is not installed
Trace/breakpoint trap (core dumped`

**Comment by Hofer-Julian** [comment]
You have to copy and compile the schema first as described here

https://gtk-rs.org/gtk4-rs/stable/latest/book/settings.html
