### ISSUE TITLE
Hide cmd window on Windows

### ISSUE THREAD

**Issue by mweller83** [gtk-rs/gtk4-rs#846]
Hi everybody!

I made a very simple GTK4 application and created a -release binary for Windows. Works great but when I execute the .exe not only the application appears but also a cmd windows/dos prompt (like if you run a Java GUI with javaw and not with java). 
How can I change this so that only the application‘s window shows up?

Thank you!

**Comment by bilelmoussaoui** [comment]
I believe this is less related to gtk-rs but to windows itself. IIRC when compiling your application you have to somehow mark it as a GUI app and not a console application. Not sure how can you do that with Rust

**Comment by mweller83** [comment]
Thanks for the hint! In fact, it's totally unrelated to gtk-rs..
Adding 
```
#![windows_subsystem = "windows"]
```
to the top of main.rs fixes this for me. (And this line also enables to close applications "windows style" with ALT+F4.)

**Comment by sdroege** [comment]
@Hofer-Julian Should that maybe be mentioned as a footnote somewhere in the book?

**Comment by Hofer-Julian** [comment]
> @Hofer-Julian Should that maybe be mentioned as a footnote somewhere in the book?

I don't know how distribution of Windows apps typically works. Maybe it already involves steps that make this unnecessary?

**Comment by sdroege** [comment]
It's unrelated to distribution, you have to tell the compiler if it should build a commandline application or an UI application.

**Comment by bilelmoussaoui** [comment]
I thin kit definitely should be part of the book somewhere, otherwise questions like this will keep showing up

**Comment by Hofer-Julian** [comment]
Looking at this, more steps are necessary with the msvc toolchain which we currently recommend and test with our CI. 

https://rust-lang.github.io/rfcs/1665-windows-subsystem.html#additional-linker-argument

**Comment by bilelmoussaoui** [comment]
There are definitely more steps to ship a working application under window like https://gitlab.gnome.org/World/design/palette/-/blob/master/src/palette.rc.in for making the application icon work correctly. All of this could be at the end of the book as part of "Deploy your application" and have a Linux (Flatpak)/Windows/macOS chapters (of course, people will have to help with latest two :))

**Comment by Hofer-Julian** [comment]
Sounds good to me.
