### ISSUE TITLE
Add an example that makes use of async operations

### ISSUE THREAD

**Issue by bilelmoussaoui** [gtk-rs/gtk4-rs#853]
Something like sending a web request to retrieve some data and then display it. Maybe using tokio or some other async runtime.

**Comment by sdroege** [comment]
There's an example in gtk-rs-core and I think also an example for dialogs here?

> Maybe using tokio or some other async runtime.

That will involve a bit of boilerplate for the cross-runtime communication then but probably a good idea to have an example for that.

**Comment by bilelmoussaoui** [comment]
> There's an example in gtk-rs-core and I think also an example for dialogs here?

There is indeed, but it doesn't show how to integrate with a window without blocking the main thread

**Comment by Claudio-code** [comment]
Iwrote it example https://github.com/gtk-rs/gtk4-rs/pull/1578

but CI falls because not found openssl dependency https://github.com/gtk-rs/gtk4-rs/actions/runs/7649773189/job/20844748624
