### ISSUE TITLE
[BUG] Wrong Filename for Windows in glium_gl_area Example

### ISSUE THREAD

**Issue by anlumo** [gtk-rs/gtk4-rs#854]
**Bug description**

This line:

https://github.com/gtk-rs/gtk4-rs/blob/200d25e577727a1d61536533fcdaae8da3ee7d0f/examples/glium_gl_area/main.rs#L17

tries to load a DLL called "libepoxy-0.dll". However, at least on my installation this file is called "epoxy-0.dll".

Without the fix:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GetModuleHandleExW { source: Os { code: 126, kind: Uncategorized, message: "The specified module could not be found." } }', examples\glium_gl_area/main.rs:17:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with the change (removing the `lib` prefix) it works fine on my machine.

**Comment by sdroege** [comment]
Do you want to provide a PR for this? I think this example was never tested on Windows, good to hear that this is the only problem :)

**Comment by anlumo** [comment]
Done! Sorry for the delay, forgot about this.
