### ISSUE TITLE
[BUG] Missing information in chapter 5.4

### ISSUE THREAD

**Issue by maciejczekaj** [gtk-rs/gtk4-rs#858]
**Bug description**

This chapter says that we can use custom properties in GObject. Provided code samples shows are supposed to show necessary changes to make it work but there is no information that we should change 

```
self.number.set(self.number.get() + 1);
button.set_label(&self.number.get().to_string());
```

into:
```
let incremented_number = self.number.get() + 1;
button.set_property("number", &incremented_number);
```

to make bindings work correctly.

Would be nice to at least mention that as when you rewrite this code on your own you may spend some time to figure that out

**Comment by Hofer-Julian** [comment]
Nice catch, will fix that.
