### ISSUE TITLE
[BUG] Listing visibility issue in chapter 11

### ISSUE THREAD

**Issue by maciejczekaj** [gtk-rs/gtk4-rs#859]
Hi,

Thanks for creating this introduction to GTK with rust. I'm new to rust and GTK and this introduction helped me a lot.

**Bug description**

First listing of mod.rs looks like that
![image](https://user-images.githubusercontent.com/57869998/151846726-4a48d4e7-3ee3-4ef3-a77c-908362c2d1c9.png)

On this stage to run the app and display UI we need to add also new method (constructor) otherwise app will not build in main.rs Would be nice to put that as highlighted part of this snippet (change color to white :) )

**Comment by Hofer-Julian** [comment]
@maciejczekaj you mean `new`?

**Comment by Hofer-Julian** [comment]
Ah yes, I see your point but in later chapters I am not highlighting every single line. Unless it is necessary to understand the concept of course. In that case, adding constructors has been mentioned multiple times already.
