### ISSUE TITLE
[HELP] How to handle all keypress events?

### ISSUE THREAD

**Issue by rnice01** [gtk-rs/gtk4-rs#862]
Hello,
First of all, thanks for all the hard work on this, the examples and documentation are great! I'm currently trying to figure out a way to capture all keyboard events from the top level handler, like the window or something. The goal is to create a VIM like editor so I'm not sure if an Entry widget would fit my needs. Anyway below is the code I'm using from one of the examples, just trying to figure out how/what to connect to for the key press events.
```
fn main() {
    // Create a new application
    let app = Application::builder()
        .application_id("org.gtk-rs.example")
        .build();

    // Connect to "activate" signal of `app`
    app.connect_activate(build_ui);

    // Run the application
    app.run();
}

fn build_ui(app: &Application) {
    // Create a window and set the title
    let text = gtk::Text::builder().text("test").build();
    let window = ApplicationWindow::builder()
        .application(app)
        .title("My GTK App")
        .child(&text)
        .build();

/// This is failing saying key-release-event signal not found
    window.connect("key-release-event", false, move |args| {
      None
    });
    // Present window
    window.present();
}
```

**Comment by bilelmoussaoui** [comment]
Using an EventController. In this case you would use A GtkEventControllerKey. Something like this should work
```rust
let window = ApplicationWindow::builder()
        .application(app)
        .title("My GTK App")
        .child(&text)
        .build();
let controller = gtk::EventControllerKey::new();
controller.connect_key_pressed(move |controller, key, keycode, state| {
 println!("{:#?}", keyval.name());
});
window.add_controller(&controller);
```

We have an open issue at #662 for adding a chapter about event controllers.

**Comment by bilelmoussaoui** [comment]
See also https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/struct.EventControllerKey.html#method.connect_key_pressed
