### ISSUE TITLE
Support for vcpkg on Windows

### ISSUE THREAD

**Issue by ruifengx** [gtk-rs/gtk4-rs#865]
Looks like [`vcpkg`](https://github.com/microsoft/vcpkg) has [support for `gtk`](https://github.com/microsoft/vcpkg/tree/master/ports/gtk). `vcpkg` has long been my preferred "package manager" for C/C++ libraries, and it looks very popular among Windows programmers (14.8k stars atm). There is a Rust binding for `vcpkg` ([`vcpkg-rs`](https://docs.rs/vcpkg/latest/vcpkg/)), and I find it relatively easy to use (see [the use of `vcpkg` in `rust-sdl2`](https://github.com/Rust-SDL2/rust-sdl2/blob/master/sdl2-sys/build.rs), for example).

Installing `gtk` using `vcpkg` should be as easy as `vcpkg install gtk`. Compare this to [the steps listed in _the Book_](https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html) currently. I wonder whether or not it is possible to add support for `vcpkg` here, so that installation on Windows could be less painful (at least from my perspective).

If you find this change appropriate, I could work on this and try to submit a PR, but I will need some guidance on which files to modify (it seems the `-sys` crates here are automatically generated, and I currently have very little knowledge on that generator). The change should only involve modifying `Cargo.toml` (adding an optional dependency on `vcpkg`) and `build.rs` (making use of `vcpkg` to locate the library to link with), and we should be able to make both modifications backward compatible (e.g. by feature-gating the use of `vcpkg`).

> P.S. The title says "on Windows", but one should also be able to use `vcpkg` on other platforms like Linux, but I am afraid that very few people would actually want to do that (because apparently `pkg-config` is well-integrated on Linux, and installing `gtk` should be as easy as e.g. `dnf install gtk4-devel`).

**Comment by bilelmoussaoui** [comment]
Are there any bindings out there that makes use of it ?  Would it conflict with the current automatic system-deps usage ?

It looks interesting though

**Comment by ids1024** [comment]
See https://github.com/gdesmott/system-deps/issues/8 and https://github.com/gdesmott/system-deps/pull/12 for previous discussion and work on this.

**Comment by ruifengx** [comment]
As I mentioned, there is `rust-sdl2` using both `pkg-config` and `vcpkg`. If [this PR](https://github.com/imgui-rs/imgui-rs/pull/582) lands, `imgui-rs` will also be using both. Regarding `system-deps` (I did not know it is used here; my guess was that [`pkg-config-rs`](https://github.com/rust-lang/pkg-config-rs) is used here), I found [this interesting issue](https://github.com/gdesmott/system-deps/issues/8) and [this PR](https://github.com/gdesmott/system-deps/pull/12). However, both lack an update ever since Aug 2020. They did mention `vcpkg`'s `gtk` builds are broken, but that was one year ago, and [this PR](https://github.com/microsoft/vcpkg/pull/20654) (merged 2 months ago) might have fixed the problem. I will try `vcpkg install gtk` to verify this soon.

However, to be clear, I am not necessarily bound to using `vcpkg`. I am just not satisfied with the current steps for installation required on Windows (just compare that long list to the one-line `dnf install gtk` on Fedora, for example).

**Comment by ruifengx** [comment]
See also microsoft/vcpkg#22881 regarding build failure and version update.

**Comment by Hofer-Julian** [comment]
@ruifengx could you elaborate what you mean with "support" for vcpkg?

**Comment by ruifengx** [comment]
That would be automatically locating the package with `vcpkg` and getting all the link flags, _without going through an extra `pkg-config` step_. IMO `pkg-config` on Windows is barely usable, and supporting `gtk` would be its mere purpose for existing on my PC.

**Comment by Hofer-Julian** [comment]
Then I guess there is nothing to do from our side until https://github.com/gdesmott/system-deps/pull/12 is merged.

**Comment by ruifengx** [comment]
Okay, and it seems that PR won't be merged any time soon in its current status. I guess I have to live with the status quo, or try to help that PR land. Thanks anyway.

Do you prefer this issue closed, or should I leave it open until the upstream PR is merged?

**Comment by Hofer-Julian** [comment]
I think we can close it and open a new one when it becomes actionable :)
