### ISSUE TITLE
[BUG] `NamedAction::new(&"")` cause crash

### ISSUE THREAD

**Issue by qarmin** [gtk-rs/gtk4-rs#875]
```
System:    Host: rafalkom Kernel: 5.13.0-28-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: GNOME 40.5 
           tk: GTK 3.24.30 wm: gnome-shell dm: GDM3 Distro: Ubuntu 21.10 (Impish Indri) 
```
```
RUST_BACKTRACE=full RUSTFLAGS=-Zsanitizer=address RUSTDOCFLAGS=-Zsanitizer=address cargo run  -Zbuild-std --target x86_64-unknown-linux-gnu
```

**Bug description**

```
let ff = NamedAction::new(&"");
```
cause crash:
```
**
Gtk:ERROR:../../../gtk/gtkshortcutaction.c:1166:gtk_named_action_constructed: assertion failed: (self->name != NULL && self->name[0] != '\0')
Bail out! Gtk:ERROR:../../../gtk/gtkshortcutaction.c:1166:gtk_named_action_constructed: assertion failed: (self->name != NULL && self->name[0] != '\0')
Aborted (core dumped)


```

**Comment by bilelmoussaoui** [comment]
That looks like a programmer error to me

**Comment by sdroege** [comment]
Yeah looks like correct handling to me. Ideally this could be annotated somehow and we'd have a non-empty-string type... but that's not how reality is.

Not sure how we could improve on this. In theory we could check this pre-condition and panic otherwise, but that's not really helping anything.

**Comment by bilelmoussaoui** [comment]
> Not sure how we could improve on this. In theory we could check this pre-condition and panic otherwise, but that's not really helping anything.

The only way I could see this improved somehow, is as you mentioned, having some kind of "hopefully" better panic message but other than that not much. Could be pretty easy to do once we have something like https://gitlab.gnome.org/GNOME/gobject-introspection/-/issues/406

**Comment by bilelmoussaoui** [comment]
I am going to go ahead and close this one as there isn't much we can do here
