### ISSUE TITLE
[BUG] Closing the application will output an error message

### ISSUE THREAD

**Issue by langzime** [gtk-rs/gtk4-rs#898]
**Bug description**

Closing the application will output an error message

**Backtrace**

thread 'main' panicked at 'assertion failed: ::glib::types::instance_of::<Self>(ptr as *const _)', /Users/xxxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.6/src/auto/tree_selection.rs:19:1
stack backtrace:
   0:        0x100e42b21 - std::backtrace_rs::backtrace::libunwind::trace::h47a7835575e4d9f3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x100e42b21 - std::backtrace_rs::backtrace::trace_unsynchronized::he8690599afcb5399
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x100e42b21 - std::sys_common::backtrace::_print_fmt::h0617b83dce07f61f
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x100e42b21 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h90c059b532d34bdd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x100e596eb - core::fmt::write::hefb311138778afb5
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:        0x100e3cf1a - std::io::Write::write_fmt::h0e0ed87b18ae870c
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:        0x100e44345 - std::sys_common::backtrace::_print::hcb332ccba1b9e587
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x100e44345 - std::sys_common::backtrace::print::h8f35339db66741dd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x100e44345 - std::panicking::default_hook::{{closure}}::h43f0e51e5825bd5b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:        0x100e43f2f - std::panicking::default_hook::ha1c3473cbcf391f7
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:        0x100e44a30 - std::panicking::rust_panic_with_hook::h0db3c4ba5fb4dc12
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:        0x100e444a4 - std::panicking::begin_panic_handler::{{closure}}::hc6d8c92efeef5a19
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:500:13
  12:        0x100e42f97 - std::sys_common::backtrace::__rust_end_short_backtrace::h7ffb59e898e02a83
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:        0x100e4443a - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:        0x100e6595f - core::panicking::panic_fmt::h7d73f67464d78916
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:        0x100e658b7 - core::panicking::panic::h9721d5a8c5d33ad7
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:48:5
  16:        0x100d5c8d8 - <gtk4::auto::tree_selection::TreeSelection as glib::translate::FromGlibPtrNone<*mut gtk4_sys::GtkTreeSelection>>::from_glib_none::hd6182b685e2016ff
                               at /Users/xxxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.5/src/object.rs:829:17
  17:        0x100d62da1 - glib::translate::from_glib_none::h088e53305a92ff42
                               at /Users/xxxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.15.5/src/translate.rs:1426:5
  18:        0x100b25138 - <O as gtk4::auto::tree_view::TreeViewExt>::selection::hef96cdba86d644a6
                               at /Users/xxxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.6/src/auto/tree_view.rs:1539:13
  19:        0x100b67568 - raudient::main_win::MainWindow::new::{{closure}}::h7feb3a4c0c5bc252
                               at /Users/xxxxxxxxx/CargoProjects/raudient/src/main_win.rs:90:29
  20:        0x100b250f0 - <O as gtk4::auto::tree_view::TreeViewExt>::connect_cursor_changed::cursor_changed_trampoline::hc5f832e2ce7f1b24
                               at /Users/xxxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk4-0.4.6/src/auto/tree_view.rs:2211:13
  21:        0x10144c325 - __g_closure_invoke_va
  22:        0x101463202 - _g_signal_emit_valist
  23:        0x101463d22 - _g_signal_emit
  24:        0x1016dc02e - _gtk_tree_view_set_model
  25:        0x1016e8dc7 - _gtk_tree_view_dispose
  26:        0x101451383 - _g_object_unref
  27:        0x10163cae2 - _gtk_scrolled_window_dispose
  28:        0x101451383 - _g_object_unref
  29:        0x1014fc1c8 - _gtk_box_dispose
  30:        0x101451383 - _g_object_unref
  31:        0x1017192d4 - _gtk_window_dispose
  32:        0x1014c4605 - _gtk_application_window_dispose
  33:        0x101451383 - _g_object_unref
  34:        0x1015e1991 - _gtk_main_do_event
  35:        0x10171bbec - _surface_event
  36:        0x1017fb00a - __gdk_marshal_BOOLEAN__POINTERv
  37:        0x10182d042 - _gdk_surface_event_marshallerv
  38:        0x10144c325 - __g_closure_invoke_va
  39:        0x101463202 - _g_signal_emit_valist
  40:        0x101463d22 - _g_signal_emit
  41:        0x10182c4ab - _gdk_surface_handle_event
  42:        0x10183bdfb - _gdk_macos_event_source_dispatch
  43:        0x10217304e - _g_main_context_dispatch
  44:        0x1021733cd - _g_main_context_iterate
  45:        0x102173476 - _g_main_context_iteration
  46:        0x10200a80d - _g_application_run
  47:        0x100b24479 - <O as gio::application::ApplicationExtManual>::run_with_args::h08a3ac70ddf067a6
                               at /Users/xxxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.15.5/src/application.rs:30:13
  48:        0x100b2453a - <O as gio::application::ApplicationExtManual>::run::hff116ffd19ea2b19
                               at /Users/xxxxxxxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.15.5/src/application.rs:23:9
  49:        0x100b2ae13 - raudient::app::run::h8cf00248f4201cdf
                               at /Users/xxxxxxxxx/CargoProjects/raudient/src/app.rs:25:5
  50:        0x100b04c79 - raudient::main::h6b3b6dcbb7e97293
                               at /Users/xxxxxxxxx/CargoProjects/raudient/src/bin/raudient.rs:7:5
  51:        0x100b04d0e - core::ops::function::FnOnce::call_once::hcda04d72916423a9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  52:        0x100b04d61 - std::sys_common::backtrace::__rust_begin_short_backtrace::heb2028910f70813b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123:18
  53:        0x100b04de4 - std::rt::lang_start::{{closure}}::h2f6f51c9116e0b27
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145:18
  54:        0x100e427cf - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h366f85254a0aedbd
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  55:        0x100e427cf - std::panicking::try::do_call::hcd7d6ba18808215d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  56:        0x100e427cf - std::panicking::try::h8b7328b76a891d08
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  57:        0x100e427cf - std::panic::catch_unwind::h63bbd5ef51caa433
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  58:        0x100e427cf - std::rt::lang_start_internal::{{closure}}::h2efd4ac38212ab36
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  59:        0x100e427cf - std::panicking::try::do_call::hfdf1ca9f7283bb6b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  60:        0x100e427cf - std::panicking::try::h5e8a1aa20c127c08
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  61:        0x100e427cf - std::panic::catch_unwind::he9efa865311db8e6
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  62:        0x100e427cf - std::rt::lang_start_internal::hb74872162e3d56c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  63:        0x100b04dbe - std::rt::lang_start::h7022e059576285c3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:144:17
  64:        0x100b04c96 - <unknown>
                               at /Users/xxxxxxxxx/CargoProjects/raudient/src/bin/raudient.rs:8:2

<img width="883" alt="图片" src="https://user-images.githubusercontent.com/3364128/153412552-4c5ca3e3-c08e-477f-881b-d659a401be2b.png">

**Comment by sdroege** [comment]
I think this is basically the same as https://github.com/gtk-rs/gtk4-rs/issues/584 , @bilelmoussaoui ?

**Comment by bilelmoussaoui** [comment]
Seems like it yes
