### ISSUE TITLE
[BUG] Crash on GestureStylus.backlog()

### ISSUE THREAD

**Issue by Ungedummt** [gtk-rs/gtk4-rs#932]
**Bug description**

If the backlog function is called the application crashes with this error:
```
free(): invalid pointer
```

Here is a minimal example:

src/main.rs:
``` rust
use gtk::prelude::*;
use gtk::*;

fn main() {
    let application = Application::new(
        Some("org.test.test"),
        Default::default(),
    );
    application.connect_activate(build_ui);
    application.run();
}

fn build_ui(application: &Application) {
    let ui_src = include_str!("gtk_builder.ui");
    let builder = Builder::from_string(ui_src);

    let window: ApplicationWindow = builder.object("window").unwrap();
    window.set_application(Some(application));

    let stylus: GestureStylus = builder.object("stylus").unwrap();

    stylus.connect_motion(| gesture, _, _ | {
        println!("print");
        println!("{:#?}", gesture.backlog());
    });

    window.show();
}
```
src/gtk_builder.ui:
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<interface>
  <object class="GtkApplicationWindow" id="window">
    <property name="default-width">320</property>
    <property name="default-height">240</property>
    <child>
      <object class="GtkGestureStylus" id="stylus">
      </object>
    </child>
  </object>
</interface>
```
Cargo.toml:
``` toml
[package]
name = "example"
version = "0.0.1"
edition = "2021"

[dependencies]
gtk = { version = "0.4", package = "gtk4" }
```

**Comment by sdroege** [comment]
Nice one

**Comment by sdroege** [comment]
Doesn't crash for me with git master of the bindings and GTK 4.6.0. Can you run in a debugger and get a backtrace of the crash, and ideally also run in valgrind with `--track-origins=yes` another time?

**Comment by Ungedummt** [comment]
Weird I have GTK 4.6.1 (latest from main branch) installed on my system.

I tried to run it with valgrind but it doesn't launch the app at all. But I ran my app, were I discovered the bug, with valgrind and then everything is just working fine. I think it is because valgrind slows the app down and then it has a backlog to return. So the issue might be that there is no backlog and something failes with the memory cleanup?

**Comment by Ungedummt** [comment]
Got a backtrace with `--track-origins=yes`:
[valgrind.txt](https://github.com/gtk-rs/gtk4-rs/files/8088451/valgrind.txt)

Backtrace with out any options:
[valgrind.txt](https://github.com/gtk-rs/gtk4-rs/files/8088477/valgrind.txt)

But like I said earlier the app is slowed down that the crash is not happening any more :shrug: 
I removed the print of the backlog because this would clutter the backtrace

**Comment by bilelmoussaoui** [comment]
Maybe it shouldn't be a full container transfer here?

**Comment by sdroege** [comment]
Also doesn't crash for me with GTK 4.6.1

**Comment by sdroege** [comment]
Ah, how do I get the callback actually called? :)

**Comment by sdroege** [comment]
> Maybe it shouldn't be a full container transfer here?

According to the code it should, but it's missing an annotation (which doesn't matter for us because it's manually implemented anyway).

```cpp
  backlog_array = g_array_new (FALSE, FALSE, sizeof (GdkTimeCoord));
  [...]
  *n_elems = backlog_array->len;
  *backlog = (GdkTimeCoord *) g_array_free (backlog_array, FALSE);
  g_free (history);
```

**Comment by bilelmoussaoui** [comment]
> According to the code it should, but it's missing an annotation (which doesn't matter for us because it's manually implemented anyway).

Is it ? https://gtk-rs.org/gtk4-rs/stable/latest/docs/src/gtk4/auto/gesture_stylus.rs.html#116

**Comment by sdroege** [comment]
Oh it's autogenerated. But that still looks correct. It's `transfer full` according to the bindings and C code.

Why it crashes, I don't know. I can't get the callback called here at all :shrug:

**Comment by sdroege** [comment]
The `FromGlibContainer::from_glib_full_num()` implementation also looks correct to me, but from the backtrace it looks like it somehow frees the memory twice.

**Comment by sdroege** [comment]
Ah, have it.

**Comment by sdroege** [comment]
Can you check if https://github.com/gtk-rs/gtk-rs-core/pull/557 fixes it? I still don't know how to get the callback called :)

**Comment by Ungedummt** [comment]
> Can you check if https://github.com/gtk-rs/gtk-rs-core/pull/557 fixes it? I still don't know how to get the callback called :)

I'll try it this afternoon, thanks ;)

**Comment by Ungedummt** [comment]
> Can you check if [gtk-rs/gtk-rs-core#557](https://github.com/gtk-rs/gtk-rs-core/pull/557) fixes it? I still don't know how to get the callback called :)

Yes it fixes the issue, big thanks. Only 3 hours after reporting already fixed, thanks @sdroege (;
