### ISSUE TITLE
[BUG] FileChooserNativeBuilder::filter has no effect

### ISSUE THREAD

**Issue by Mek101** [gtk-rs/gtk4-rs#933]
**Bug description**

The file choser dialog produced by the builder will display any file regardless of mime or suffix.
`FileChooserNative::set_filter()` does however work when called on the built dialog.

```rust
fn get_image_file_filter() -> FileFilter {
       let filter = FileFilter::new();
       for format in Pixbuf::formats() {
              for extension in format.extensions() {
                     filter.add_suffix(extension.as_str());
              }

              for mime in format.mime_types() {
                     filter.add_mime_type(mime.as_str());
              }
        }
        filter
}

let dialog = FileChooserNative::builder()
            .transient_for(&self.active_window().unwrap())
            .modal(true)
            .select_multiple(false)
            .filter(&get_image_file_filter())
            .action(FileChooserAction::Open)
            .build();
```

**Backtrace**

The program doesn't crash so there's no backtrace. Running in debug mode doesn't show any difference in logs between `FileChooserNativeBuilder::filter()` and `FileChooserNative::set_filter()`

**Comment by bilelmoussaoui** [comment]
Closing as this is the expected behaviour of the property. the filter property is for the "default" filter as mentioned above
