### ISSUE TITLE
[FEATURE REQUEST] Add basic testing infrastructure and documentation

### ISSUE THREAD

**Issue by AaronErhardt** [gtk-rs/gtk4-rs#951]
There should be some testing infrastructure for gtk4-rs apps and internal code that's reusable and documented.

At least something as a convenient entry point for running tests that rely on GTK (something similar to https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/lib.rs#L62).

I've seen https://github.com/gtk-rs/gtk-test/issues/47 and to be honest, I don't have a lot of resources currently, too, but I hope we can at least work together to enable some basic functionality for the upcoming release.

**Comment by bilelmoussaoui** [comment]
cc @jf2048 as you wanted the test_synced to be public as well

**Comment by bilelmoussaoui** [comment]
I am not sure what would be needed other than making that function available + some examples. I wonder if the `gtk_test_init` would be any useful for this case?

**Comment by jf2048** [comment]
Yes, it seems like that needs to be public (or it needs to be copied) if someone wants unit tests for any gtk widgets, or for gtk4-macros, libadwaita-rs, libshumate-rs, libpanel-rs, sourceview5-rs, etc. Seeing a gtk4-test would also be good and probably not too hard

**Comment by jf2048** [comment]
This issue is still a problem though: #811

Although maybe it's not that bad in practice since the tests all run synchronously anyway?
