### ISSUE TITLE
[BUG] The async example in book is invalid

### ISSUE THREAD

**Issue by womeng2009** [gtk-rs/gtk4-rs#960]
**Bug description**
#### Link:
https://gtk-rs.org/gtk4-rs/stable/latest/book/main_event_loop.html
#### Question:
When I try to use the async example in the book, the main thread is blocked.
Example code is:
```
// Connect to "clicked" signal of `button`
button.connect_clicked(move |button| {
   let main_context = MainContext::default();
   // The main loop executes the asynchronous block
   main_context.spawn_local(clone!(@weak button => async move {
       // Deactivate the button until the operation is done
       button.set_sensitive(false);
       timeout_future_seconds(5).await;
       // Activate the button again
       button.set_sensitive(true);
   }));
});
```

#### Environment info:
rust:1.59.0
gtk:0.4.6
os:windows 10
toolchain:gnu

**Comment by sdroege** [comment]
Works fine here when running `cargo run --bin main_event_loop_4` in `gtk4-rs/book/listings`. Is that what you're trying?

If not, can you provide the whole code you're trying to run and also a backtrace of at least the main thread while it is blocked?

**Comment by womeng2009** [comment]
> 



> Works fine here when running `cargo run --bin main_event_loop_4` in `gtk4-rs/book/listings`. Is that what you're trying?
> 
> If not, can you provide the whole code you're trying to run and also a backtrace of at least the main thread while it is blocked?

Thank you for your prompt reply.
I try to modify the clipboard example and change the click event, the code is as follows:
```
paste_btn.connect_clicked(clone!(@weak clipboard, @weak into_entry => move |_btn| {
        clipboard.read_text_async(gio::Cancellable::NONE, clone!(@weak into_entry => move|res| {
            //edit start
            let five_seconds = Duration::from_secs(5);
            thread::sleep(five_seconds);
            edit end
            if let Ok(Some(text)) = res {
                into_entry.set_text(&text);
            }
        }));
    }));
```
then I try to run:
`cargo run --bin clipboard`
When I click the paste button, the main window is blocked and cannot be moved.
My rust version is 1.59.0, will it be the version reason?

**Comment by sdroege** [comment]
> thread::sleep(five_seconds);

This will block the main thread and is not used in the original example, which instead uses

> timeout_future_seconds(5).await;

**Comment by womeng2009** [comment]
> `main_event_loop_4`

@sdroege 
This is my fault.
I'm sorry, but I still don't understand, how to define a method like timeout_future_seconds, I try to call this method:
```
loop_async().await;
async fn loop_async() {
    for i in 0..100000 {
        println!("i:{}", i);
    }
}
```
But I don't get the expected result.
please help me.

**Comment by sdroege** [comment]
You don't define it, you [call](https://gtk-rs.org/gtk-rs-core/git/docs/glib/fn.timeout_future_seconds.html) it.

**Comment by womeng2009** [comment]
@sdroege 
I think I get it now.
**println! is blocking.**
Thank you for your answer.

**Comment by sdroege** [comment]
Yeah if `stdout` is "full" then `println!` will block
