### ISSUE TITLE
[FEATURE REQUEST] Using `gtk::gdk::Key` with `closure_local!`

### ISSUE THREAD

**Issue by sumibi-yakitori** [gtk-rs/gtk4-rs#972]
Thank you for the wonderful crate.
`gtk::gdk::Key` does not implement `FromValue` and cannot be used with `closure_local!`

```rust
let text_view = gtk::TextView::new();
let controller = gtk::EventControllerKey::new();
let closure = closure_local!(
  @watch text_view =>
  move |_: &gtk::EventControllerKey,
    key: gtk::gdk::Key,
    _: u32,
    _: gtk::gdk::ModifierType| { gtk::Inhibit(false) }
);
controller.connect_closure("key-pressed", false, closure);
text_view.add_controller(&controller);
```

```sh
the trait bound `Key: FromValue<'_>` is not satisfied
the trait `FromValue<'_>` is not implemented for `Key`
```

**Comment by sdroege** [comment]
There's no `GType` for `gdk::Key` so this wouldn't work. You could pass it around as `u32` though (that's what it actually is), or as a `char`.

**Comment by bilelmoussaoui** [comment]
Can't we implement  FromValue as if it was a u32?

**Comment by bilelmoussaoui** [comment]
Also, why are you using closure_local and manually connecting to the event, there is already an auto generated function for connecting to the event..

**Comment by sdroege** [comment]
> Can't we implement FromValue as if it was a u32?

Oh yes, that would work.

**Comment by bilelmoussaoui** [comment]
I am going to re-open this so we can handle that. It will be useful for composite template callbacks anyway

**Comment by sumibi-yakitori** [comment]
@bilelmoussaoui 
> Also, why are you using closure_local and manually connecting to the event, there is already an auto generated function for connecting to the event.

Sorry to ask this crate usage question here, but if I are using event controllers, I am not sure if the closure is automatically disconnected when the widget to which the controller is added is destroyed.
So I was thinking of using @watch for now.

In GTK, is `remove_controller` usually called automatically when a widget is destroyed?

**Comment by sumibi-yakitori** [comment]
> In GTK, is remove_controller usually called automatically when a widget is destroyed?

https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkwidget.c#L7617
Sorry. It was called.
So am I correct in assuming that the closure is automatically disconnected?

**Comment by bilelmoussaoui** [comment]
Yes it is because the event controller is dropped once the widget is removed. Otherwise you will have a memory leak here
