### ISSUE TITLE
[FEATURE REQUEST] chain_property_optional()

### ISSUE THREAD

**Issue by YaLTeR** [gtk-rs/gtk4-rs#980]
So that in a chain like this:
```rust
self.tab_view
    .property_expression("selected-page")
    .chain_property::<adw::TabPage>("child")
    .chain_property::<Page>("scale")
    .chain_closure::<String>(closure!(|_: Option<glib::Object>, scale: f64| {
        format!("{:.1}%", scale * 100f64)
    }))
    .bind(&*self.scale_entry, "text", None::<&adw::TabView>);
```
I can use `chain_property_optional()`, receive `scale: Option<f64>` into the final closure and handle the `selected-page` is `None` case. Kind of an `and_then()` for expressions.

**Comment by bilelmoussaoui** [comment]
cc @SeaDve

**Comment by jf2048** [comment]
This can't be done, any closure expression will never evaluate if a property expression resolves to null

**Comment by jf2048** [comment]
This is a general concern with property expressions BTW, you have to be careful not to let any of the objects become null or the view will become stale

**Comment by bilelmoussaoui** [comment]
I suppose we can close this for now until something changes upstream.
