### ISSUE TITLE
Add traits of `gtk::subclass::prelude` to `gtk::prelude`

### ISSUE THREAD

**Issue by Hofer-Julian** [gtk-rs/gtk4-rs#986]
Code related to subclassing now has to import traits from `gtk::subclass::prelude` next to `gtk::prelude`.
We could add the traits currently in `gtk::subclass::prelude` to `gtk::prelude` so users only have to import the latter from now on.

**Comment by bilelmoussaoui** [comment]
so any opinions on including the subclassing traits in the main prelude?

**Comment by Hofer-Julian** [comment]
I think it's good idea to include them.

(and drop the subclass prelude)

**Comment by sdroege** [comment]
It's adding a lots of new traits to the prelude that you don't need outside the `imp` modules though.

**Comment by bilelmoussaoui** [comment]
> (and drop the subclass prelude)

That seems kind of wrong. The whole point is to split the use cases like we don't include glib::translate::* in glib's prelude for example.

**Comment by Hofer-Julian** [comment]
> It's adding a lots of new traits to the prelude that you don't need outside the `imp` modules though.

If you need it for the method imp() as well then you need it in more modules.

Tbf I don‘t really see yet where additional traits in scope might be a problem.

**Comment by Hofer-Julian** [comment]
> > (and drop the subclass prelude)
> 
> That seems kind of wrong. The whole point is to split the use cases like we don't include glib::translate::* in glib's prelude for example.

If the subclassing traits are included the main prelude, when would you then use the subclassing prelude?

**Comment by bilelmoussaoui** [comment]
Closing in favour of https://github.com/gtk-rs/gtk-rs-core/issues/781
