### ISSUE TITLE
Need subclassing support for gtk::EventController and gtk::Gesture

### ISSUE THREAD

**Issue by hemidark** [gtk-rs/gtk4-rs#988]
I was trying to figure out how to subclass gtk::Gesture, or even gtk::EventController, but it seems neither is subclassable yet (no IsSubclassable implementation or GestureImpl trait). This is severely limiting for implementing custom widgets.

What is involved with adding subclassing support for these types? Is it very easy to do?

**Comment by hemidark** [comment]
(Also, in the meantime, is there a better workaround than relying on EventControllerLegacy?)

**Comment by sdroege** [comment]
They can't be subclassed outside GTK by design. On the C level the class struct of `gtk::EventController` is not public, for example.

What are you trying to do exactly?

**Comment by hemidark** [comment]
That's unfortunate. I'm writing an app that takes tablet input, so I need access to the motion history, extra axes, device, tool, and timestamp from the Gdk events.

GestureDrag seems like a reasonable fit, for drawing, but it only seems to expose the starting xy position and the current offset from it. (Though in practice I'd also like to track the "hover" events from before the stylus makes contact.)

EventControllerLegacy will do the job, at least. I'm going to close this because it's really an upstream issue.

**Comment by hemidark** [comment]
GestureStylus _might_ also do. I'll look into that some more.
